### ISSUE TITLE
Cannot Build Unity Project in mosa/m66-peercc-unity

### ISSUE THREAD

**Issue by tomitrescak** [webrtc-uwp/webrtc-uwp-sdk#102]
Hi, looks like the unity project is out of sync on this Branch. Would you be able to point me to the correct version of the unity project? I am seeing these errors when building the project:

```
Assets\Scripts\ControlScript.cs(496,28): error CS1061: 'Conductor' does not contain a definition for 'OnAddRemoteStream' and no extension method 'OnAddRemoteStream' accepting a first argument of type 'Conductor' could be found (are you missing a using directive or an assembly reference?)

Assets\Scripts\ControlScript.cs(497,28): error CS1061: 'Conductor' does not contain a definition for 'OnRemoveRemoteStream' and no extension method 'OnRemoveRemoteStream' accepting a first argument of type 'Conductor' could be found (are you missing a using directive or an assembly reference?)

Assets\Scripts\ControlScript.cs(498,28): error CS1061: 'Conductor' does not contain a definition for 'OnAddLocalStream' and no extension method 'OnAddLocalStream' accepting a first argument of type 'Conductor' could be found (are you missing a using directive or an assembly reference?)

Assets\Scripts\ControlScript.cs(569,30): error CS0176: Member 'Conductor.GetAudioCodecs()' cannot be accessed with an instance reference; qualify it with a type name instead

…. And much more …
```

Any help is greatly appreciated

**Comment by morosev** [comment]
Hi @tomitrescak. You are right, it is out of sync. On M66 branch Unity integration is still work in progress. It will be ready soon, but you can use M62 version instead (https://github.com/ortclib/ortclib-sdk/tree/Mosa/m62-peercc-unity) until M66 gets ready. Just read and follow the instructions for Unity build in README.md.

**Comment by morosev** [comment]
Update - `Mosa/m62-peercc-unity` branch has been merged to `releases/m62 branch`. The Unity application is now part of m62 branch. You can use this link further: https://github.com/ortclib/ortclib-sdk/tree/releases/m62

**Comment by cy238** [comment]
@morosev Any update on this? Also, will it still be possible to use .NET scripting backend with the M66 version when it is ready?
