### ISSUE TITLE
Building in visual studio crashes computer

### ISSUE THREAD

**Issue by wingchangwow** [webrtc-uwp/webrtc-uwp-sdk#105]
I got the prepare script to run and finish correctly, but when I get into the solution in Visual Studio 2017 and attempt to build the PeerCC project, it takes nearly 10 mins (and seems to be working fine) until it hits RTCOfferOptions.cpp, causing the computer to hang up entirely. The display and taskbar goes blank periodically, and I can't even open the task manager to troubleshoot. The system stays totally unresponsive even when left alone for extended periods of time. Any help would be appreciated.

HP Z840 Workstation
2x Intel Xeon CPU E5-2650 v4 @ 2.20GHz 
32.0 GB RAM
Windows 10 Pro v1809 64bit build 17763.253

**Comment by timothy003** [comment]
The compiler uses a lot of memory for the ZS generated C++/WinRT wrappers. Each CL process needs about 2 GB. On my machine with an i7-2600K and 8 GB of RAM, it takes 46 minutes and to build the wrappers and just barely finishes without Windows running out of virtual memory.

Turns out every source file includes a bunch of C++/WinRT headers, which are incredibly large and slow to process. After adding them to the precompiled header, my system stopped running OOM and the project was built in 2 minutes.

I modified `webrtc\windows\projects\msvc\Org.WebRtc.Universal\pch.h` as follows:

```cpp
//
// pch.h
// Header for platform projection include files
//

#pragma once

#include "cppwinrt_Helpers.h"

#include "winrt/Windows.Devices.Enumeration.h"
#include "winrt/Windows.Foundation.h"
#include "winrt/Windows.Media.Core.h"
#include "winrt/Windows.UI.Core.h"
#include "winrt/Windows.UI.Xaml.Controls.h"
#include "winrt/Org.WebRtc.h"
```

Before:

```
Project Performance Summary:
       38 ms  C:\webrtc-uwp-sdk\webrtc\windows\projects\msvc\Org.WebRtc.WrapperGlue.Universal\Org.WebRtc.WrapperGlue.vcxproj   6 calls
    2775506 ms  C:\webrtc-uwp-sdk\webrtc\windows\projects\msvc\Org.WebRtc.Universal\Org.WebRtc.vcxproj   1 calls

Task Performance Summary:
    [...]
     3513 ms  XDCMake                                    1 calls
     6109 ms  MIDL                                       8 calls
     9631 ms  Exec                                       3 calls
    31905 ms  Link                                       1 calls
    2722614 ms  CL                                         2 calls
```

After:

```
Project Performance Summary:
       39 ms  C:\webrtc-uwp-sdk\webrtc\windows\projects\msvc\Org.WebRtc.WrapperGlue.Universal\Org.WebRtc.WrapperGlue.vcxproj   6 calls
    134414 ms  C:\webrtc-uwp-sdk\webrtc\windows\projects\msvc\Org.WebRtc.Universal\Org.WebRtc.vcxproj   1 calls

Task Performance Summary:
    [...]
     2001 ms  XDCMake                                    1 calls
     2696 ms  Exec                                       3 calls
     6444 ms  MIDL                                       8 calls
    17364 ms  Link                                       1 calls
    104845 ms  CL                                         2 calls
```

**Comment by djee-ms** [comment]
Thanks @timothy003 that's awesome, I was suspecting something like that but didn't take the time to figure it out. I opened a PR to add the change.

**Comment by jamescadd** [comment]
Huge thanks to @timothy003 for this! Since the PR is merged I'll close the issue, please reopen otherwise.
