### ISSUE TITLE
Debug build of Org.WebRtc fails with 251 missing externals

### ISSUE THREAD

**Issue by r-b-us** [webrtc-uwp/webrtc-uwp-sdk#11]
Tried multiple machines, Windows SDKs etc but cannot build the Org.WebRtc wrapper. Get 481 linker errors, most related to missing SSL and encryption, some to protobuf. Tried x64 and x86 - both the same. Perl is version 5.22.1. prepare.bat chooses SDK 14393 by default although I have tried forcing various others including 10240. Windows is 15063. 

Release build seems to work fine, however.

**Comment by navrkald** [comment]
Hi @r-b-us check the commit above.

**Comment by SergioOpenPeer** [comment]
@r-b-us  Sorry, there was some merge issues earlier. You can try now. It should work

**Comment by navrkald** [comment]
It worked. You should close this issue.
