### ISSUE TITLE
Upstreaming D3D11 frame source

### ISSUE THREAD

**Issue by Holo-Krzysztof** [webrtc-uwp/webrtc-uwp-sdk#115]
As a heads-up, I have talked to the higher-ups and they're fine with contributing back our D3D11 frame source if you're still interested.
We're currently in the process of making the existing UWP MF encoder D3D-aware so that we don't need to explicitly download the texture from the GPU for encoding; as soon as that is done I could probably start with opening up the code.
I'd appreciate some guidance on where to put it in the source tree. Currently it lives in our code in a subdirectory of `examples`, but I guess it should reside somewhere in `media` or elsewhere.

Also, we'd like to add our company to the list of WebRTC developers. Is modifying the AUTHORS file the right way to do this?

**Comment by jamescadd** [comment]
That's great news!  Yeah let's find the right place for you to contribute this back.  It may be easiest to setup a quick call to review what you've done with @robin-raymond and @morosev and go from there.  I'd also like to invite some of the people who worked on 3DSTK to the call as well as they're doing some related work on the media stack.  We can do that whenever you like, just lmk.

On contributions, yes that's right about adding your company to AUTHORS.  See step #3 here - let me know if you get stuck and I'll see if I can help:
https://webrtc.org/contributing/

**Comment by Holo-Krzysztof** [comment]
Alright! I'll contact you probably next week about that because right now the code is a bit of a mess due to the work-in-progress MF/D3D integration.

Should I do that in this repo or in Google's (or both)?

**Comment by jamescadd** [comment]
Sounds good, looking forward to it!  Without seeing the code I'm not sure how to advise on which repo to do the work.  You're definitely welcome to submit to releases/m71 here and we would like the contribution.  Submitting to Google directly is of course an option, but hard to advise on that until we see what's changed.  Your call :)

**Comment by Holo-Krzysztof** [comment]
Sorry for the delay, I was out of office for most of last week.

Long story short, the MF/D3D integration didn't work out, so we're putting that on the backlog and want to upstream what we already had working (download to staging texture, convert to NV12 on CPU). I'll put the code so that it builds without yet another submodule to set up for now and we can decide later where it will end up.

We could schedule a call for later this week, (maybe on Thursday?), so we have time to prepare and get the right people on the call. If there are no problems with the build system, the code should be up on github today-ish.

**Comment by jamescadd** [comment]
Thanks Krzysztof, let me ask a few people to review this internally and we can setup some time to meet. Will send an email with a few options. Appreciate the submission!

**Comment by jamescadd** [comment]
Merged - thanks again!
