### ISSUE TITLE
Calling RTCPeerConnection.CreateOffer fails

### ISSUE THREAD

**Issue by tomzorz** [webrtc-uwp/webrtc-uwp-sdk#116]
Hi

We've been working with the webrtc-uwp-sdk, and we're having some issues with the `RTCPeerConnection.CreateOffer` call. (Technically on this fork https://github.com/flufy3d/webrtc-uwp-sdk/tree/WebRtcUnity/common/windows/samples/PeerCCUnity but as you can see from the changes it shouldn't really matter in this case.)

The code is very similar to the sample, first we create a RTCPeerConnection object, set up events, add local video and audio tracks, then try to create the offer to send to our signalling server. Upon doing that I get the following exception:

```
System.Runtime.InteropServices.COMException (0xA004139F): 
The text associated with this error code could not be found.  The text associated with this error code could not be found. 
```

I saw from other issues here that the whole setup is sensitive to which thread its being called from, so now I've experimented with that with no success.

Any idea what I might be doing wrong? First I thought it was the fact that we didn't add a local video track (as we only want to receive video, plus send/receive audio) but that didn't help.

Thanks,
Tamás

**Comment by tomzorz** [comment]
The lines is question

```
var offerOptions = new RTCOfferOptions();
var offer = await _rtcPeerConnection.CreateOffer(offerOptions); // 👈 exception when calling this ⚠
```

where `_rtcPeerConnection` is a `RTCPeerConnection` object.

**Comment by jamescadd** [comment]
i'm not sure if master is the best place to fork for unity support right now - @robin-raymond @morosev any guidance?

**Comment by tomzorz** [comment]
@jamescadd so in our fork above the PeerCC sample works, we have video and audio both ways. But when I started using bits and pieces of that to hook everything up to our server infrastructure, that's when I get the error. Question is more like... what can I be doing wrong to get an exception by the CreateOffer method? Almost same code in the signaller/conductor classes works. In my replacement class it doesn't.

**Comment by tomzorz** [comment]
Found the actual issue, see #116 - closing this.
