### ISSUE TITLE
No video/audio [mosa/m66-peercc-unity]

### ISSUE THREAD

**Issue by cy238** [webrtc-uwp/webrtc-uwp-sdk#117]
I cannot get the video/audio connection working in mosa/m66-peercc-unity. Building with the new python scripts worked fine. After adding a call to `Conductor.SelectVideoDevice(...)` to `ControlScript` there were no errors/exceptions when selecting a caller. Unfortunately the textures just stay blank.

Is this even implemented yet? `CreateLocalMediaStreamSource` and `CreateRemoteMediaStreamSource` just return new pointers at the moment. In M62 the `Media` class was used to create source objects instead.

Any input or a rough ETA on this?

**Comment by jamescadd** [comment]
The Unity code has all been merged into releases/m71 at this point, but we're still working through some issues.  Rough ETA is 1-2 weeks.  There's another Unity project in development that should be ready next week as well and leverages M71.  I'll update all the Unity threads when this is ready as well.

**Comment by jamescadd** [comment]
This is now working in releases/m71.  Please open an issue if you have issues on that branch.
