### ISSUE TITLE
Branches

### ISSUE THREAD

**Issue by markgrossnickle** [webrtc-uwp/webrtc-uwp-sdk#120]
Is there a breakdown of what each branch represents?  I've seen a lot of mentions that m62 is the Unity branch of record. What does m62 stand for? How about the rest of the m's?  As someone new to this library, how do I go about understanding which branch to be on?  

Feel free to delete this ticket if this isn't the right place to ask. I realize this isn't an issue with the code itself but more an issue of the organization of the repository.

**Comment by Holo-Krzysztof** [comment]
Basically, the M stands for milestone from what I know; WebRTC upstream follows Chromium/Chrome releases, so they share versioning info from what I know.

Here are M73 release notes from Google, for example: https://groups.google.com/forum/#!topic/discuss-webrtc/l0gc3RjBhc0

**Comment by jamescadd** [comment]
Thanks once again Krzysztof!  I'll add this to the docs I'm working on. I would add that when you see branches that start with someone's name and a date they are feature branches.  You can see what's in progress by keeping an eye on those. https://github.com/webrtc-uwp/webrtc-uwp.github.io/tree/James/20190225-m71-docs
