### ISSUE TITLE
How can I start a video call on a computer which has no camera and can see the frame from the remote client

### ISSUE THREAD

**Issue by hanzz0502** [webrtc-uwp/webrtc-uwp-sdk#121]
I want to start a call using peerconnection_client.exe on a computer which has no camera.Why I can't see the frame from the remote client when I shield the sentences creating the instance of videoTrack ?Is  the instance of videoTrack necessary in starting a call? 
Last but not least,how can I start a call on a computer which has no camera?

**Comment by jamescadd** [comment]
The latest release of the SDK now supports devices with no camera or microphone.  Documentation is available here: https://github.com/webrtc-uwp/webrtc-uwp.github.io/blob/releases/m71/how-to-device-capture-removal.md

Thanks,
James
