### ISSUE TITLE
Add configuration for using only datachannels

### ISSUE THREAD

**Issue by AnthonyM** [webrtc-uwp/webrtc-uwp-sdk#125]
Currently the library expects that the user will be capturing user audio/video input. This restricts the possible use cases and makes the library unusable in cases where capturing input isn't supported. 

I've worked around this by modifying the code in impl_org_webRtc_WebRtcLib.cpp to use 
webrtc::CreateModularPeerConnectionFactory, and passing nullptr instead of actual encoders

```
  peerConnectionFactory_ = ::webrtc::CreateModularPeerConnectionFactory(
      networkThread.get(), workerThread.get(), signalingThread.get(), nullptr,
      nullptr, nullptr, nullptr);
```

This seems to work fine for my use case, but I'm wondering if it's the best way. 

Is making this a configuration option something that this project would support? I can submit a PR in that case. If not we'll probably have to go and build it without modifications instead.

**Comment by jamescadd** [comment]
Hi Anthony, thanks for the suggestion.  Is this sufficient for your scenarios?  If not I would like to learn more and we can potentially take a PR for this.  Appreciate the offer!
https://github.com/webrtc-uwp/webrtc-uwp.github.io/blob/James/20190225-m71-docs/how-to-device-capture-removal.md

Thanks,
James

**Comment by AnthonyM** [comment]
That guide worked great.
