### ISSUE TITLE
peercc sample scene ressolution problem

### ISSUE THREAD

**Issue by datHSOsnabrueck** [webrtc-uwp/webrtc-uwp-sdk#129]
I think, this question related to the topic below:
[https://github.com/Microsoft/WebRTC-universal-samples/issues/40#issuecomment-457271135](url)
I have the same issues after deploying the unity solution from branche releases/m71
1. the scene has been zoom in from the first start although changing the camera position and the menu panel in unity editor but no help)
2.  After connecting both hololens and pc ,I can not see the peer of pc from the available peer list in hololens but in pc i can see the hololens in the available peer list. 

I used pc as server and client simultaneously. 
in console of server i received alternate this:
Total connected: 2
New connection...
Disconnecting socket
Total connected: 2
New connection...
Disconnecting socket
Total connected: 2

Any corrections for this problem or has anyone been faced with this problem before?

**Comment by jamescadd** [comment]
Try using a different server for signaling.  In the past I have not been able to use the same machine as both a client and the signaling server, if memory serves it ends up getting IPv6 addresses in that circumstance.

**Comment by datHSOsnabrueck** [comment]
@jamescadd  thx you for the answer.
The first problem got fixed in unity.
The second problem still happen.
Somehow I use a notebook to run server with standalone uwp app. The other notebook I start a standalone uwp app and I can start the video call between 2 notebooks.  But the combination hololens and notebook seem not to work. because hololens never detected new peer. 
 
is the simultaneously changing status below normal or its indicate a bug in the controlscripts ?
New connection...
Disconnecting socket
Total connected: 2

**Comment by datHSOsnabrueck** [comment]
So I found out the the reason, which cause the problem.

```
#if !UNITY_EDITOR
        RunOnUiThread(() =>
        {
            Task.Run(async () => { RequestAccessForMediaCaptureAndInit(); });
        });

#endif
```

inside the _controlscripts.cs_ function, there is  _RequestAccessForMediaCaptureAndInit()_ function, which use to initialize the conductor and other stuff (signalling callback...)
However this function was never called so in hololens, no peer got detected.

Anyone could help me ?
