### ISSUE TITLE
Error running WebRTC prepare script

### ISSUE THREAD

**Issue by rogeru** [webrtc-uwp/webrtc-uwp-sdk#13]
What did I try:
git clone --recursive https://github.com/webrtc-uwp/webrtc-uwp-sdk.git
cd webrtc-uwp-sdk
bin\prepare.bat

Getting error:
CRITICAL ERROR: WebRTC invalid folder structure. ..\..\..\webrtc\windows\templates\gns\args.gn does not exist

Using Windows 10 Pro 1703

**Comment by berthold08** [comment]
I have get the same problem with the run of the batchfile "bin\prepare.bat" on windows 10.
The problem is that all downloaded "bin\x...x.bat" files have a lineending "LF" (UNIX).
You have to convert ALL files "bin\x....x.bat" to the lineending "CR+LF" (WINDOWS).
After the conversion the batchfiles runs in a cmd shell. Try "bin\prepare.bat -help or -diagnostic".

**Comment by rogeru** [comment]
@berthold08 thanks for the feedback, but after changing the bat files to windows lineendings I still have the same error. Were you able to run the prepare successfully?

```
C:\webrtc-uwp-sdk>bin\prepare.bat
Could Not Find C:\webrtc-uwp-sdk\python-2.7.6.msi
Could Not Find C:\webrtc-uwp-sdk\python-2.7.6.msi
Could Not Find C:\webrtc-uwp-sdk\python-2.7.6.msi

Running prepare script ...

Preparing webRTC and ORTC development environment ...
Preparing development environment for ARM, x64, x86 and win32 platforms ...
Cloning into 'ortc-binaries'...
remote: Counting objects: 15, done.
remote: Total 15 (delta 0), reused 0 (delta 0), pack-reused 15
Unpacking objects: 100% (15/15), done.
COPY ..\ortc-binaries\Release\libOrtc.dylib ortc\apple\libs\libOrtc.dylib
CALL print 4                                                                                                             Copied file ..\ortc-binaries\Release\libOrtc.dylib to ortc\apple\libs\libOrtc.dylib

Running WebRTC prepare script ...

CRITICAL ERROR: WebRTC invalid folder structure. ..\..\..\webrtc\windows\templates\gns\args.gn does not exist

FAILURE:Preparing WebRTC development environment has failed.
The system cannot find the batch label specified - resetSDKVersion
=======   WebRTC prepare script summary   =======
=======   platform   =========   result   =======
            arm                  failed
=================================================

            x86                 not run
            win32               not run
=================================================


C:\webrtc-uwp-sdk>git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

        modified:   bin (modified content)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        ortc/

no changes added to commit (use "git add" and/or "git commit -a")

C:\webrtc-uwp-sdk>
```

**Comment by berthold08** [comment]
Hallo, with this environment the batchfile is working on Windows 10.
start windows Powershell as Administrator
change to normal command shell

Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. Alle Rechte vorbehalten.

PS C:\WINDOWS\system32>

PS C:\WINDOWS\system32> cmd
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. Alle Rechte vorbehalten.
C:\WINDOWS\system32>x:
X:\>cd work
X:\work>cd op_webrtc_uwp
X:\work\op_webrtc_uwp>cd webrtc-uwp-sdk
X:\work\op_webrtc_uwp\webrtc-uwp-sdk>dir
 Datenträger in Laufwerk X: ist Data
 Volumeseriennummer: 40F3-C968

 Verzeichnis von X:\work\op_webrtc_uwp\webrtc-uwp-sdk

18.10.2017  16:12    <DIR>          .
18.10.2017  16:12    <DIR>          ..
11.10.2017  14:46             3.454 .gitmodules
17.10.2017  18:24    <DIR>          bin
11.10.2017  14:46    <DIR>          common
11.10.2017  14:57    <DIR>          docs
11.10.2017  14:46             1.104 README.md
11.10.2017  14:46    <DIR>          webrtc
               2 Datei(en),          4.558 Bytes
               6 Verzeichnis(se), 54.911.729.664 Bytes frei

X:\work\op_webrtc_uwp\webrtc-uwp-sdk>where git
x:\work\webrtc\depot_tools\git.bat
C:\Program Files (x86)\Git\cmd\git.exe
C:\Program Files\Git\cmd\git.exe

X:\work\op_webrtc_uwp\webrtc-uwp-sdk>where python
x:\work\webrtc\depot_tools\python.bat
X:\work\webrtc\depot_tools\win_tools-2_7_6_bin\python\bin\python.exe
C:\Python27\python.exe

X:\work\op_webrtc_uwp\webrtc-uwp-sdk>where git
x:\work\webrtc\depot_tools\git.bat
C:\Program Files (x86)\Git\cmd\git.exe
C:\Program Files\Git\cmd\git.exe

X:\work\op_webrtc_uwp\webrtc-uwp-sdk>bin\prepare.bat -diagnostic
Diagnostic mode - checking if some required programs are missing
================================================================================

Perl                                installed
Python                              installed
Git                                 installed

================================================================================

Diagnostic finished

X:\work\op_webrtc_uwp\webrtc-uwp-sdk>bin\prepare.bat -help

   Available parameters:

        -diagnostic             Flag for runing check if system is ready for webrtc development.

        -help           Show script usage

        -logLevel       Log level (error=0, info =1, warning=2, debug=3, trace=4)

        -noEventing     Flag not to run eventing preparations for Ortc

        -target         Name of the target to prepare environment for. Ortc or WebRtc. If this parameter is not set dev
environment will be prepared for both available targets.

        -platform       Platform name to set environment for. Default is All (win32,x86,x64,arm)


X:\work\op_webrtc_uwp\webrtc-uwp-sdk>bin\prepare.bat -logLevel=4 -noEventing=1 -target=WebRtc -platform=x86

Running prepare script ...

Running script parameters:
Target: WebRtc
Platform: x86
Log level: 4
Preparing WebRtc development environment ...
Preparing development environment for x86 platform...
Python is present.

Running WebRTC prepare script ...
=================================
Preparing WebRTC development environment for x86 platform ...
Executing prepareWebRTC function
Pushed webrtc\xplatform\webrtc path
Executing generateChromiumFolders function
chromium\src folder already exists
chromium\src\tools folder already exists
chromium\src\third_party folder already exists
chromium\src\third_party\winsdk_samples folder already exists
chromium\src\third_party\libjingle\source\talk\media\testdata\ folder already exists
third_party folder already exists
tools folder already exists
Executing makeJunctionLinks function
        1 Datei(en) kopiert.
        1 Datei(en) kopiert.
        1 Datei(en) kopiert.
        1 Datei(en) kopiert.
0> File buildtools\win\gn.exe exists and SHA1 matches. Skipping.
Success!
Downloading 1 files took 0.062000 second(s)
0> File buildtools\win\clang-format.exe exists and SHA1 matches. Skipping.
Success!
Downloading 1 files took 0.032000 second(s)
10.0.14393 SDK version will be used
Executing generateProjects function
Generating WebRTC projects for x86 platform ...
Created folder out\winuwp_10_x86_debug
Copied
Generating Visual Studio projects took 480ms
Done. Made 410 targets from 104 files in 16150ms
Copied
Created folder out\winuwp_10_x86_release
Copied
Generating Visual Studio projects took 569ms
Done. Made 410 targets from 104 files in 15193ms
Copied
Popped webrtc\xplatform\webrtc path

Success: WebRTC development environment is prepared.
=======   WebRTC prepare script summary   =======
=======   platform   =========   result   =======
            arm                 not run
            x64                 not run
            x86                 prepared
            win32               not run
=================================================


Success: Development environment is set.
Total execution time: 00:00:45 (45s total)


X:\work\op_webrtc_uwp\webrtc-uwp-sdk>

**Comment by navrkald** [comment]
Had same problem. Had in path "!" (exclamation mark). After remove it from path to repo and clean repo from administrator cmd using https://gist.github.com/nicktoumpelis/11214362 helped.

**Comment by rogeru** [comment]
Not sure what's going on here, but I re-cloned fresh. Reinstalled python and perl, and depot-tools.
Still get the same error.

```
C:\Program Files\Git\cmd\git.exe

C:\workspace\webrtc-uwp-sdk>where python
C:\workspace\depot_tools\python.bat
C:\Python27\python.exe

C:\workspace\webrtc-uwp-sdk>where perl
C:\Strawberry\perl\bin\perl.exe

C:\workspace\webrtc-uwp-sdk>bin\prepare -diagnostic
Diagnostic mode - checking if some required programs are missing
================================================================================

Perl                                installed
Python                              installed
Git                                 installed

================================================================================

Diagnostic finished

C:\workspace\webrtc-uwp-sdk>bin\prepare.bat -logLevel=4 -noEventing=1 -target=WebRtc -platform=x86

Running prepare script ...

Running script parameters:
Target: WebRtc
Platform: x86
Log level: 4
Preparing WebRtc development environment ...
Preparing development environment for x86 platform...
Python is present.

Running WebRTC prepare script ...

CRITICAL ERROR: WebRTC invalid folder structure. ..\..\..\webrtc\windows\templates\gns\args.gn does not exist

FAILURE:Preparing WebRTC development environment has failed.
The system cannot find the batch label specified - resetSDKVersion
=======   WebRTC prepare script summary   =======
=======   platform   =========   result   =======
            arm                  failed
=================================================

            x86                 not run
            win32               not run
=================================================


C:\workspace\webrtc-uwp-sdk>
```

I don't understand how this can work with this relative path in prepareWebRtc.bat
```
SET webRTCGnArgsTemplatePath=..\..\..\webrtc\windows\templates\gns\args.gn
```

**Comment by vmancic** [comment]
@rogeru Could you please try fresh clone again. I think I had this or similar issue earlier, but I have just tried fresh clone again and prepare finished successfully.
