### ISSUE TITLE
MRC not working [releases/m71 PeerCCUnity]

### ISSUE THREAD

**Issue by TiagoShen** [webrtc-uwp/webrtc-uwp-sdk#130]
Hi

I am able to run the peercc example but the mrc is not working (both HoloLens app's local video surface and PC's remote video frame can only get plane video stream from HoloLens's PV camera). Any suggestions?
![image](https://user-images.githubusercontent.com/21050140/54795133-ec47ca80-4c85-11e9-9e2d-584485058015.png)

In addition, when I open the Unity project, there are two missing script in the EventSystem object, although I can successfully build the project.
![image](https://user-images.githubusercontent.com/21050140/54794659-835f5300-4c83-11e9-8432-e59cf18d8aba.png)

Sorry that I'm still new in Unity and IL2CPP. I wonder if there's any way I can see c# script's debug log in the VS output window. Like these few lines in ControlScript.cs. Since it wasn't a problem when using .Net scripting backend.
![image](https://user-images.githubusercontent.com/21050140/54794906-d38ae500-4c84-11e9-8170-9da82a7de01d.png)

Thanks in advance.

**Comment by datHSOsnabrueck** [comment]
@TiagoShen At lease you can see plain video. I also have the same thing with eventsystem.
Did you just follow the readme.md in releases/m71 and you can see in hololens the pc peer in the available peer list?
which unity version do you use and could you share the controlscripts file ?

**Comment by TiagoShen** [comment]
@datHSOsnabrueck I am using Unity 2018.3.6f1. ControlScript.cs is included in the original Unity project under Asset/Scripts. I can see plane video streams on both clients, but the frame rate is quite low and almost down to zero after streaming for a few seconds.

**Comment by TiagoShen** [comment]
I've tried switch to Release build, the performance issue is gone, but mrc is still not working. I'm using Visual Studio 2017 Community 15.9.9, could it be related to my VS version? 
In addition, the hololens client quit unexpectedly every third call attempt.

**Comment by YUEJINYUAN** [comment]
@TiagoShen QQ or Wechat? I need your help urgently. If I use SDK17134 or 17763 on IL2CPP, my Unity build will fail.

**Comment by morosev** [comment]
@TiagoShen Please check the following line:
https://github.com/webrtc-uwp/PeerCC/blob/releases/m71/ClientCore/Signalling/Conductor.cs#L762
The MRC is set to disabled status by default. Just change the third parameter in a function call to `true`. Setting of this value should be exposed in the Conductor interface. I created a task for that feature: #133

**Comment by TiagoShen** [comment]
Thanks a lot. MRC is now working perfectly.
