### ISSUE TITLE
How to build for Unity Editor (Win32 - x64)?

### ISSUE THREAD

**Issue by markgrossnickle** [webrtc-uwp/webrtc-uwp-sdk#135]
I am building from cse/m71-ks which seems to be the branch with the latest Mixed Reality Toolkit plugin.  I added some debug logs to see why the Data channel is failing to connect and I wanted to test it in the Unity editor without having to build to the Hololens.  

I am struggling to build for the Win32 platforms. The WSA works fine. 
![image](https://user-images.githubusercontent.com/16213480/55561305-2914b800-56af-11e9-90f0-78818cf1ad57.png)

I mainly need WSA x86 for the Hololens and Win32 x64 for the Unity Editor.  The problem is when I build to Win32 x64 the editor states the following error:

> DllNotFoundException: webrtc_unity_plugin

The webrtc_unity_plugin is set to target the Editor and Standalone.  If I swap the dll I built with the original it works fine (so my Unity settings are OK). 

In the configuration manager in visual studio I see the following options:

![image](https://user-images.githubusercontent.com/16213480/55561545-91fc3000-56af-11e9-81b7-ee84bf9a580f.png)

Drop Down Circled in Blue:
Arm
x86
x64

Drop Down Circled in Red:
ARM
ARM64
Win32  (confusing but I think this means x86 rather than Win32)
x64

I clicked new from the Blue drop down and added Win32 and at first tried to copy from x64 and then tried to copy from empty.   Both times the dll could not be found in Unity.  The second drop down I keep on x64.

Is there another step I am missing to add Win32 support?  Or what am I missing here?  I know it is possible as they exist in @bengreenier's branch:
https://github.com/bengreenier/webrtc-unity-plugin/tree/master/Assets/Plugins/WSA/x86_64
![image](https://user-images.githubusercontent.com/16213480/55562707-c53fbe80-56b1-11e9-869a-10c298e3cbc9.png)

**Comment by morosev** [comment]
@markgrossnickle For win32 build you can just follow the standard build procedure for Windows platform from the command line: https://webrtc.org/native-code/development. You have to specify the target `webrtc_unity_plugin` as a parameter when you call `ninja` command.
win32 build doesn't require anything from VS solution or UWP wrapper code.

**Comment by markgrossnickle** [comment]
@morosev 
When I follow those instructions it only checks out what is in the webrtc/xplatform/webrtc folder. How do I do a fetch for the windows side of things?  I had been using just git for everything but when I try to call gn gen out/Default it says I need to be inside of a checkout. 

I got further along by following these instructions (but eventually failed as well):
https://github.com/Microsoft/MixedRealityToolkit-Unity/commit/000d2fad897728d0f39b9d06522efc85b545b7c8

**Comment by morosev** [comment]
@markgrossnickle 
Try the following commands. That could be the easiest way to build the plugin for win32.
```
git clone --recursive -b cse/m71-ks https://github.com/webrtc-uwp/webrtc-uwp-sdk.git webrtc-uwp-sdk-m71-ks
cd webrtc-uwp-sdk-m71-ks
scripts\run.py -a prepare -t webrtc -p win --cpus x86 -c debug --noColor --noWrapper
cd webrtc\xplatform\webrtc\out\webrtc_win_x86_debug
set DEPOT_TOOLS_WIN_TOOLCHAIN=0
..\..\..\depot_tools\ninja webrtc_unity_plugin
```

**Comment by markgrossnickle** [comment]
@morosev  Thanks. Perhaps my environment is not setup correctly

When I use python version 3.x I get the following error:
c:\projects\webrtc4\webrtc-uwp-sdk-m71-ks>py -3 scripts\run.py -a prepare -t webrtc -p win --cpus x64 -c debug --noColor --noWrapper
Traceback (most recent call last):
  File "scripts\run.py", line 5, in <module>
    from inputHandler import Input
  File "c:\projects\webrtc4\webrtc-uwp-sdk-m71-ks\scripts\inputHandler.py", line 5, in <module>
    from system import System
  File "c:\projects\webrtc4\webrtc-uwp-sdk-m71-ks\scripts\system.py", line 8, in <module>
    from _winreg import HKEY_LOCAL_MACHINE
ModuleNotFoundError: No module named '_winreg'


When I use Python 2.x I get the following error:

> 0> Failed to fetch file gs://chromium-gn/22d302b1658a293a4997205350751ff309b138c9 for c:\projects\webrtc4\webrtc-uwp-sdk-m71-ks\scripts\..\.\webrtc\xplatform\webrtc\buildtools\win\gn.exe, skipping. [Err: Traceback (most recent call last):
>   File "c:\projects\webrtc4\webrtc-uwp-sdk-m71-ks\webrtc\xplatform\depot_tools\gsutil.py", line 20, in <module>
>     import urllib2
> ModuleNotFoundError: No module named 'urllib2'

]

**Comment by morosev** [comment]
@markgrossnickle Well, I ran the script above and everything passed without any problem. You have to use Python 2.7. Please follow the instructions here: https://github.com/webrtc-uwp/webrtc-uwp-sdk/tree/releases/m71. It should just work if all prerequisites are available on the system.

**Comment by markgrossnickle** [comment]
@morosev You are right. It was my environment. I am not sure which bit I had wrong but to anyone else stumbling upon this thread I uninstalled all other variations of python on my machine and installed the 2.7.15 variant and made sure it was top on the path list. I also was missing one of the two Windows SDKs mentioned though I think it was an issue with python. 

Thanks for pointing me in the right direction

**Comment by markgrossnickle** [comment]
@morosev Sorry to bug again. Are you able to build to x64?  I can do x86 but x64 fails similarly to the error I reported above: https://github.com/Microsoft/MixedRealityToolkit-Unity/commit/000d2fad897728d0f39b9d06522efc85b545b7c8#r33080509


[1/1] LINK(DLL) webrtc_unity_plugin.dll webrtc_unity_plugin.dll.lib webrtc_unity_plugin.dll.pdb
FAILED: webrtc_unity_plugin.dll webrtc_unity_plugin.dll.lib webrtc_unity_plugin.dll.pdb
C:/Python27/python.exe ../../build/toolchain/win/tool_wrapper.py link-wrapper environment.x64 False link.exe /nologo /IMPLIB:./webrtc_unity_plugin.dll.lib /DLL /OUT:./webrtc_unity_plugin.dll /PDB:./webrtc_unity_plugin.dll.pdb @./webrtc_unity_plugin.dll.rsp
win_clang_x64\obj\third_party\libyuv\libyuv_internal.lib : fatal error LNK1107: invalid or corrupt file: cannot read at 0x688A

I'm curious if it is another environment issue or if you experience the same thing.

**Comment by markgrossnickle** [comment]
@morosev Are you able to build x64? ^

**Comment by markgrossnickle** [comment]
Nevermind. I went back and reviewed the webrtc native code development instructions again and noticed I had the Python path above the depot_tools path.  I still can't get x64 to work with your instructions above but I can get it to work with Ben's:
https://github.com/Microsoft/MixedRealityToolkit-Unity/commit/000d2fad897728d0f39b9d06522efc85b545b7c8#commitcomment-33080509

Thanks

**Comment by morosev** [comment]
@markgrossnickle  Sorry for late reply. Good that you succeeded in making it work. This commit might solve the issue for win32/x64 build:
https://github.com/webrtc-uwp/webrtc-scripts/commit/27977a4d88959f9a6a3ca59fcbfeded0d2bfcdb3
Win32 x86/x64 build has been maintained on `Robin/m71-dot-net-branch` which is not merged yet to `cse/m71-ks`.
