### ISSUE TITLE
Windows build depends on Python 2.x, does not work with Python 3.x

### ISSUE THREAD

**Issue by djee-ms** [webrtc-uwp/webrtc-uwp-sdk#136]
Scripts in `webrtc-uwp-sdk\webrtc\xplatform\webrtc\tools\clang\scripts\`, in particular `update.py` and `utility.py`, are using 2.x constructs and fail if python.exe points to a 3.x version on the build machine. This should be at least documented on the `README.md` (tested on branch `cse/m71-ks`).

**Comment by jamescadd** [comment]
Agreed - the latest documentation is [here](https://github.com/webrtc-uwp/webrtc-uwp-sdk/tree/releases/m71).  Checking on whether everything in `cse/m71-ks` is in `releases/m71` but you may not need that branch at all.

**Comment by djee-ms** [comment]
Ok thanks. @bengreenier pointed me to it, but if everything is merged to `release/m71` then that's even better. I will give it a try next week.
