### ISSUE TITLE
Current status of screen_capture ?

### ISSUE THREAD

**Issue by datHSOsnabrueck** [webrtc-uwp/webrtc-uwp-sdk#140]
According to #47  and #54 I would like to know if there are any news or work around about screen_capture at this time ?

Would be nice to stream desktop screen in hololens instead of webcam view in the PeerCC Sample

Thanks

**Comment by jamescadd** [comment]
@morosev Do you think it's more feasible to enable screen capture now that we have the DX video surface source PR?

**Comment by morosev** [comment]
@jamescadd @datHSOsnabrueck 
I made a little investigation about desktop_capture module support in WebRTC library. It looks like the screen capture feature is not supported for any available platform when WebRTC library is used as a stand alone library. On the other hand, screen capture module is used from Chromium code to support desktop sharing in the browser.
We can probably make use of DX video surface source PR (https://github.com/webrtc-uwp/webrtc/pull/9) to support DX screenshare approach on HoloLens. But other components are needed as well which will be used to wrap the DesktopCapture instance and to make it available in WebRTC standalone engine. A component like this one: https://chromium.googlesource.com/chromium/src.git/+/refs/heads/master/content/browser/media/capture/desktop_capture_device.h
