### ISSUE TITLE
Video frame reading through WinRT prohibitively slow

### ISSUE THREAD

**Issue by djee-ms** [webrtc-uwp/webrtc-uwp-sdk#144]
Hi-

I tried to use the WinRT wrapper provided under `Org.WebRtc` instead of directly P/Invoke-ing the C++ API, and I am having issues reading video frames. I have a working solution, but it is terribly slow because of the WinRT projection. So I am wondering if there's an alternative, or if the API needs to be changed.

My UWP app (C#) registers an `OnVideoFrame` handler to retrieve the local video frame:
```cs
var localVideoTrack = MediaStreamTrack.CreateVideoTrack("local_video_track", localVideoSource);
MediaStreamTrack.Cast(localVideoTrack).OnVideoFrame += OnLocalVideoFrame;
```

The handler receives an `IVideoFrameBufferEvent` which contains an `IVideoFrameBuffer` from which one can get the I420 YUV data in the form of an `IVideoFramePlanarYuvBuffer` interface.
Each Y, U, V plane is exposed via an `IVideoData`.

`Org.WebRtc.VideoData` exposes `Data8bit()` which returns an `IVectorView<uint8_t>` for the given video plane. This projects [according to .NET rules](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.collections.ivectorview_t_) into an `IReadOnlyList<byte>`. This seems to be already not great, as I don't see a way to get a `byte[]` array without copying byte by byte. Also I am not sure that `IVectorView` guarantees contiguous memory in the first place, which the API probably should.

But where it gets very strange is that looking at the generated wrapper code in `webrtc\xplatform\webrtc\sdk\windows\wrapper\generated\org_webRtc_VideoData.h` I see that the implementation uses `std::shared_ptr< std::list< std::uint8_t > >`, that is each single pixel looks to be allocated separately into a linked list, and that for each of the Y, U, V planes. In my tests this means that profiling shows the function reading back the video frame takes over 70% of the CPU time just to render the local video stream, without even transmitting nor receiving anything from the remote peer. Most of the time is spent in the loop reading the data pixel by pixel, which makes a single call across WinRT per pixel per plane.

I use something akin to:
```cs
private byte[] CopyToArray(IReadOnlyList<byte> y, IReadOnlyList<byte> u, IReadOnlyList<byte> v)
{
    int ny = y.Count;
    int nu = u.Count;
    int nv = v.Count;
    int num = ny + nu + nv;
    var ret = new byte[num];
    for (int i = 0; i < ny; ++i)
    {
        ret[i] = y[i]; // this is very hot in the profiler
    }
    for (int i = 0; i < nu; ++i)
    {
        ret[ny + i] = y[i]; // same
    }
    for (int i = 0; i < nv; ++i)
    {
        ret[ny + nu + i] = y[i]; // same
    }
    return ret;
}
```

I am wondering if there is another way with the current API, or if I am doing something wrong? As far as I know grabbing the video frame like this is the only way to render the local and remote video streams (local because WebRTC takes exclusive access to the camera, remote because it comes from the network, and in both cases there's no facility in WebRTC which abstracts the platform's video rendering).

Any idea?
Thanks

**Comment by phongcao** [comment]
@djee-ms I believe this issue has been fixed in [m71-dot-net](https://github.com/webrtc-uwp/webrtc-uwp-sdk/commits/Robin/m71-dot-net) branch. You can use `GetData8bit` method to retrieve byte[] array without affecting performance.

**Comment by robin-raymond** [comment]
Yes, thanks @phongcao - it has been fixed and merged to releases/m71 .

**Comment by djee-ms** [comment]
Ok thanks I moved to `releases/m71` and I am back to a few percent CPU use only by using `GetData8Bit`.
So I am closing this issue.
