### ISSUE TITLE
WebRtc.UWP.Native.Builder build fail (branch m71)

### ISSUE THREAD

**Issue by ifullstacker** [webrtc-uwp/webrtc-uwp-sdk#149]
### **the error is:**

1>------  WebRtc.UWP.Native.Builder               Debug x64 ------
1>[DEBUG            ] - [System         ] - __updateDepotToolsPath         - Removing depot tools path 'D:\webrtc-uwp-sdk-m71\webrtc\xplatform\depot_tools' from the PATH. (system.py:421)
1>[INFO             ] - [System         ] - __updateDepotToolsPath         - Adding depot tools path 'D:\webrtc-uwp-sdk-m71\scripts\..\.\webrtc\xplatform\depot_tools' to the PATH. (system.py:424)
1>[33m
1>===================================== Script execution STARTED =====================================
1>[0m
1>Traceback (most recent call last):
1>  File "D:\webrtc-uwp-sdk-m71\webrtc\windows\projects\msvc\WebRtc.UWP.Native.Builder\..\..\..\..\..\scripts\run.py", line 350, in <module>
1>    main()
1>  File "D:\webrtc-uwp-sdk-m71\webrtc\windows\projects\msvc\WebRtc.UWP.Native.Builder\..\..\..\..\..\scripts\run.py", line 271, in main
1>    System.setUp()
1>  File "D:\webrtc-uwp-sdk-m71\scripts\system.py", line 89, in setUp
1>    cls.__determineVisualStudioPath()
1>  File "D:\webrtc-uwp-sdk-m71\scripts\system.py", line 478, in __determineVisualStudioPath
1>    Settings.msvcToolsVersion = next(os.walk(Settings.msvcToolsPath))[1][0]
1>StopIteration
1>D:\webrtc-uwp-sdk-m71\webrtc\windows\projects\msvc\WebRtc.UWP.Native.Builder\WebRtc.UWP.Native.Builder.vcxproj(318,5): error MSB3073: 命令“python D:\webrtc-uwp-sdk-m71\webrtc\windows\projects\msvc\WebRtc.UWP.Native.Builder\..\..\..\..\..\scripts\run.py -a clean -t webrtc -p winuwp --cpus x64 -c Debug --noColor” exited，error code 1。

**Comment by ifullstacker** [comment]
i find the the reason，you must install the vs2017 in default folder.
if not default, you need modify scripts/system.py , line 454, add the code below:
` Settings.msvsPath = 'your vs installed url'`

**Comment by ispysoftware** [comment]
To avoid messing with the existing scripts, create /scripts/userdef.py containing (for example):

msvsPath = 'D:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional'
