### ISSUE TITLE
libyuv builds with clang on releases/m71 when compiling WebRtc.Win32 for x64

### ISSUE THREAD

**Issue by djee-ms** [webrtc-uwp/webrtc-uwp-sdk#157]
See `webrtc-uwp-sdk\webrtc\xplatform\libyuv\BUILD.gn`:
```
if (is_win && target_cpu == "x64") {
    if (current_os == "winuwp") {        // <----------
      public_deps = [
        ":libyuv_internal",
      ]
    } else {
      # Compile with clang in order to get inline assembly
      public_deps = [
        ":libyuv_internal(//build/toolchain/win:win_clang_x64)",
      ]
    }
  }
```
When building `WebRtc.Win32.sln` in x64, this skips the first branch and picks the clang x64 toolchain. This results in a `libyuv_internal.lib` which cannot be linked by MSVC. This happens on a freshly cloned repository.

```
1>FAILED: win_clang_x64/obj/third_party/libyuv/libyuv_internal.lib
1>ninja -t msvc -e environment.x64 -- ../../third_party/llvm-build/Release+Asserts/bin/lld-link.exe /lib /llvmlibthin /nologo /ignore:4221 /OUT:win_clang_x64/obj/third_party/libyuv/libyuv_internal.lib @win_clang_x64/obj/third_party/libyuv/libyuv_internal.lib.rsp
1>ninja: fatal: CreateProcess: %1 is not a valid Win32 application.
```

Changing `if (current_os == "winuwp")` to `if (is_win)` fixes the build.

**Comment by djee-ms** [comment]
I saw a couple of commits related to `libyuv` and assembly, _e.g._ https://github.com/webrtc-uwp/libyuv/commits/f1e39df1a6ffc965a1743622632cc79e9f927286
Is this fixed somehow @robin-raymond? Some commit says that `libyuv` doesn't use assembly anymore, why is that?

**Comment by SergioOpenPeer** [comment]
@djee-ms pushed to m71 and m75

**Comment by djee-ms** [comment]
Ok thanks @SergioOpenPeer!
