### ISSUE TITLE
Sent video (on localhost) still in 640x480 resolution, despite setting SetPreferredVideoCaptureFormat() to higher resolution

### ISSUE THREAD

**Issue by DanAndersen** [webrtc-uwp/webrtc-uwp-sdk#16]
Hi,
I am attempting to use the WebRTC UWP library to stream HD video from a C# UWP app to a browser application. Both the sender and receiver are on the same machine (localhost). On the sender side, I call WebRTC.SetPreferredVideoCaptureFormat(1920,1080,30). I've confirmed that this is one of the supported capabilities of the current device.

When I receive the video on the receiving side, the video itself is at the right resolution (1920x1080, as tested by looking at the "videoWidth" and "videoHeight" properties of the `<video>` element, but it appears as if it has been merely upscaled rather than actually encoding higher-resolution video. It does not look like it is just a side-effect of the video encoding process itself -- the output video I'm getting (even on localhost) looks the same (except for aspect ratio) regardless of whether I set the preferred video capture format to 640x480 or 1920x1080.

I noticed that there is a possible typo in webrtc-windows:
https://github.com/webrtc-uwp/webrtc-windows/blob/14e7b71ce361e877d3ec43e9df0ca85802bcebb6/org/webrtc/wrapper/Media.cc#L518

I think that 
```
constraints.SetMandatoryMaxFrameRate(cricket::VideoFormat::IntervalToFps(globals::gPreferredVideoCaptureFormat.height));
```
should probably be 
```
constraints.SetMandatoryMaxFrameRate(cricket::VideoFormat::IntervalToFps(globals::gPreferredVideoCaptureFormat.interval));
```

I don't know enough about the inner workings of WebRTC to know if this is the root cause. Could it be that these constraints are forcing the encoder to try to hit an incorrectly high FPS, and thus reducing the resolution to compensate?

**Comment by jamescadd** [comment]
@robin-raymond Do you know who could help triage this?

**Comment by DanAndersen** [comment]
Hi,
I was curious to see if anyone had looked into this issue yet. Thank you!

**Comment by morosev** [comment]
Yes, that might be a problem. The FPS typo is fixed and will be merged to the master branch.
On the other hand it is just a constraint and FPS couldn't be higher than camera device actually supports. We can be sure that FPS doesn't go above 60.
It is usual situation that even if the video is captured at 1920x1080@30, the transmitted picture size or frame rate could be less than specified values. Video quality automatically adjusts to network conditions and CPU load.
You can track the encoded video size in webrtc output log. We can give you instruction how to do that.
