### ISSUE TITLE
Unable to integrated Callstats.io

### ISSUE THREAD

**Issue by datHSOsnabrueck** [webrtc-uwp/webrtc-uwp-sdk#160]
@jamescadd 
I am playing with some feedback about the video call via WebRTC and according to the instruction from [here](https://blogs.windows.com/buildingapps/2019/01/09/webrtc-uwp-callstats-io-integration-sample-released/#j2XFDjed8TOyqdFu.97), I should be able to use the callstats api after succesfully integrate callstats.io. However the step are little confusing and I have some problems. 

> 1) Create a callstats.io account.

Go to https://dashboard.callstats.io/register and create the Organization
Navigate to the apps tab to create an app and enter the SDK as other “UWP”
From the left side panel, click on “App Settings” and navigate to the “Security” tab
Click on “New credentials” and choose a label for the key
Select the key type as “ECDSA” and enter the public key (**confused here, where do i have the public key... from step 2 ?**)
Under the key details, click on “view” for the credential
2) To authenticate with callstats.,io it is necessary to generate cryptographic keys and upload the public key to the service. Follow the instructions in the readme.md file here. After completing this step, you should have a Config class and .p12 certificate in your project. That’s all you need to authenticate to the callstats.io REST API.

I think that firstly I have to setup the integration first [here](https://github.com/webrtc-uwp/PeerCC). However the generated pubkey seem not to be the write format therefore I cant create new credenticals (Error in callstats.io: Key format is invalid. The app secret creation failed because the data was invalid.)

If the integration process success and I can append the public key to the config.cs script correctly. Do I need to change the config.cs file in both PeerConnectionClientCore and PeerConnectionClientUnityCore and build ?

Step3) Referencing nuget package in project.
Do I have to add the nuget package in PeerConnectionClient.WebRtc(Universal Windows) project for the windows client or also for the unity(hololens) client?
Step 4 til 7 might not be nessesary anymore because the implementation are already in the conductor.cs script. (eg. await PeerConnectionStateChange.StatsOnIceGatheringStateChange(peerConnection);)

**Comment by ivanab** [comment]
@datHSOsnabrueck
How your generated public key looks like? 

You should have this content in your copied key: 

-----BEGIN PUBLIC KEY----- 
................................................................ 
......................................................== 
-----END PUBLIC KEY----- 

Dots represent random characters from your generated public key.   

After that you need to create ecc-key.p12 certificate (remove existing one and add yours), follow instructions here: 
https://github.com/webrtc-uwp/PeerCC 

And you just need to enter values into PeerCC/Client/config.txt file.

**Comment by datHSOsnabrueck** [comment]
> @datHSOsnabrueck
> How your generated public key looks like?
> 
> You should have this content in your copied key:
> 
> -----BEGIN PUBLIC KEY-----
> ................................................................
> ......................................................==
> -----END PUBLIC KEY-----
> 
> Dots represent random characters from your generated public key.
> 
> After that you need to create ecc-key.p12 certificate (remove existing one and add yours), follow instructions here:
> https://github.com/webrtc-uwp/PeerCC
> 
> And you just need to enter values into PeerCC/Client/config.txt file.

yeah exactly. I generated  pubkey.pem file and I did copy the key include == 
But the error happen from the description above

**Comment by ivanab** [comment]
This should be included also:
-----BEGIN PUBLIC KEY-----
-----END PUBLIC KEY-----

**Comment by datHSOsnabrueck** [comment]
> This should be included also:
> -----BEGIN PUBLIC KEY-----
> -----END PUBLIC KEY-----

thanks for the quick response @ivanab . I successfully add new credentical. However I stuck at 

> openssl req -new -x509 -days 1826 -key privatekey.pem -out certificate.crt
Following error log
> Can't open Z:/extlib/_openssl11__/ssl/openssl.cnf for reading, No such file or directory
12228:error:02001003:system library:fopen:No such process:crypto/bio/bss_file.c:74:fopen('Z:/extlib/_openssl11__/ssl/openssl.cnf','r')
12228:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:81:
unable to find 'distinguished_name' in config
problems making Certificate Request
12228:error:0E06D06A:configuration file routines:NCONF_get_string:no conf or environment variable:crypto/conf/conf_lib.c:272:


I dont have Z Driver btw.

**Comment by ivanab** [comment]
Install version Win64 OpenSSL v1.1.1 from: https://slproweb.com/products/Win32OpenSSL.html

Type in Command Prompt:
echo %OPENSSL_CONF%

Path should be:
C:\OpenSSL-Win64\bin\openssl.cfg

If not:
set OPENSSL_CONF=c:\OpenSSL-Win64\bin\openssl.cfg

**Comment by datHSOsnabrueck** [comment]
> Install version Win64 OpenSSL v1.1.1 from: https://slproweb.com/products/Win32OpenSSL.html
> 
> Type in Command Prompt:
> echo %OPENSSL_CONF%
> 
> Path should be:
> C:\OpenSSL-Win64\bin\openssl.cfg
> 
> If not:
> set OPENSSL_CONF=c:\OpenSSL-Win64\bin\openssl.cfg


Sorry but despite the fact, that openssl.cfg is in C:\OpenSSL-Win64\bin\openssl.cfg. I still have the same issue. In the bin folder i cant find openssl.cfg file anyway but it still showing the location in command prompt.

In the system path I got
C:\Strawberry\c\bin
C:\OpenSSL-Win64\bin

**Comment by ivanab** [comment]
You don't need to change Config.cs, just PeerCC/Client/config.txt it will read from that file.

Steps 4-7 are not necessary. You should see responses from the API in VS output console.

Callstats integration is not used in HoloLens project.

**Comment by jamescadd** [comment]
Hello @datHSOsnabrueck - I'm glad to see you're trying this out as we haven't had a ton of feedback on the CallStats integration.  I'd be interested to know if you're already using (or plan to use) CallStats, and if so to understand the use case.  If you prefer email you can reach me at the Microsoft domain, my alias is jacadd.

Thanks,
James

**Comment by datHSOsnabrueck** [comment]
> You don't need to change Config.cs, just PeerCC/Client/config.txt it will read from that file.
> 
> Steps 4-7 are not necessary. You should see responses from the API in VS output console.
> 
> Callstats integration is not used in HoloLens project.

Well, today I make the test after finished setup the c12 certificate but unfortunately I can't see any data in callstats.io dashboard or VS output.
I did enter the key in the config.txt file and run the solution again, but I can't see any output information about callstats.

I skip the steps 3 til 7 as you mention.

From the VS output I can barely see any new information

> Invalid parameter passed to C runtime function.
Invalid parameter passed to C runtime function.
Invalid parameter passed to C runtime function.
Exception thrown: 'System.TimeoutException' in PeerConnectionClientCore.dll
Invalid parameter passed to C runtime function.
Invalid parameter passed to C runtime function.
Invalid parameter passed to C runtime function.
Invalid parameter passed to C runtime function.

**Comment by datHSOsnabrueck** [comment]
> Hello @datHSOsnabrueck - I'm glad to see you're trying this out as we haven't had a ton of feedback on the CallStats integration. I'd be interested to know if you're already using (or plan to use) CallStats, and if so to understand the use case. If you prefer email you can reach me at the Microsoft domain, my alias is jacadd.
> 
> Thanks,
> James

Hello and thanks for the answer. I do not know if I can contribute something :) I'm just a student trying to figure out the quality of connecting and using this webrtc uwp project in the context of network connectivity / bandwidth. I'd like to collect this information in callstats.io to evaluate the video call I made using this project. So first I have to success setup callstats.io :D
