### ISSUE TITLE
Add option to build with c++17 on Win32

### ISSUE THREAD

**Issue by djee-ms** [webrtc-uwp/webrtc-uwp-sdk#163]
I'm opening a new issue separate from #150 for the specific problem with `absl::optional`.

Currently `absl::optional` and `std::optional` are incompatible, and [Abseil maintainers have no plan to change that](https://github.com/abseil/abseil-cpp/issues/264).

On UWP, because C++/WinRT requires `/std:c++17`, this is forced in `webrtc\xplatform\chromium\build\config\win\BUILD.gn`:
```
cflags_cc += [
  "/std:c++17",
  "/Zc:__cplusplus",
]
```

However on Win32 this is not active by default. The problem is that if an application compiled with `/std:c++17` tries to link against `webrtc.lib` (compiled without), the mismatching implementations will result in link errors, as one is using `absl::optional` and the other `std::optional`.

I am not sure what is the best approach here, but it seems the least invasive one is to add an option to `run.py` to specify whether or not to force `/std:c++17` for `webrtc.lib`. I made the change locally and it seems to work; I can provide PRs (3 submodules) if there is an agreement that this is a good approach. But I need to find a solution as this is blocking me both from setting up a build pipeline and from releasing the code since I cannot ask users to locally patch their git repository to work around that issue.

In details my change is:
- Add an `std_cpp17` option to `webrtc\xplatform\chromium\build\config\win\BUILD.gn`
- Force that boolean if on UWP
- From "compiler" in that file, add `//build/config/win:cpp17` if the option is set
- Add a `--cpp17` option to the Python build script
- Add a line in `webrtc/windows/templates/gns/args.gn` to enable that GN flag via the `run.py` option

I have no solution for the MSVC project (native builder), but at least that way by falling back on the build script one can compile `webrtc.lib` and link it with a C++17 application.

**Comment by robin-raymond** [comment]
Hmm... right. That's annoying! The trouble is that win32 is set to build in the default google way. So we'll need an option to say "build win32 but it's a specialized win32 version so build with modern C++ so that code using it can build with modern C++ too". You mentioned changes - do you have a PR regarding this change?

**Comment by djee-ms** [comment]
I didn't open PRs yet. As far as I understand since this touches 3 different submodules I have to create 3 clones and open a PR in each of them, so I'd rather wait we agree in principle that this is a valid approach.
See patches:
[scripts.patch.txt](https://github.com/webrtc-uwp/webrtc-uwp-sdk/files/3291168/scripts.patch.txt)
[webrtc_windows.patch.txt](https://github.com/webrtc-uwp/webrtc-uwp-sdk/files/3291171/webrtc_windows.patch.txt)
[webrtc_xplatform_chromium_build.patch.txt](https://github.com/webrtc-uwp/webrtc-uwp-sdk/files/3291173/webrtc_xplatform_chromium_build.patch.txt)

**Comment by djee-ms** [comment]
Note that Google can be considered doing something wrong here, or we can consider that WebRTC doesn't support C++17 (and I think that's the case officially) and that the C++/WinRT wrappers forcing C++17 are incompatible with WebRTC. So there's no good solution I'm afraid.

**Comment by robin-raymond** [comment]
I think we need to "fix" support. Ideally google would support C++17 out of the box but I can also understand why they might not want to force that support right now. So I think it needs to be an optional compilation thing. We can try to submit any "fixes" required for google back to google but I have no idea if they would be interesting in this kind of fix. We can sandbox try it in our fork though first and then submit proper fixes to google after perhaps.

**Comment by djee-ms** [comment]
Add GN support to chromium/build : https://github.com/webrtc-uwp/chromium-build/pull/8
Populate GN argument in `args.gn` template : https://github.com/webrtc-uwp/webrtc-windows/pull/52
Add `run.py` support : https://github.com/webrtc-uwp/webrtc-scripts/pull/38

**Comment by robin-raymond** [comment]
@djee-ms Looks great - thank you. In the middle of a few fixes but once I get done then I can look at merging these.

**Comment by djee-ms** [comment]
Ping - any news on that @robin-raymond ? This is a blocking issue for us, we can't release publicly without that as the Win32 build won't even link.

**Comment by robin-raymond** [comment]
@djee-ms I haven't forgotten. It's my next task.

**Comment by robin-raymond** [comment]
Ok going to work on this tomorrow.

**Comment by robin-raymond** [comment]
Resolved + merged releases m71/m75.

**Comment by djee-ms** [comment]
Thanks Robin!
