### ISSUE TITLE
[Question] What's the current status of this project?

### ISSUE THREAD

**Issue by Alexees** [webrtc-uwp/webrtc-uwp-sdk#164]
I was wondering if there's a concise list of the features covered by the current webrtc "out of the box" implementation:  
- Can I connect to clients based on the official webrtc source (basically clients on other platforms)?
- How much of Signaling, STUN and TURN are available?
- Is multi-peer connection supported?
- Are all three channels, Video, Audio and Data implemented?

Thanks

**Comment by jamescadd** [comment]
Hello - the answer to all of the above is "yes."  This is a complete port of the webrtc.org source and includes all features and codes included in the same milestone release of Chrome.  If you have any specific questions please let me know.

Thanks,
James
