### ISSUE TITLE
hresult_wrong_thread exception calling RTCPeerConnection.createOffer() from JS

### ISSUE THREAD

**Issue by timothy003** [webrtc-uwp/webrtc-uwp-sdk#169]
Calling `RTCPeerConnection.createOffer()` from a JavaScript app throws a `winrt::hresult_wrong_thread` exception and causes an assertion failure.

Code:

```javascript
const { WebRtc } = Org;
const config = new WebRtc.RTCConfiguration();
config.factory = new WebRtc.WebRtcFactory(new WebRtc.WebRtcFactoryConfiguration());
const pc = new WebRtc.RTCPeerConnection(config);
pc.createOffer(new WebRtc.RTCOfferOptions()).then(console.log, console.error);
```

Output:

```
(mediasession.cc:349): Duplicate id found. Reassigning from 102 to 127
(mediasession.cc:349): Duplicate id found. Reassigning from 104 to 125
(mediasession.cc:349): Duplicate id found. Reassigning from 103 to 124
Exception thrown at 0x00007FFFF8369129 (KernelBase.dll) in WWAHost.exe: WinRT originate error - 0x80040155 : 'Failed to find proxy registration for IID: {7239777F-99E2-5040-A0CD-D1B400618D15}.'.
Exception thrown at 0x00007FFFF8369129 (KernelBase.dll) in WWAHost.exe: WinRT originate error - 0x8001010E : 'The application called an interface that was marshalled for a different thread.'.
Exception thrown at 0x00007FFFF8369129 in WWAHost.exe: Microsoft C++ exception: winrt::hresult_wrong_thread at memory location 0x0000008784FFEA18.
Debug Assertion Failed!

Program: ...ileDiscord\MobileDiscordDev\bin\x64\Debug\AppX\Org.WebRtc.dll
File: c:\program files (x86)\windows kits\10\include\10.0.17763.0\cppwinrt\winrt\base.h
Line: 11134

Expression: m_status == AsyncStatus::Started || m_status == AsyncStatus::Canceled

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)
WWAHost.exe has triggered a breakpoint.
```

Stack trace:

```
>	Org.WebRtc.dll!winrt::impl::promise_base<std::experimental::coroutine_traits<winrt::Windows::Foundation::IAsyncOperation<winrt::Org::WebRtc::IRTCSessionDescription>,std::shared_ptr<zsLib::PromiseWithHolderPtr<std::shared_ptr<wrapper::org::webRtc::RTCSessionDescription>,std::shared_ptr<zsLib::Any>,std::shared_ptr<zsLib::Any> > > >::promise_type,winrt::Windows::Foundation::IAsyncOperation<winrt::Org::WebRtc::IRTCSessionDescription>,winrt::Windows::Foundation::AsyncOperationCompletedHandler<winrt::Org::WebRtc::IRTCSessionDescription>,void>::unhandled_exception() Line 11134	C++
 	Org.WebRtc.dll!`Internal::Helper::ToCppWinrt_PromiseWith_ToCppWinrt_Org_WebRtc_RTCSessionDescription_ToCppWinrt_Void$_ResumeCoro$2'::`1'::catch$11() Line 1799	C++
 	[External Code]	
 	Org.WebRtc.dll!Internal::Helper::ToCppWinrt_PromiseWith_ToCppWinrt_Org_WebRtc_RTCSessionDescription_ToCppWinrt_Void$_ResumeCoro$2() Line 1784	C++
 	[External Code]	
```

**Comment by jamescadd** [comment]
Hello - try calling it from the UI thread, let me know if that doesn't work. I'd be interested to hear more about the JS use case you have for the library as well.

**Comment by timothy003** [comment]
Do you mean calling it off the UI thread? Like, using a C++ WinRT component?

This is for a UWP port of Discord, a web-based voice and text chat app. It's currently using this library to add RTC support on Windows 10 Mobile, but I'm having trouble updating to the M71 release. Is JS not supported anymore?

**Comment by jamescadd** [comment]
We haven't had anyone use JS with m71 yet but it should work. Search the peerconnection sample for Dispatcher for an example of calling a method from the UI thread. No need for another component.

**Comment by timothy003** [comment]
Sorry, I'm confused. From my understanding, JS already runs on the UI thread. The PeerCC sample uses `CoreDispatcher`, but that API is WebHostHidden. And even after calling `WebRtcLib.setup()` (with no arguments), the result is still the same.

**Comment by timothy003** [comment]
I forgot to mention that this is a hosted web app, not JS running in a WebView.

**Comment by jamescadd** [comment]
Right, I forgot that the CoreDispatcher is hidden there.  Is there any chance you can share a repro sample?  Feel free to email my microsoft.com address, alias jacadd, if this should be kept private.

**Comment by timothy003** [comment]
I tried making a blank JS app and adding the WebRtc NuGet package, but it can't find the library for some reason.

```
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Org.WebRtc". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
```

**Comment by jamescadd** [comment]
Just to double check, this is in VS2017 correct?  So steps are to create a new HWA, add reference to the NuGet package, and run?

**Comment by timothy003** [comment]
I used the "Blank App (Universal Windows)" JavaScript template, since that would not require a web server to run. And FWIW, the M54 NuGet package didn't work for me in VS2015, either; I had to build the library myself.

**Comment by jamescadd** [comment]
Ok I see that I can repro this as well.  We'll have to take a look.  Given that this project type is no longer supported in VS2019 (see note at the bottom of this page: https://docs.microsoft.com/en-us/visualstudio/javascript/javascript-in-vs-2019?view=vs-2019) this has been low priority currently - I'll keep the issue open in case others hit the same.

**Comment by timothy003** [comment]
Thanks for your support. I appreciate the transparency.

Video calling has recently broken in my app due to a crash in the H.264 PPS parser, which is why I'm trying to update WebRTC. I expected M71 to require some tweaks for my app, but the UWP wrapper appears to be entirely rewritten, so it will take me some time to get familiar with it. The new code looks a lot better, though, and I'm hoping there will be less crashes and deadlocks. I'll continue to work on this and report my findings here.

There weren't instructions on how to use the SDK in a project, so after trial and error, this is what I came up with:

1. Recursively clone webrtc-uwp-sdk to `C:\`
2. Open `C:\webrtc-uwp-sdk\webrtc\windows\solutions\WebRtc.Universal.sln`
3. Wait for packages to restore
4. Close solution
5. Create new JS project
6. Add existing projects:
   - `C:\webrtc-uwp-sdk\webrtc\windows\projects\msvc\WebRtc.UWP.Native.Builder\WebRtc.UWP.Native.Builder.vcxproj`
   - `C:\webrtc-uwp-sdk\webrtc\windows\projects\msvc\Org.WebRtc.WrapperGlue.Universal\Org.WebRtc.WrapperGlue.vcxproj`
   - `C:\webrtc-uwp-sdk\webrtc\windows\projects\msvc\Org.WebRtc.Universal\Org.WebRtc.vcxproj`
7. Add project dependency from `Org.WebRtc.WrapperGlue` to `WebRtc.UWP.Native.Builder`
8. Add project reference from JS project to `Org.WebRtc`
9. Select Debug x64 configuration
10. Add Microphone and Webcam capabilities to `package.appxmanifest`
11. Add this code to `main.js`:
    ```js
    const { WebRtc } = Org;
    WebRtc.WebRtcLib.setup();
    const { Capture } = Windows.Media;
    const mediaCapture = new Capture.MediaCapture();
    const captureInitSettings = new Capture.MediaCaptureInitializationSettings();
    captureInitSettings.streamingCaptureMode = Capture.StreamingCaptureMode.audioAndVideo;
    mediaCapture.initializeAsync(captureInitSettings).then(() => {
        mediaCapture.close();
        const config = new WebRtc.RTCConfiguration();
        config.factory = new WebRtc.WebRtcFactory(new WebRtc.WebRtcFactoryConfiguration());
        const pc = new WebRtc.RTCPeerConnection(config);
        pc.createOffer(new WebRtc.RTCOfferOptions()).then(console.log, console.error);
    }, console.error);
    ```
12. Change JS project Properties > Debugging > Debugger Type to 'Native Only'
13. Hit F5

**Comment by timothy003** [comment]
I've identified two threading-related issues so far.

The first is that zsLib uses a background thread for the default message queue. Since none of the delegates have proxies or stubs to marshal events to the UI thread, event handlers fail with an `hresult_wrong_thread` exception.

The second issue is in the conversion from `zsLib::Promise` to `Windows::Foundation::IAsyncOperation` for returning the results of `CreateOffer()` and `CreateAnswer()`. zsLibEventingTool's generated promise helper returns the result on a thread pool, and the call to `AsyncOperationCompletedHandler<TResult>` fails as demonstrated in the original post, since it's a generic type and has no built in proxies or stubs.

In the function `Internal::Helper::ToCppWinrt_PromiseWith_ToCppWinrt_Org_WebRtc_RTCSessionDescription_ToCppWinrt_Void`, an event object is created with `HANDLE handle = ::CreateEventEx(NULL, NULL, 0, EVENT_ALL_ACCESS)`, and the coroutine is suspended using `co_await winrt::resume_on_signal(handle)`. It then gets resumed on the Windows thread pool and completes the operation using `co_return result`. Perhaps it would be better to make `zsLib::Promise` awaitable instead, avoiding the thread pool altogether.

**Comment by robin-raymond** [comment]
@timothy003 Normally the setup routine takes a dispatcher which allows events to get routed back to the UI thread. In this case you can't because it doesn't exist from JS.

However, there is a new dispatcher type that can work for the GUI and might work for JS assuming JS is internally using the underlying dispatcher to power JS events:
https://docs.microsoft.com/en-us/uwp/api/windows.system.dispatcherqueue

It's already available in the code but that object where you set it is webhosthidden so you can't see it from JS. However, I can do some changes to allow you to create it for the "current" thread from the non hidden object (the message queue object and not the message queue maker).

Which version are you working from? m71 or m75?

**Comment by timothy003** [comment]
I'm currently on the M71 branch. I've been using `CoreWindow.Dispatcher()` to get the dispatcher in `WebRtcLib::actual_setup()`:

```cpp
    // Setup if WinUWP CppWinRT is defined...
    auto nativeCppWinrt = UseEventQueue::toNative_winrt(queue);
    if (!nativeCppWinrt)
      if (auto window = winrt::Windows::UI::Core::CoreWindow::GetForCurrentThread())
	    nativeCppWinrt = window.Dispatcher();
    if ((nativeCppWinrt) && (!didSetupZsLib_.test_and_set())) {
      UseHelper::setup(nativeCppWinrt);
    }
```

This is the same technique used in M54 and the [WinRT docs](https://docs.microsoft.com/en-us/windows/uwp/winrt-components/raising-events-in-windows-runtime-components), and it works in all versions of Windows 10. It doesn't work if called from `WebView` content that's hosted off the UI thread, but most of the UWP APIs don't work there anyway.

**Comment by timothy003** [comment]
I've modified the promise helper to use a custom awaiter. Now the `IAsyncOperation` completes on the right thread, and I can perform negotiation and connect to a peer in JS.

This is the await adapter, which makes `zsLib::Promise` and `zsLib::PromiseWithHolderPtr` awaitable and resumes the coroutine on the thread that the promise is associated with:

```cpp
template<typename PromiseT>
struct await_adapter
{
  PromiseT& promise;

  bool await_ready() const noexcept { return promise.isSettled(); }

  void await_suspend(std::experimental::coroutine_handle<> resume)
  {
    promise.thenClosure(resume);
  }

  auto await_resume() const
  {
    if constexpr (std::is_same_v<PromiseT, Promise>) {
      if (promise.isRejected())
        throw promise.template reason<Any>();
    } else {
      if (promise.isRejected())
        throw promise.reason();
      return promise.value();
    }
  }
};

inline await_adapter<Promise> operator co_await(Promise& promise)
{
  return {promise};
}

template<typename DataTypePtr, typename ReasonTypePtr, typename UserTypePtr>
await_adapter<PromiseWithHolderPtr<DataTypePtr, ReasonTypePtr, UserTypePtr>> operator co_await(PromiseWithHolderPtr<DataTypePtr, ReasonTypePtr, UserTypePtr>& promise)
{
  return {promise};
}
```

And this is the simplified promise helper:

```cpp
Windows::Foundation::IAsyncOperation< Org::WebRtc::IRTCSessionDescription > Internal::Helper::ToCppWinrt_PromiseWith_ToCppWinrt_Org_WebRtc_RTCSessionDescription_ToCppWinrt_Void(shared_ptr< PromiseWithHolderPtr< wrapper::org::webRtc::RTCSessionDescriptionPtr > > promise)
try {
  if (!promise) co_return Org::WebRtc::RTCSessionDescription {nullptr};

  auto value = co_await *promise;
  if (value) {
    auto result = (::Internal::Helper::ToCppWinrt_Org_WebRtc_RTCSessionDescription(value));
    co_return result;
  }
  co_return Org::WebRtc::RTCSessionDescription {nullptr};
} catch (AnyPtr&) {
  PromisePtr promiseBase = promise;
  {
    auto reasonHolder = promiseBase->reason< ::zsLib::AnyHolder< wrapper::org::webRtc::RTCErrorPtr > >();
    if (reasonHolder) {
      ::Internal::Helper::Throwers::singleton().customThrow(reasonHolder->value_);
    }
  }

  throw hresult_no_interface();
}
```

**Comment by robin-raymond** [comment]
@timothy003 I'm looking into this issue now. For JS, do you know if there is a [https://docs.microsoft.com/en-us/uwp/api/windows.system.dispatcherqueue](https://docs.microsoft.com/en-us/uwp/api/windows.system.dispatcherqueue) for the GUI JS thread? I can add code internally that calling [https://docs.microsoft.com/en-us/uwp/api/windows.system.dispatcherqueue.getforcurrentthread#Windows_System_DispatcherQueue_GetForCurrentThread](https://docs.microsoft.com/en-us/uwp/api/windows.system.dispatcherqueue.getforcurrentthread#Windows_System_DispatcherQueue_GetForCurrentThread) even if you can't call it from JS. I think making promises awaitable is a good idea.

**Comment by robin-raymond** [comment]
I will make `EventQueue.getDefaultForUi()` check for a `CoreDispatcher` (from current thread window) and a `DisatpcherQueue` (from current thread).

**Comment by robin-raymond** [comment]
@timothy003 I made the sdk able get get the "current" GUI thread as you have done automatically. You just need to call EventQueue.getDefaultForUi() on the UI thread and pass that result into the setup. As for the promise, this is a great idea. Did you hack the generated output manually, or did you add this into the wrapper impl? I'd like to be able to incorporate this code if you are willing.

**Comment by timothy003** [comment]
I didn't want to rebuild everything, so I initially hacked the generated output, which is why I put the `await_ready`, `await_suspend`, and `await_resume` functions in a separate struct and overloaded `operator co_await`. Now that I know it works, I've added the await members to `zsLib::Promise` & friends directly and modified zsLib-eventing to output the same code. Personally, I think modifying `zsLib::Promise` intrusively is simpler, but it can be done either way.

There are still a few things that need to be reviewed.

I can't call `background()` after `thenClosure()`. This is because the coroutine could potentially be resumed concurrently on another thread, destructing the coroutine and promise before `await_suspend()` returns.

I'm not sure what `await_resume()` should return for the base `Promise`. It stores a value, but it appears to be unused, so I made it return `void` for now.

Likewise, `await_resume()` throws an exception on rejection, but the promise doesn't store an `exception_ptr`, so I'm not sure what to throw here. The current code simply throws `reason()` or `mReason`, but `reason()` actually returns `nullptr` for `PromiseWithHolderPtr<T>`, since `AnyHolder<RTCErrorPtr>` can't be converted to `AnyHolder<AnyPtr>`.

Thanks for adding a way to get the UI thread. It looks like you're missing a runtime API check for `DispatcherQueue`, but I haven't tested it yet.

**Comment by robin-raymond** [comment]
@timothy003 To be clear on this patch (which I am reviewing) -- does it cause a bug to be resolved, or is it a simplification of the code since promises now become directly awaitable? If it fixes a bug I'd like to ensure that bug is truly gone.

**Comment by timothy003** [comment]
The patch should resolve the bug with calling `createOffer()` and `createAnswer()` from JS, assuming `EventQueue.getDefaultForUi()` works correctly. I haven't tested it yet. Are you able to verify the fix on your end?

**Comment by robin-raymond** [comment]
I tested your JS sample code above with the queue fixes I've made but without the promise fixes and I didn't have an issue running the code and it worked silently as far as I can tell. I didn't see an exception. That's why I'm wondering about the awaitable promises if they fix another issue I need to verify, or if they should be considered an enhancement and I can test them from that perspective.

**Comment by timothy003** [comment]
Can you switch to script debugging and add a breakpoint to check if `createOffer()` is working? My guess is it's failing somehow. (I had to disable audio capturing and rendering to avoid the deadlock in #143.)

**Comment by robin-raymond** [comment]
@timothy003 It's working with the latest releases/m75 for me. I was able to log the SDP. Do you have an updated failing sample?

**Comment by timothy003** [comment]
I did `git clone --recursive -b releases/m71 https://github.com/webrtc-uwp/webrtc-uwp-sdk` and tried using `EventQueue.getDefaultForUi()`, but it still returns a background thread. Stepping through the debugger reveals that `MessageQueueThread::singletonUsingCurrentGUIThreadsMessageQueue()` never calls `MessageQueueThreadUsingCurrentGUIMessageQueueForCppWinrt::singleton()` because `MessageQueueThreadUsingCurrentGUIMessageQueueForCppWinrt::hasCoreDispatcher()` is `false`.

Here's the new sample code:

```js
(async function () {
    try {
        const { WebRtc } = Org;
        const configuration = new WebRtc.WebRtcLibConfiguration();
        configuration.queue = WebRtc.EventQueue.getDefaultForUi();
        WebRtc.WebRtcLib.setup(configuration);
        const { Capture } = Windows.Media;
        const mediaCapture = new Capture.MediaCapture();
        const captureInitSettings = new Capture.MediaCaptureInitializationSettings();
        captureInitSettings.streamingCaptureMode = Capture.StreamingCaptureMode.audioAndVideo;
        await mediaCapture.initializeAsync(captureInitSettings);
        mediaCapture.close();
        const config = new WebRtc.RTCConfiguration();
        config.factory = new WebRtc.WebRtcFactory(new WebRtc.WebRtcFactoryConfiguration());
        const pc = new WebRtc.RTCPeerConnection(config);
        await pc.setLocalDescription(await pc.createOffer(new WebRtc.RTCOfferOptions()));
        const pc2 = new WebRtc.RTCPeerConnection(config);
        await pc2.setRemoteDescription(pc.localDescription);
        await pc2.setLocalDescription(await pc2.createAnswer(new WebRtc.RTCAnswerOptions()));
        await pc.setRemoteDescription(pc2.localDescription);
        document.body.textContent = "success";
    } catch (e) {
        document.body.textContent = e;
        throw e;
    }
})();
```

I'll try releases/m75 and report back.

**Comment by timothy003** [comment]
I'm still seeing the `hresult_wrong_thread` exception in releases/m75. There's no more assertion failure, so the app no longer crashes, but the `IAsyncOperation` from `createOffer()` never completes.

FWIW, I installed Windows SDK 18362, but my OS build is 17763.

**Comment by robin-raymond** [comment]
@timothy003 okay, i've got it up diagnosing. I'm having difficulty getting the debugger operating in native mode for the JS (which used to work on m71) which is hampering efforts.

**Comment by timothy003** [comment]
I just realized that there's a race condition. `winrt::resume_on_signal()` doesn't suspend if the signal is already set, which could happen if `createOffer()` resolves the promise too quickly. That means the code after `co_await winrt::resume_on_signal()` can sometimes execute synchronously on the calling thread, which might explain why it works on your machine.

**Comment by robin-raymond** [comment]
I found the reason - there was a spot I forgot to fix during the last update.

**Comment by robin-raymond** [comment]
And yes - you were right, the race condition caused my version to work sometimes!

**Comment by robin-raymond** [comment]
@timothy003 Update: I hit he deadlock now after fixing the bug where the main thread could not be accessed. The issue is that the the setup creates the peercc factory (which does a blocking RPC to the signaling thread) from the GUI thread but in that process needs to create the audio capture/render which requires the main thread (for permissions), but that thread is blocked doing the RPC. The solution is to execute the setup asynchronously so the peercc factory can be a blocking call with an async result. Alternatively, I can delay create the peercc factory but then that will cascade to other functions which have to be come async as a result (since they are expecting the factory to be ready when they execute), so it's just pushing the pain point until later. I think that's the best option to get around this issue.

**Comment by timothy003** [comment]
The way I solved this issue in M54 was by moving the audio interface activation to `AudioDeviceWindowsWasapi::InitRecordingInternal()` and initializing a `Windows.Media.Capture.MediaCapture` in the JS `getUserMedia()` shim. This allowed me to emulate browser behavior by only showing a dialog to the user if `getUserMedia()` is called (in Discord, when the unmute button is pressed). Then, when the `MediaStream` is added to the `RTCPeerConnection`, webrtc calls `InitRecording()`, activating the audio interface. This happens off the UI thread, but since permission has already been granted, the call does not block.

With M71, I was planning on using the browser's native audio/video devices instead, giving me more flexibility with the JS shim and enabling web audio API functionality, which Discord uses to implement voice activity input mode. I'll need to somehow pass an EdgeHTML `MediaStreamTrack` object into WebRTC. I haven't figured out that part yet. Let me know if there's a better way!

**Comment by robin-raymond** [comment]
@timothy003 I have a bit of a mystery happening with the JS. With the coroutines being used the code can start executing form the main thread but the co-routine returns the result on a different thread. What's weird though is that I added a new async setup routine on the PeerConnectionFactory which works fine with coreturn happening on a different thread from the JS thread -- but when an attempt is made to coreturn the offer from the other thread the JS just freezes. I wonder if that's because the setup returns void but the CreateOffer returns an sdp object result. I can't find documentation on this so I'm not sure the reason.

**Comment by robin-raymond** [comment]
@timothy003 ok, I've confirmed the issue -- if you have an async method with JS and return and IAsyncOperation which has a result value then it fails but not when there's no return result that's why one async worked and not the other. So this reconfirms your earlier finding. The issue I'm having though with the coroutines, what guarantee do we have that the resume of the original thread will always happen from the thread which initiated the call? I know that the promises in zsLib can be assigned to a queue thus making sure they resolve on the correct thread but how does the coroutine that is woken up ensure that it too happens from that thread? is that a side effect of the await code written for the promise or intentional some how?

**Comment by timothy003** [comment]
The coroutine is resumed when `std::experimental::coroutine_handle<>::resume()` or `operator()()` is called.

**Comment by robin-raymond** [comment]
@timothy003 from everything I'm reading there's zero guarantee the thread will resume from the same thread it was suspended from originally -- which fits the pattern of how I understood the coroutines to work. You can force it by doing a co_await resume_on_background(). So without a method of forcing resumption on the calling thread, this glitch is in fact a problem for JS which just cannot allow any other thread than the one that called it to resume when a value is returned. Is this a JS bug/known issue/ limitation? I know JS is single threaded but you'd think if they made async APIs callable this would be handled for JS? Am I missing something?

**Comment by robin-raymond** [comment]
@timothy003 so resume() will resume on the thread where resume() is called from?

**Comment by timothy003** [comment]
Sorry, I was in a hurry and didn't have time to explain.

By implementing our own awaiter, we can control what thread the coroutine is resumed on. In `await_suspend()`, we are passed a `coroutine_handle<>`, which lets us resume execution of the coroutine. That's the key to making this all work - calling `resume()` on the `coroutine_handle<>` immediately wakes up the coroutine on the current thread.

The reason this isn't handled for JS is because there are no built in proxies and stubs to marshal calls between threads for generic types like `Windows.Foundation.AsyncOperationCompletedHandler<TResult>`. That's why your async method using `IAsyncAction` works while the one using `IAsyncOperation<TResult>` doesn't. Until you provide the type argument, it's not a complete type.

Source: [Raising Events in Windows Runtime Components - Windows UWP applications | Microsoft Docs](https://docs.microsoft.com/en-us/windows/uwp/winrt-components/raising-events-in-windows-runtime-components)

**Comment by robin-raymond** [comment]
I have merged your PRs to releases/m75. Please let me know if you need this code on releases/m71 as well. I can back port these fixes if required. I will merge the awaitable promise stuff to releases/m71 as well since they are compatible, but not the "setup" method change below unless you need it.

I have made a tiny change to the source because the setup needs to be done on a spawned thread:
````
                    config.factory = new WebRtc.WebRtcFactory(new WebRtc.WebRtcFactoryConfiguration());
                    await config.factory.setup();
````

This routine makes that happen...

The JS code sample code you have provided now works for me every time.

**Comment by timothy003** [comment]
Thanks the the update! I don't need the async factory setup, since the shimmed `RTCPeerConnection` constructor is synchronous, but I'll use releases/m75 from now on.

**Comment by robin-raymond** [comment]
Welcome. I think you might or you may hit a deadlock. The factory blocks the main thread until all of the factory components are created and the factory components spin up media and the media requires access to the main thread (which is blocked constructing the factory). Calling async setup solves that issue.

**Comment by robin-raymond** [comment]
I have back ported the fix to releases/m71 so it should work fine now, but I still have to do the await factory.setup() to make it work due to the above mentioned deadlock.

**Comment by robin-raymond** [comment]
All coded in both releases/m71 and releases/m75. JS requires the await factory.setup() or it will deadlock but otherwise it's good to do. I merged your awaitable promise into zsLib.

**Comment by timothy003** [comment]
I can confirm that `createOffer()` works in a fresh clone of releases/m75. I'll have to do some additional work to avoid the deadlock, because I can't change Discord to use `factory.setup()`, but that's a separate issue.

Thanks again for all your support!
