### ISSUE TITLE
Build failed - wrong SKD 10.0.16299.0

### ISSUE THREAD

**Issue by navrkald** [webrtc-uwp/webrtc-uwp-sdk#17]
Hi,
I have installed new Win SDK 10.0.16299.0 and build started failing. Before I build WebRTC UWP SDK correctly.

There is part of my build log:

1>  Project "c:\_S\test\annie-win-2\webrtc-uwp-sdk\webrtc\xplatform\webrtc\out\winuwp_10_x64_Debug\WebRtc.sln" (1) is building "c:\_S\test\annie-win-2\webrtc-uwp-sdk\webrtc\xplatform\webrtc\out\winuwp_10_x64_Debug\obj\third_party\boringssl\boringssl.vcxproj" (4) on node 1 (default targets).
1>  Build:
1>    call c:\_S\test\annie-win-2\webrtc-uwp-sdk\webrtc\xplatform\depot_tools\ninja.exe -C ../../../../../out/winuwp_10_x64_debug/ ./boringssl.dll.lib
1>    ninja: Entering directory `../../../../../out/winuwp_10_x64_debug/'
1>    [1/494] STAMP obj/build/config/sanitizers/deps_no_options.stamp
1>    [2/494] STAMP x64/obj/build/config/sanitizers/deps_no_options.stamp
1>    [3/494] STAMP obj/build/config/sanitizers/deps.stamp
1>    [4/494] STAMP x64/obj/build/config/sanitizers/deps.stamp
1>    [5/494] STAMP x64/obj/build/win/default_exe_manifest__gen_manifest.inputdeps.stamp
1>    [6/494] CXX x64/obj/third_party/winuwp_compat/winuwp_compat/winuwp_compat_std.obj
1>    [7/494] ACTION //build/win:default_exe_manifest__gen_manifest(//build/toolchain/win:x64)
1>    [8/494] CXX x64/obj/third_party/winuwp_compat/winuwp_compat/winuwp_compat_noop.obj
1>    [9/494] STAMP x64/obj/build/win/default_exe_manifest__gen_manifest.stamp
1>    [10/494] CXX obj/third_party/winuwp_compat/winuwp_compat/winuwp_compat_noop.obj
1>    [11/494] STAMP x64/obj/build/win/default_exe_manifest__gen_rc.inputdeps.stamp
1>    [12/494] CXX x64/obj/third_party/winuwp_compat/winuwp_compat/winuwp_compat_win.obj
1>    [13/494] ACTION //build/win:default_exe_manifest__gen_rc(//build/toolchain/win:x64)
1>    [14/494] CXX x64/obj/third_party/winuwp_compat/winuwp_compat/winuwp_compat_internal.obj
1>    [15/494] STAMP x64/obj/build/win/default_exe_manifest__gen_rc.stamp
1>    [16/494] STAMP x64/obj/build/win/default_exe_manifest.inputdeps.stamp
1>    [17/494] LIB x64/obj/third_party/winuwp_compat/winuwp_compat.lib
1>    [18/494] STAMP x64/obj/third_party/winuwp_compat/force_include_std.stamp
1>    [19/494] RC x64/obj/build/win/default_exe_manifest/default_exe_manifest.manifest.res
1>    [20/494] STAMP x64/obj/third_party/winuwp_compat/force_include_win.stamp
1>    [21/494] STAMP x64/obj/build/win/default_exe_manifest.stamp
1>    [22/494] STAMP x64/obj/third_party/yasm/genmacro.inputdeps.stamp
1>    [23/494] STAMP x64/obj/third_party/yasm/genmodule.inputdeps.stamp
1>    [24/494] CXX obj/third_party/winuwp_compat/winuwp_compat/winuwp_compat_std.obj
1>    [25/494] ACTION //third_party/yasm:generate_x86_insn(//build/toolchain/win:x64)
1>    [26/494] STAMP x64/obj/third_party/yasm/genperf.inputdeps.stamp
1>    [27/494] CXX obj/third_party/winuwp_compat/winuwp_compat/winuwp_compat_internal.obj
1>    [28/494] STAMP x64/obj/third_party/yasm/generate_x86_insn.stamp
1>    [29/494] STAMP x64/obj/third_party/yasm/re2c.inputdeps.stamp
1>    [30/494] CC x64/obj/third_party/yasm/genmacro/genmacro.obj
1>    [31/494] CC x64/obj/third_party/yasm/genmodule/genmodule.obj
1>    [32/494] CC x64/obj/third_party/yasm/genperf/perfect.obj
1>    [33/494] CC x64/obj/third_party/yasm/re2c/dfa.obj
1>    [34/494] CC x64/obj/third_party/yasm/genperf/genperf.obj
1>    [35/494] LINK x64/genmacro.exe x64/genmacro.exe.pdb
1>    [36/494] CC x64/obj/third_party/yasm/re2c/substr.obj
1>    [37/494] STAMP x64/obj/third_party/yasm/compile_nasm_macros.inputdeps.stamp
1>    [38/494] CC x64/obj/third_party/yasm/re2c/scanner.obj
1>    [39/494] STAMP x64/obj/third_party/yasm/compile_win64_gas.inputdeps.stamp
1>    [40/494] LINK x64/genmodule.exe x64/genmodule.exe.pdb
1>    [41/494] STAMP x64/obj/third_party/yasm/compile_win64_nasm.inputdeps.stamp
1>    [42/494] STAMP x64/obj/third_party/yasm/generate_module.inputdeps.stamp
1>    [43/494] CC x64/obj/third_party/yasm/re2c/code.obj
1>    [44/494] CC x64/obj/third_party/yasm/re2c/actions.obj
1>    [45/494] CXX obj/third_party/winuwp_compat/winuwp_compat/winuwp_compat_win.obj
1>    FAILED: obj/third_party/winuwp_compat/winuwp_compat/winuwp_compat_win.obj 
1>    ninja -t msvc -e environment.winuwp_x64 -- "C:\Program Files (x86)\Microsoft Visual Studio\Shared\14.0\VC\BIN\amd64\cl.exe" /nologo /showIncludes /FC @obj/third_party/winuwp_compat/winuwp_compat/winuwp_compat_win.obj.rsp /c ../../third_party/winuwp_compat/winuwp_compat_win.cc /Foobj/third_party/winuwp_compat/winuwp_compat/winuwp_compat_win.obj /Fd"obj/third_party/winuwp_compat/winuwp_compat_cc.pdb"
**1>c:\program files (x86)\windows kits\10\include\10.0.16299.0\um\fileapi.h(1451): error C2375: 'winuwpGetTempPathA': redefinition; different linkage [c:\_S\test\annie-win-2\webrtc-uwp-sdk\webrtc\xplatform\webrtc\out\winuwp_10_x64_Debug\obj\third_party\boringssl\boringssl.vcxproj]**
1>    c:\_s\test\annie-win-2\webrtc-uwp-sdk\webrtc\xplatform\webrtc\third_party\winuwp_compat\winuwp_compat_win.h(349): note: see declaration of 'winuwpGetTempPathA'
**1>c:\program files (x86)\windows kits\10\include\10.0.16299.0\um\winbase.h(5262): error C2375: 'winuwpCopyFileA': redefinition; different linkage [c:\_S\test\annie-win-2\webrtc-uwp-sdk\webrtc\xplatform\webrtc\out\winuwp_10_x64_Debug\obj\third_party\boringssl\boringssl.vcxproj]**
1>    c:\_s\test\annie-win-2\webrtc-uwp-sdk\webrtc\xplatform\webrtc\third_party\winuwp_compat\winuwp_compat_win.h(420): note: see declaration of 'winuwpCopyFileA'
**1>c:\program files (x86)\windows kits\10\include\10.0.16299.0\um\winbase.h(5270): error C2375: 'winuwpCopyFileW': redefinition; different linkage [c:\_S\test\annie-win-2\webrtc-uwp-sdk\webrtc\xplatform\webrtc\out\winuwp_10_x64_Debug\obj\third_party\boringssl\boringssl.vcxproj]**
1>    c:\_s\test\annie-win-2\webrtc-uwp-sdk\webrtc\xplatform\webrtc\third_party\winuwp_compat\winuwp_compat_win.h(414): note: see declaration of 'winuwpCopyFileW'
1>    [46/494] CC x64/obj/third_party/yasm/re2c/main.obj
1>    [47/494] ACTION //third_party/yasm:compile_win64_gas(//build/toolchain/win:x64)
1>    [48/494] ACTION //third_party/yasm:compile_nasm_macros(//build/toolchain/win:x64)
1>    [49/494] ACTION //third_party/yasm:generate_module(//build/toolchain/win:x64)
1>    [50/494] ACTION //third_party/yasm:compile_win64_nasm(//build/toolchain/win:x64)
1>    ninja: build stopped: subcommand failed.
1>c:\_S\test\annie-win-2\webrtc-uwp-sdk\webrtc\xplatform\webrtc\out\winuwp_10_x64_Debug\obj\third_party\boringssl\boringssl.vcxproj(1380,5): error MSB3073: The command "call c:\_S\test\annie-win-2\webrtc-uwp-sdk\webrtc\xplatform\depot_tools\ninja.exe -C ../../../../../out/winuwp_10_x64_debug/ ./boringssl.dll.lib" exited with code 1.
1>  Done Building Project "c:\_S\test\annie-win-2\webrtc-uwp-sdk\webrtc\xplatform\webrtc\out\winuwp_10_x64_Debug\obj\third_party\boringssl\boringssl.vcxproj" (default targets) -- FAILED.

**Comment by navrkald** [comment]
After research I found that problem is in webrtc-uwp-sdk\webrtc\xplatform\webrtc\third_party\winuwp_compat\winuwp_compat_win.h which is injected using /FI cl.exe flag for winuwp project. And overhides win api functions from c:\program files (x86)\windows kits\10\include\<version>\um\fileapi.h

**Comment by navrkald** [comment]
Here is fix: https://github.com/webrtc-uwp/webrtc-uwp-scripts/pull/5

**Comment by SergioOpenPeer** [comment]
@vmancic Please clone https://github.com/webrtc-uwp/webrtc-uwp-sdk.git master branch, Run prepare and try to build for x64 Debug

**Comment by vmancic** [comment]
The issue is confirmed on webrtc-uwp master branch. However, the fix mention in this ticket will not be implemented on master branch since this problem is not present on m62, and m62-to-master merge is expected soon.
