### ISSUE TITLE
encoding broken on nuget package 1.71.0.8 x64

### ISSUE THREAD

**Issue by ispysoftware** [webrtc-uwp/webrtc-uwp-sdk#174]
just switched to latest nuget package and x64 encode seems to be broken

Our app running on x86 build with color test (correct):

![image](https://user-images.githubusercontent.com/800093/60968331-62646000-a34f-11e9-959b-9e4adbbb6bdc.png)

on x64 build:
![image](https://user-images.githubusercontent.com/800093/60968450-ac4d4600-a34f-11e9-9c2c-cf4b6e155017.png)

**Comment by robin-raymond** [comment]
@SergioOpenPeer @nikolamand What changed? Is this because of the "faux" branch I introduced? cc: @ispysoftware

**Comment by ispysoftware** [comment]
I reverted this 
https://github.com/webrtc-uwp/libvpx/compare/b8026ed175f32a73f6a7bc2705e314056181cfb0...e724c9d418ebbe4f98a206c6ec624fcd502408d2?diff=unified

which fixed the issue

- I don't know why it was working on 32 bit and not 64 bit. 
- I'm passing a BGR24 bit byte array in so I was suprised it worked correctly originally. Your update was probably correct and has now "fixed" the fact that it shouldn't have worked in the first place. If that is the case could you please add in a BGR24 option which does the original transform so I don't have to do a full byte-re-arrange before sending the frame in?

**Comment by robin-raymond** [comment]
That makes sense. I exposed all the existing RBG formats that were already in libyuv as adding means supporting a fork of libyuv with additional stuff for a library that is 3rd party to us. But I think it might not be too bad to add it in this case. You are right that is a common format.

**Comment by ispysoftware** [comment]
From looking at 

https://chromium.googlesource.com/libyuv/libyuv/+/refs/heads/master/source/row_common.cc

.. those channel mappings seem like a hell of a thing to have been wrong for all this time with all the apps that are using it - are you 100% sure that code is wrong?

**Comment by robin-raymond** [comment]
Yup, I was equally as surprised! We took frames from MS capturer API where we can control the output format from their API. I took those frames and shoved them through the yuv conversion routines and the color was wacky. I couldn't figure out what we were doing wrong and then I played with the channels by forcing colours into the various encoding formats and it became clear that the issue was yuv itself. I don't understand how that is possible in such a library but it appears to be true. I'm still so shocked that I welcome anyone to double check that I'm not "missing" something because it does seem improbable.

**Comment by ispysoftware** [comment]
the background color on my webrtc video is bgr 20,20,20 which should be very dark gray. I think something is screwy in the new mappings because it's coming out blue, where if it was just 2 channels reversed they are both the same colour so it shouldn't make any difference...

**Comment by djee-ms** [comment]
@ispysoftware is that still an issue? I believe you reverted https://github.com/webrtc-uwp/libvpx/compare/b8026ed175f32a73f6a7bc2705e314056181cfb0...e724c9d418ebbe4f98a206c6ec624fcd502408d2?diff=unified which was indeed incorrect, and @robin-raymond already reverted it too, see _e.g._ abf57387e00579a15925b95961d3ad5ec16c5b69, which fixed the blue-ish video for me.

**Comment by ispysoftware** [comment]
I'm not using the latest update as I added some code in to support passing frames in by pointer instead of by byte array which hasn't made it into the repo

https://github.com/webrtc-uwp/webrtc-uwp-sdk/issues/178
