### ISSUE TITLE
Invalid libyuv change?

### ISSUE THREAD

**Issue by djee-ms** [webrtc-uwp/webrtc-uwp-sdk#176]
I believe that this change is invalid:
https://github.com/webrtc-uwp/libyuv/commit/8e69003dfee7e1cde88fc4d691e97121a7149d7a

According to the [libyuv documentation](https://chromium.googlesource.com/libyuv/libyuv/+/refs/heads/master/docs/formats.md#the-argb-fourcc):
> If you were to read ARGB pixels as uint32's, the alpha would be in the high byte, and the blue in the lowest byte. In memory, these are stored little endian, **so ‘B’ is first, then ‘G’, ‘R’ and ‘A’ last.**

This is what the code used to do correctly, but was changed. This results in a blue-ish video image:
```diff
-    YuvPixel(src_y[0], u, v, rgb_buf + 0, rgb_buf + 1, rgb_buf + 2,
+    YuvPixel(src_y[0], u, v, rgb_buf + 3, rgb_buf + 2, rgb_buf + 1,
             yuvconstants);
             yuvconstants);
-    rgb_buf[3] = 255;
+    rgb_buf[0] = 255;
```

**Comment by djee-ms** [comment]
While looking for another issue I noticed #174 and I believe this is a duplicate, although I see no revert on the `releases/m71` branch so leaving this one open.

**Comment by robin-raymond** [comment]
Yes, you are correct. I reverted the changes. Microsoft's code returns frames encoded in BE (storage) order whereas libyuv is using LE, but I didn't notice the LE comment in libyuv and it's an unusual encoding given that most format use the proper BE/storage ordering.
