### ISSUE TITLE
GetAudioCaptureDevices not found

### ISSUE THREAD

**Issue by infrasoft2007** [webrtc-uwp/webrtc-uwp-sdk#18]
Hi,
missing the functions in Media instance:
- GetAudioCaptureDevices()
- GetAudioPlayoutDevices()
- SelectAudioCaptureDevice()

Some sample not work with updated nuget webrtc.

**Comment by jamescadd** [comment]
Thanks for the note - which samples are you having issues with? I believe those methods were all removed from WebRTC and you'll need to use UWP alternatives to enumerate devices, but I'll check.

**Comment by infrasoft2007** [comment]
Thank for your reply.
PeerConnectionSample, for example, not show the list of mic.
Now only with ORTC lib I can set mic for streaming. 
If I want set mic with webrtc lib, how I can do it?

**Comment by manjia** [comment]
Hey @jamescadd I see you're still making people to wait lifetimes just to provide inconsistent answers, just be honest and tell everybody to go look for a solution somewhere else, it's pretty clear that nobody is going nowhere by relying on your support.
Btw you know it's thanks to people like you that Microsoft is the joke of computer science right?

**Comment by robin-raymond** [comment]
@manjia There's no reason for personal attacks. @jamescadd isn't mandated to reply to an open source effort. He's trying to help out where he can. Issues get missed at times and it's not intentional. These methods are not present because of the way WebRTC engine works now and we are evaluating alternative approaches to make life easier. We know this is an ongoing concern.

**Comment by manjia** [comment]
@robin-raymond Yes I know, looks like nobody in Microsoft is mandated to reply to open source efforts and no, I disagree, there's definitely a reason for a personal attack: as far as I know, @jamescadd is the "Microsoft Program Manager of Windows Developer Platform Group" or some similar bombastic work charge so I doubt he uses to answer issues for fun on his free time, do you want me to post a wall of links where @jamescadd in person makes people to wait for literaly months just to later reply them with a "can you better specify what is not working?" or some other useless crap like that? Of course he is not the only one who unintentionally misses issues, he just follows Microsoft's way of doing things, and there is my point: it's thanks to people like him if Microsoft is the joke of computer science. In my company if I'd let an issue about a product I'm in charge unanswered for 6 months my boss would probably whip me with a nettle branch, while in Microsoft this seems to be the very normal way to do things.

**Comment by robin-raymond** [comment]
@manjia This is not the place for these kinds of attacks. He's **not** in charge of answering questions for this open source project. James has been giving access to helpful information we need to make this project work on the Windows platform but a bunch of non-Microsoft employees has been trying our best to make it happen. We are very grateful to him to helping us get the information we need about UWP APIs and SDKs. It's not his job to monitor on here but, again, we're grateful he's popped by and been helping us.

You are literally attacking the wrong person here. If anyone you want to complain about it's me! So feel free. With the volume of code and limited resources, a large variety of features, and questions coming in all over the place I can say as an open source project we miss stuff. Generally most people will "bump" a thread if there's something we missed that is pressing. We are trying our best to bring this technology to the UWP platform (and other platforms) but attacking the person who has been instrumental on getting us technical answers to the Microsoft platform, that's not cool in my books.

The ability to enumerate devices was removed from WebRTC by google as it's done at a different layer. This is not something we did as that's what happened in the original WebRTC code. Most people have been able to work around this issue by specifying a device ID and doing the enumeration themselves. We do want to try and bring back this kind of API but there's been a lot of other things we've been doing so my apologies.

**Comment by jamescadd** [comment]
Keeping things on topic - WebRTC uses the default audio capture/output devices in the Google implementation.  This implementation mirrors the Google approach, so you would need to set the devices as default:
1. In Settings, search for Manage Audio Devices
2. Choose the preferred input/output device, use the "Set Default" button

For a programmatic approach you would need to implement this in the WebRTC audio engine, cloning a pre-M54 version of the repo and replicating the code in the above mentioned functions should get you there.  We'll consider adding this in the future as it would be nice to have.
