### ISSUE TITLE
UI hang on 32 bit

### ISSUE THREAD

**Issue by ispysoftware** [webrtc-uwp/webrtc-uwp-sdk#180]
When the webrtc connection is setting up, the UI is hanging for about 2-3 seconds. It's only happening on a 32 bit build and it's not happening (weirdly) when performance profiler is attached to the process. It's an issue because our software then thinks all the cameras have disconnected and restarts them. 64 bit is working fine.

**Comment by robin-raymond** [comment]
@ispysoftware indeed weird - m71 or m75? Is there a particular method call you are aware of when the freeze happens after?

**Comment by ispysoftware** [comment]
m75 - i'm not sure what's causing it - i was trying to use performance profiler to track it down but having that running stops the issue from happening. It seems to hang right after the iceConnectionState on the client transitions to "checking" and remains hung until it hits "complete"

**Comment by robin-raymond** [comment]
I can't seem to reproduce this issue. I've tried a number of times. If you think you can create a project which repos it I'll be happy to take a look. Are you using the nuget or your own build? I assume you are using your own build.

**Comment by ispysoftware** [comment]
i'm using my own build but it's just the very latest m75+ my pointer code for pushing frames in.  I'll see if i can dig into it further and re-open if i find anything.
