### ISSUE TITLE
[m75] Build failure on arm64 uwp debug

### ISSUE THREAD

**Issue by djee-ms** [webrtc-uwp/webrtc-uwp-sdk#187]
Trying to compile the `releases/m75` branch on UWP Debug ARM64, it seems that `common_audio` uses neon64 but is compiled with MSVC and the intrinsics are not recognized.

Incidentally I thought @SergioOpenPeer from your comment on #155 that arm64 could only be compiled with `clang-cl`. Did I misunderstand? Was it only for `libyuv`?

Thanks

```
[1/2648] CC obj/common_audio/common_audio_neon_c/cross_correlation_neon.obj
FAILED: obj/common_audio/common_audio_neon_c/cross_correlation_neon.obj
ninja -t msvc -e environment.store_arm64 -- "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\ARM64/cl.exe" /nologo /showIncludes @obj/common_audio/common_audio_neon_c/cross_correlation_neon.obj.rsp /c ../../common_audio/signal_processing/cross_correlation_neon.c /Foobj/common_audio/common_audio_neon_c/cross_correlation_neon.obj /Fd"obj/common_audio/common_audio_neon_c_c.pdb"
../../common_audio/signal_processing/cross_correlation_neon.c(64): error C2220: warning treated as error - no 'object' file generated
../../common_audio/signal_processing/cross_correlation_neon.c(64): warning C4013: 'vaddvq_s64' undefined; assuming extern returning int
[2/2648] CC obj/common_audio/common_audio_neon_c/min_max_operations_neon.obj
FAILED: obj/common_audio/common_audio_neon_c/min_max_operations_neon.obj
ninja -t msvc -e environment.store_arm64 -- "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\ARM64/cl.exe" /nologo /showIncludes @obj/common_audio/common_audio_neon_c/min_max_operations_neon.obj.rsp /c ../../common_audio/signal_processing/min_max_operations_neon.c /Foobj/common_audio/common_audio_neon_c/min_max_operations_neon.obj /Fd"obj/common_audio/common_audio_neon_c_c.pdb"
../../common_audio/signal_processing/min_max_operations_neon.c(47): error C2220: warning treated as error - no 'object' file generated
../../common_audio/signal_processing/min_max_operations_neon.c(47): warning C4013: 'vmaxvq_u16' undefined; assuming extern returning int
../../common_audio/signal_processing/min_max_operations_neon.c(107): warning C4013: 'vmaxvq_u32' undefined; assuming extern returning int
../../common_audio/signal_processing/min_max_operations_neon.c(150): warning C4013: 'vmaxvq_s16' undefined; assuming extern returning int
../../common_audio/signal_processing/min_max_operations_neon.c(193): warning C4013: 'vmaxvq_s32' undefined; assuming extern returning int
../../common_audio/signal_processing/min_max_operations_neon.c(230): warning C4013: 'vminvq_s16' undefined; assuming extern returning int
../../common_audio/signal_processing/min_max_operations_neon.c(273): warning C4013: 'vminvq_s32' undefined; assuming extern returning int
```

**Comment by SergioOpenPeer** [comment]
@djee-ms I would say that you are not compiling with clang-cl. To compile with clang-cl, from webrtc-uwp-sdk\scripts folder, run this command line:
`run.py -a prepare build -p winuwp -x arm64 -c debug --clang`
Another option is to compile WebRtc.UWP.Native.Builder project, from WebRtc.Universal.sln.

Both builds are tested for the releases/m75 branch and VS2017.

**Comment by djee-ms** [comment]
Ok thanks @SergioOpenPeer that was it, I missed that `--clang` flag, I assumed it was the default when compiling `arm64`. I upgraded my build script to pass that flag and now it compiles well.

Did you test also all the other variants with `--clang` (`x86`, `x64`, and `arm`) or is that supported only for `arm64`? Just out of curiosity, to see if `clang-cl` is a possible alternative to MSVC and to be able to compile everything with the same compiler.

Also, if `arm64` doesn't compile with MSVC, should the script return an error instead of trying to build and fail? And/or shouldn't this `--clang` flag be added automatically to avoid mistakes?

**Comment by SergioOpenPeer** [comment]
winuwp for x86, x64 can be compiled with clang-cl and cl, but arm can be compiled only with cl.

**Comment by djee-ms** [comment]
Ok thanks. Closing this issue since it was my fault.
