### ISSUE TITLE
Why RawVideoSource can't return the peer video data? #4

### ISSUE THREAD

**Issue by youshinki** [webrtc-uwp/webrtc-uwp-sdk#2]
I want get the remote yuv data, so i used RawVideoSource in OnAddRemoteStream event func.
But this RawVideoSource.OnRawVideoFrame event func did not return the data what i wanted.

This is what i got:
uint __param0 = 640
uint __param1 = 480,
byte[] __param2 ={0}
uint __param3 = 0
byte[] __param4 = {0}
uint __param5 = 0
byte[] __param6 = {0}
uint __param7 = 0

Please help!!
ps: i'm using nuget webrtc lib version 1.54.2  and  h264 codec

**Comment by morosev** [comment]
Hi youshinki,
Unfortunately, you cannot obtain raw video data in application layer if you intend to use H.264 codec. Raw (uncompressed) video data are available for VP8 and VP9 only. We are doing some changes related to H.264 decoding engine and this method (CreateRawVideoSource()) will be ready to be used with H.264 in about a month.
In the meantime, you can take  encoded H.264 data from WebRTC engine using method CreateEncodedVideoSource(). There is a code sample for making use of this method.

```
var source = Media.CreateMedia().CreateEncodedVideoSource(videoTrack);
source.OnEncodedVideoFrame += (width, height, frameData) =>
  {
    Debug.WriteLine("Encoded video frame received");
  };
```

**Comment by youshinki** [comment]
@morosev 
Thanks for your answer, is very helpful.

**Comment by NinoStella** [comment]
I'm testing the OnEncodedVideoFrame in the PeerCC sample, but the event is never fired. 
The OnRawVideoFrame works, but i don't know how to conver YUV planes to raw rgb. 
Any help?

**Comment by NinoStella** [comment]
I'm trying to use the OnRawVideoFrame, but if i attach the event handler, the application crashes few seconds after connection to peer has been established. 
if i remove the attached handler, all works as expected. 
Any suggestion?

**Comment by youshinki** [comment]
@HoloJackStones Base on your info，there may be have memory issues in your event handler.
Or may be doing too many works in the callback thread. Hoping this helps.
