### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by allbabel** [webrtc-uwp/webrtc-uwp-sdk#20]
Is there ARM support?  I am building for x86 and x64 on branch releases/m62 fine but preparing for ARM I get the following error.

`Traceback (most recent call last):
  File "C:/Users/andyb/source/repos/webrtc-uwp-sdk/webrtc/xplatform/webrtc/build/vs_toolchain.py", line 460, in <module>
    sys.exit(main())
  File "C:/Users/andyb/source/repos/webrtc-uwp-sdk/webrtc/xplatform/webrtc/build/vs_toolchain.py", line 456, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "C:/Users/andyb/source/repos/webrtc-uwp-sdk/webrtc/xplatform/webrtc/build/vs_toolchain.py", line 310, in CopyDlls
    _CopyPGORuntime(target_dir, target_cpu)
  File "C:/Users/andyb/source/repos/webrtc-uwp-sdk/webrtc/xplatform/webrtc/build/vs_toolchain.py", line 276, in _CopyPGORuntime
    raise NotImplementedError("Unexpected target_cpu value: " + target_cpu)
NotImplementedError: Unexpected target_cpu value: arm
ERROR at //build/toolchain/win/BUILD.gn:39:3: Script returned non-zero exit code.
  exec_script("../../vs_toolchain.py",
  ^----------
Current dir: C:/Users/andyb/source/repos/webrtc-uwp-sdk/webrtc/xplatform/webrtc/out/winuwp_10_arm_release/
Command: C:/Python27/python.exe -- C:/Users/andyb/source/repos/webrtc-uwp-sdk/webrtc/xplatform/webrtc/build/vs_toolchain.py copy_dlls C:/Users/andyb/source/repos/webrtc-uwp-sdk/webrtc/xplatform/webrtc/out/winuwp_10_arm_release Release arm
Returned 1.
See //BUILD.gn:11:1: which caused the file to be included.
group("default") {
^------------------

CRITICAL ERROR: Could not generate WebRTC projects for winuwp_10 platform, arm CPU`

Looking at vs_toolchain.py I see nothing for ARM.  I remember building the same WebRTC for ARM back in May from the master branch.

Andy

**Comment by jamescadd** [comment]
ARM support is available via this version of the NuGet package: https://www.nuget.org/packages/WebRTC/1.54.2

We're working on bringing ARM support up for the current M62 based builds as well but this is not yet complete.

**Comment by fdarie** [comment]
Does anyone know how to get the **source code** for the 1.54.2 version which has ARM support ?

**Comment by jamescadd** [comment]
@allbabel @fdarie This is coming with the M66 merger (should be done this week).

**Comment by mluketin** [comment]
@jamescadd 
Hi James, do you know when ARM support will be added to m71. I am asking because HoloLens2 is using ARM.

**Comment by robin-raymond** [comment]
@mluketin We are in the testing phase now for ARM but how long it's going to take to resolve all of the issues is unknown.

**Comment by jamescadd** [comment]
Hi @mluketin - there is a working ARM branch that I have tested on an Asus NovaGo available here: https://github.com/webrtc-uwp/webrtc-uwp-sdk/tree/Sergej/20190212-m71-arm  We're working to get this compiling with clang before merging it into releases/m71.

**Comment by tarukosu** [comment]
I'm eagerly waiting for ARM support.
When will it be merged to release branch?

**Comment by jamescadd** [comment]
ARM support is now available both in master and in releases/m71.  Note that there is a separate issue related to SIMD instruction support for ARM32 which does impact performance #155.  Please follow this issue for additional updates.  The latest alpha NuGet package supports ARM as well.
