### ISSUE TITLE
How to convert MediaAudioTrack / MediaStream  into IMediaSource in  Org.WebRtc.Media

### ISSUE THREAD

**Issue by minna-GitHub** [webrtc-uwp/webrtc-uwp-sdk#204]
Currently ( version 1.54),  Org.WebRtc.Media.CreateMediaSource() methods accepting only MediaVideoTrack but not MediaAudioTrack. Hence, we can not play audio alone with RTCMediaStreamConstraints ( audio =true, vedio=false). Do we have any alternative to get IMediaSource  for audio track.

Also, do we have any documentation on Org.WebRtc

**Comment by LoadLibrary** [comment]
Have you tried to use a more recent version?
The version 1.71.0.9 is the one being maintained.
Unfortunately documentation for Org.WebRTC is limited to what is available in IntelliSense and the sample Apps.

**Comment by minna-GitHub** [comment]
Hi Augusto Righetto,
Thanks for the response. I am using version 1.54.2. we are using media.GetAudioCaptureDevices() and media.GetAudioPlayoutDevices() methods for voice calls and Org.WebRtc.Media.CreateMediaSource()  is not required in our case. 
But, still, I am interested to use latest version 1.71.0.9. can you please share the documentation or sample project if any.

**Comment by LoadLibrary** [comment]
The API follows similar patterns as in https://www.w3.org/TR/webrtc/.
Feel free to take a look at the https://github.com/webrtc-uwp/PeerCC-XPlatform sample code.
