### ISSUE TITLE
Invalid chars in bat file

### ISSUE THREAD

**Issue by rogeru** [webrtc-uwp/webrtc-uwp-sdk#21]
File buildWebRTC.bat has invalid chars.
 https://github.com/webrtc-uwp/webrtc-uwp-scripts/blob/master/buildWebRTC.bat#L239

There seems to be other files as well.

$ unix2dos *.bat
unix2dos: converting file batchTerminator.bat to DOS format...
unix2dos: converting file buildORTC.bat to DOS format...
unix2dos: Binary symbol 0x1B found at line 239
unix2dos: Skipping binary file buildWebRTC.bat
unix2dos: converting file cleanWebRTC.bat to DOS format...
unix2dos: converting file Config.bat to DOS format...
unix2dos: Binary symbol 0x1B found at line 692
unix2dos: Skipping binary file createNuget.bat
unix2dos: Binary symbol 0x1B found at line 846
unix2dos: Skipping binary file createNuget2.bat
unix2dos: Binary symbol 0x1B found at line 229
unix2dos: Skipping binary file doItAll.bat
unix2dos: Binary symbol 0x1B found at line 697
unix2dos: Skipping binary file prepare.bat
unix2dos: Binary symbol 0x1B found at line 389
unix2dos: Skipping binary file prepareEventing.bat
unix2dos: Binary symbol 0x1B found at line 606
unix2dos: Skipping binary file prepareWebRtc.bat
unix2dos: Binary symbol 0x1B found at line 313
unix2dos: Skipping binary file publishSamples.bat
unix2dos: converting file registerAllEvents.bat to DOS format...
unix2dos: converting file test.bat to DOS format...

**Comment by robin-raymond** [comment]
This is ansi terminal colour coding via the escape character:

https://en.wikipedia.org/wiki/ANSI_escape_code
