### ISSUE TITLE
is this project still being maintained?

### ISSUE THREAD

**Issue by ispysoftware** [webrtc-uwp/webrtc-uwp-sdk#211]
There's been no updates or replies to questions in weeks - is Microsoft still working on this?

**Comment by LoadLibrary** [comment]
The ownership of this project has changed. The new team is ramping up and planing the best way to move this project forward.
I saw your message about "RTCIceConnectionState.Failed not always fired". The m71 branch is the one getting most of attention at this moment. The m75 branch was never promoted from alpha state due its lack of stability.
As soon as we have a clear roadmap I'll let the community know about it.

**Comment by ispysoftware** [comment]
Cool. Thanks for the info. Personally I'd like to see a net standard wrapper as that would cover all bases. Maintaining wrappers for different platforms seems like a lot of overhead.

**Comment by LoadLibrary** [comment]
This is something that is definitely in our radar.
Do you mind share other pain points you have while using WebRTC-UWP?

**Comment by ispysoftware** [comment]
Sure - our main goal is to be able to write a cross-platform app so net standard would be ideal. Every other component we have is cross platform. A net standard wrapper that we can push raw video and audio into would be fantastic - so the only platform specific stuff would be device access that can be external to the library (we have this working with the win32 version).

Other pain points are that there seem to be a lot of race conditions in m75 - we get random lockups and crashes (will try m71 today, didn't realise m75 was alpha). Also the lack of hardware H264 encode in win32 is forcing VP8 which is a CPU hog in high resolution. 

We launched a UWP app on the store based on m75 but it crashed so many times (with webrtc related errors) we had to take it down.

**Comment by LoadLibrary** [comment]
Thanks for your feedback! :)
Net standard is a popular request and we're looking at that for the future.
I don't recommend shipping m75 in prod. 
Feel free to do a pull request with your changes. Please use the m71 branch.
Which win32 app and branch are you using?

**Comment by ispysoftware** [comment]
here's a test project. It randomly crashes with

Exception thrown: read access violation.
mtx was 0xFFFFFFFFFFFFFFFF.

in mtx_do_lock on mutex.c

[m71test.zip](https://github.com/webrtc-uwp/webrtc-uwp-sdk/files/3899141/m71test.zip)
(might need to run it a few times)

to get this to run at all you need to apply a fix to zslib to handle not having a window (this is a console app)

https://github.com/webrtc-uwp/webrtc-uwp-sdk/issues/181#issuecomment-538999223

**Comment by alexisconia** [comment]
@ispysoftware  did you find a solution to use m71 with a console app ?

**Comment by ispysoftware** [comment]
Yes I had to make a few changes to zslib. The changes I made are in another comment.

**Comment by ispysoftware** [comment]
Can we get a status update on this project? Not much seems to be happening with it - if it's been abandoned can someone at Microsoft please let us know as we have a lot of tech debt with it and will need to strategise accordingly.

**Comment by LoadLibrary** [comment]
We are currently focusing our efforts on getting out of the fork business. Keeping this fork doesn't allow us to move fast enough. We are contributing back the changes needed to build WebRTC.org code base for UWP. Here are some of the changes we're contributing back:
. https://webrtc-review.googlesource.com/c/src/+/167021
. https://boringssl-review.googlesource.com/c/boringssl/+/39584
. https://chromium-review.googlesource.com/c/chromium/src/+/1962509
. https://github.com/abseil/abseil-cpp/pull/594
. https://github.com/abseil/abseil-cpp/pull/596
Besides the new video capturing module that is being reviewed, we're also creating a new audio capturing module.
There are more changes in the pipeline to be contributed back and more changes required for finishing the port.
After having WebRTC.org code base compatible with UWP, we're going to work on a WinRT abstraction layer allowing easy consumption of WebRTC capabilities by WinRT projections.
We want to be finished by end of March. That said, keep in mind we are contributing back the changes and we have no control over when/if the changes will be accepted by their teams.

**Comment by ispysoftware** [comment]
Thank you. Are there still plans to create a net standard version of the library?

**Comment by LoadLibrary** [comment]
Yes, there are plans for having a net standard version of the library.
