### ISSUE TITLE
VideoCapturer.Create sometimes stalls the executing Task

### ISSUE THREAD

**Issue by dl4mmers** [webrtc-uwp/webrtc-uwp-sdk#213]
Hey, we are using the WebRtc nuget package v1.71.0.9 in a DLL used by our Unity-HoloLens-UWP app to stream audio and video from the HoloLens to a browser client (and vice versa) using a Freeswitch and Verto. Our implementation is based on the [PeerCC-X-Platform](https://github.com/webrtc-uwp/PeerCC-XPlatform) and [PeerCC](https://github.com/webrtc-uwp/PeerCC) examples. 

Creating the peer connection is executed in a task and sometimes it happens that VideoCapturer.Create stalls the task, so that the task never finishes. Most of the times everything works fine and running into this issue feels quiet random. I don't really know how to properly debug this to get a feel what happens under the hood. I have found the relevant line by writing debug logs to the console. 

Most of the executed code matches with the code of PeerCC-X-Platform (https://github.com/webrtc-uwp/PeerCC-XPlatform/blob/master/WebRtcAdapter/Call/Call.cs#L204). First `CreatePeerConnection()` gets called, inside this function `ConfigureRtc()` gets called and then `GetUserMedia()`, `AddLocalMediaTracks()` and `BindSelfVideo()` gets called. In function `GetUserMedia()` the blockade happens:

```
VideoCapturerCreationParameters capturerParams = new VideoCapturerCreationParameters
{
    Name = _selectedVideoDevice.DisplayName,
    Id = _selectedVideoDevice.Id,
    EnableMrc = false,
    Factory = factory
};

Debug.WriteLine("Before VideoCapturer.Create");
var videoCapturer = VideoCapturer.Create(capturerParams);
Debug.WriteLine("After VideoCapturer.Create");
```

The output "Before VideoCapturer.Create" always gets printed whereas the output "After VideoCapturer.Create" never gets printed when the issue occurs. The executing task then never finishes and peer connection won't get created. 

Do anyone know what could go wrong when VideoCapturer gets created and how to fix or workaround this?

**Comment by LoadLibrary** [comment]
Do you mean WebRTC-UWP v1.**71**.0.9 instead of v1.17.0.9?
What browser (and version) are you using for this test?
Have you tried using Chrome m71 for this test?

**Comment by dl4mmers** [comment]
Yes, I meant WebRTC-UWP v1.71.0.9.
I'm using Chrome v78.0.3904.108, but i just tested Chrome v71.0.3578.98 and this issue occurs on both versions. 

I've made a workaround by waiting a specific time for the task to finish and on timeout, I create a new instance of this task and wait again. That's definitely not the best or cleanest solution, but video connection always get's established now.

**Comment by LoadLibrary** [comment]
I'm glad you got unblocked. I agree that apps shouldn't need to deal with this kind of synchronization issues.
The ownership of this component have changed recently and the new team is planning on the best way to keep it. We should be sharing publicly the roadmap next quarter.
