### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by mluketin** [webrtc-uwp/webrtc-uwp-sdk#218]
Is there any plan to support ARM64? Right now only ARM is supported, but for [HoloLens 2 it is preferred to build ARM64 applications](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-porting-guide#compile-dependenciesplugins-for-arm-processor).

**Comment by LoadLibrary** [comment]
We're actively working on bringing WebRTC-UWP up to m79. ARM64 is part of that work.
