### ISSUE TITLE
StopRecordAsync never returns

### ISSUE THREAD

**Issue by binxie33** [webrtc-uwp/webrtc-uwp-sdk#219]
I am implementing my own uwp capture device, mostly copying the codes from impl_webrtc_VideoCapturer.cpp, it works well for capturing video, but when I try to stop the capture, it always hangs in CaptureDevice::StopCapture()  function:

media_capture_.get().StopRecordAsync().get();  <==== never returns

Appreciate any assistance.

**Comment by binxie33** [comment]
I can see the flash light of  the camera turns off, which means stop recording does succeed, it is just the call to .get() never returns.

**Comment by binxie33** [comment]
if I don't call .get() to make StopRecordAsync to wait, it won't hang and everything seems works fine but the camera does not close. 

I managed to workaround the problem by adding a sleep(100ms) after the StopRecordAsync() call, the camera is closed and the thread does not hang.

But the root cause remains unclear.

**Comment by LoadLibrary** [comment]
That Sleep shouldn't be required...
I'm glad you've found an workaround.
