### ISSUE TITLE
master and releases/m62 branch builds failing with VS2017 15.4.2/SDK 16299

### ISSUE THREAD

**Issue by r-b-us** [webrtc-uwp/webrtc-uwp-sdk#22]
Gives a few errors whether building debug or release, x32 or x64 (this example is from release x64):

1. Metadata file 'D:\webrtc-uwp-Jan2018\webrtc-uwp-sdk\webrtc\windows\solutions\Build\Output\x64\Release\Org.WebRtc\Org.WebRtc.winmd' could not be found.

2. The command "pushd "D:\webrtc-uwp-Jan2018\webrtc-uwp-sdk\webrtc\windows\projects\msvc\WebRtc.Builder.Universal\..\..\..\..\..\" && call "bin\prepare.bat" -target webrtc -platform x64 -logLevel 4 && call "bin\prepare.bat" -target webrtc -platform win32 -logLevel 4 && popd && pushd "D:\webrtc-uwp-Jan2018\webrtc-uwp-sdk\webrtc\windows\projects\msvc\WebRtc.Builder.Universal\..\..\..\..\..\webrtc\xplatform\webrtc\out\winuwp_10_x64_Release" && call "..\..\..\..\..\webrtc\xplatform\depot_tools\ninja" webrtc && call "..\..\..\..\..\webrtc\xplatform\depot_tools\ninja" webrtc/rtc_base:rtc_json && popd" exited with code 1.				

3. '../../third_party/yasm/source/patched-yasm/modules/objfmts/elf/elf-x86-x32.c', needed by 'x64/obj/third_party/yasm/yasm/elf-x86-x32.obj', missing and no known rule to make it	WebRtc.Builder	D:\webrtc-uwp-Jan2018\webrtc-uwp-sdk\webrtc\windows\projects\msvc\WebRtc.Builder.Universal\ninja

4. LNK1181	cannot open input file 'third_party\boringssl\boringssl.lib'

Noticed some earlier issues with 16299 but there was a comment that m62 fixed them, hence the new issue.

**Comment by vmancic** [comment]
Update on Jan 15 2018: 

1) Reported issue not found on releases/m62 branch, x64 Debug and x64 Release

2) The issue confirmed with master branch, 

2.1) Master, Debug, x64:
--------------------------
1>ninja : error : '../../third_party/yasm/source/patched-yasm/modules/objfmts/elf/elf-x86-x32.c', needed by 'x64/obj/third_party/yasm/yasm/elf-x86-x32.obj', missing and no known rule to make it
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1276,5): error MSB3073: The command "pushd "C:\Work\jan15-uwp-master\webrtc-uwp-sdk\webrtc\windows\projects\msvc\WebRtc.Builder.Universal\..\..\..\..\..\" && call "bin\prepare.bat" -target webrtc -platform x64 -logLevel 4 && call "bin\prepare.bat" -target webrtc -platform win32 -logLevel 4 && popd && pushd "C:\Work\jan15-uwp-master\webrtc-uwp-sdk\webrtc\windows\projects\msvc\WebRtc.Builder.Universal\..\..\..\..\..\webrtc\xplatform\webrtc\out\winuwp_10_x64_Debug" && call "..\..\..\..\..\webrtc\xplatform\depot_tools\ninja" webrtc && call "..\..\..\..\..\webrtc\xplatform\depot_tools\ninja" webrtc/rtc_base:rtc_json && popd" exited with code 1.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

2.1) Master, Release, x64:
--------------------------
1>ninja : error : '../../third_party/yasm/source/patched-yasm/modules/objfmts/elf/elf-x86-x32.c', needed by 'x64/obj/third_party/yasm/yasm/elf-x86-x32.obj', missing and no known rule to make it
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1276,5): error MSB3073: The command "pushd "C:\Work\jan15-uwp-master\webrtc-uwp-sdk\webrtc\windows\projects\msvc\WebRtc.Builder.Universal\..\..\..\..\..\" && call "bin\prepare.bat" -target webrtc -platform x64 -logLevel 4 && call "bin\prepare.bat" -target webrtc -platform win32 -logLevel 4 && popd && pushd "C:\Work\jan15-uwp-master\webrtc-uwp-sdk\webrtc\windows\projects\msvc\WebRtc.Builder.Universal\..\..\..\..\..\webrtc\xplatform\webrtc\out\winuwp_10_x64_Release" && call "..\..\..\..\..\webrtc\xplatform\depot_tools\ninja" webrtc && call "..\..\..\..\..\webrtc\xplatform\depot_tools\ninja" webrtc/rtc_base:rtc_json && popd" exited with code 1.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by r-b-us** [comment]
Ok - thanks for that. I did try VS 2017 15.5.3 but can't recall if I used the m62 branch. I'll try again and hopefully it'll work for me too.

**Comment by r-b-us** [comment]
The combination of releases/m62 and VS 2017 15.5.3 works fine. Thanks!

**Comment by vmancic** [comment]
Fix for points 2. and 3. from bug description is provided in webrtc-uwp-sdk master branch.

**Comment by vmancic** [comment]
I was not able to get issues #1 and #4 from bug description. It would be helpful to know how did you get it.

**Comment by r-b-us** [comment]
Can't easily explain that unless it was something to do with using VS 2017 15.4.2 instead of a 15.5.x version. All I did was clone, prepare.bat and build. Maybe there were multiple problems, some solved by the m62 branch and some by VS 2017 15.5.x?

**Comment by vmancic** [comment]
Thanks.
