### ISSUE TITLE
Building for release?

### ISSUE THREAD

**Issue by Noemata** [webrtc-uwp/webrtc-uwp-sdk#24]
I was able to build Debug libs/DLLs with the provided build instructions, but when using the "webrtc-uwp-sdk\webrtc\windows\solutions\WebRtc.sln" file to build the UWP wrapper DLL, I failed to build a release version of the DLL due to missing libs.

It appears that the prepare script only builds for Debug.

How do we build for release?

**Comment by robin-raymond** [comment]
@vmancic please investigate this

**Comment by vmancic** [comment]
Which branch are you using, which platform are you building for? Can you send detailed log from running prepare.bat (please use -loglevel 4 when running prepare.bat).

I've just checked for master branch: I did successfully build UW projects (Release versions for x86 and x64) from webrtc-uwp-sdk\webrtc\windows\solutions\WebRtc.sln.

**Comment by Noemata** [comment]
Building from main branch, building for UWP x64/x86.  I discovered I can trigger the appropriate build target by doing a rebuild of WebRtc.Builder.  You might want to detail this in the docs.

**Comment by SergioOpenPeer** [comment]
fixed
