### ISSUE TITLE
Expose "raw" MediaCapture Object

### ISSUE THREAD

**Issue by jamescadd** [webrtc-uwp/webrtc-uwp-sdk#30]
@ghandmann commented on [Wed Oct 18 2017](https://github.com/webrtc-uwp/webrtc-windows/issues/11)

Hi There,
we currently experiment with the Hololens and WebRTC. Therefore we use this project as WebRTC library.

In order to enable the "mixed reality capture" of the Hololens we would need to have access to the raw [MediaCapture](https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.mediacapture) object to call "AddVideoEffectAsync". Currently i can't see any way this is exposed by your library. It looks like, that the needed object is created in [PeerConnectionInterface.cc Line 601](https://github.com/webrtc-uwp/webrtc-windows/blob/14e7b71ce361e877d3ec43e9df0ca85802bcebb6/org/webrtc/wrapper/PeerConnectionInterface.cc#L601)

Do you have any suggestion for us on how to access the needed information? 

Thanks,
Sven

---

@jamescadd commented on [Thu Oct 19 2017](https://github.com/webrtc-uwp/webrtc-windows/issues/11#issuecomment-338026676)

Hi Sven,

We have an open issue to enabled mixed reality capture for HoloLens.  It should be ready in approximately 1 month.  I'll leave this issue open and comment as we make progress, or feel free to reach out at jacadd@microsoft.com to discuss further.

Thanks,
James

---

@Noemata commented on [Sun Jan 28 2018](https://github.com/webrtc-uwp/webrtc-windows/issues/11#issuecomment-361098051)

Could you please provide updated information on this.

---

@Noemata commented on [Mon Jan 29 2018](https://github.com/webrtc-uwp/webrtc-windows/issues/11#issuecomment-361281749)

I'm presently looking through Media.h and Media.cc in order to find a place where we could wire in the HoloLens MediaCapture capability.  It's not obvious what needs to be tweaked.  Any suggestions since this has become a languishing item.  We'll do the work, we just need some hints.

---

@DanAndersen commented on [Thu Feb 22 2018](https://github.com/webrtc-uwp/webrtc-windows/issues/11#issuecomment-367796471)

Hi,
Has there been some development on enabling mixed reality capture? I am currently needing to use WebRTC for a HoloLens app, in which each frame being sent from the HoloLens contains a payload of metadata of the estimated pose of that frame.

---

@jamescadd commented on [Thu Feb 22 2018](https://github.com/webrtc-uwp/webrtc-windows/issues/11#issuecomment-367798621)

@Noemata @DanAndersen We're close, but have run into an issue that's preventing MRC from working.  I should have an update for this thread in the next day or 2, will keep everyone posted as this has been outstanding for some time.

---

@Noemata commented on [Mon Feb 26 2018](https://github.com/webrtc-uwp/webrtc-windows/issues/11#issuecomment-368518917)

Any updates on this, given we're past the next day or 2.  Sorry to be pestering about this, but we need to decide how to proceed.

---

@jamescadd commented on [Mon Feb 26 2018](https://github.com/webrtc-uwp/webrtc-windows/issues/11#issuecomment-368571665)

Sure thing, here's the latest instructions to build and a pointer to the MRC code.  The current status of this codebase is:

1. It's necessary to always select H.264 for the codec on both ends of the call as HoloLens only has hardware encode/decode support for that codec.
2. Performance issue exists when both clients are Unity based.  To work around this, run the standard PeerConnection client on the desktop side and Unity on HoloLens.
3. WASAPI audio is causing an issue with MRC; currently it must be disabled entirely for a call to be started.  WEBRTC_AUDIO_DEVICE_DISABLED which can be used to control WASAPI audio device inclusion. When the statement is defined, WASAPI device code is not compiled at all. WEBRTC_AUDIO_DEVICE_DISABLED define is controlled from file “ortclib-sdk\webrtc\xplatform\webrtc\webrtc\modules\audio_device\audio_device_config.h”.
4. The MRC code is located here: https://github.com/webrtc-uwp/webrtc/blob/Mosa/20180223-unity-hololens/webrtc/modules/video_capture/windows/video_capture_winuwp.cc#L417
I can verify that the code runs properly in the debugger, however the holograms aren't currently showing up in the remote feed.  Working on this as well.

I'd be interested to hear anyone's mileage on the above, let me know if you try it @Noemata .  Here are the instructions to build the latest Unity codebase:

1) Install Unity Editor 2017.2.0f3 with Metro Support
https://download.unity3d.com/download_unity/46dda1414e51/Windows64EditorInstaller/UnitySetup64-2017.2.0f3.exe
http://download.unity3d.com/download_unity/46dda1414e51/TargetSupportInstaller/UnitySetup-Metro-Support-for-Editor-2017.2.0f3.exe
2) Clone the repository: git clone --recursive -b Mosa/20180223-unity-hololens https://github.com/ortclib/ortclib-sdk.git ortclib-sdk-m62-media-engine-video
3) From a command prompt run bin\prepare.bat from the ortclib-sdk-m62-media-engine-video directory
4) Open ortclib-sdk-m62-media-engine-video\webrtc\windows\solutions\WebRtcUnity.sln
5) Select Debug configuration and x86 platform (others can be used as well)
6) Build project PeerConnectionClientUnity.WebRtc

---

@Noemata commented on [Mon Feb 26 2018](https://github.com/webrtc-uwp/webrtc-windows/issues/11#issuecomment-368582403)

Not having audio is a non starter for us.  What would be sufficient for our needs would be to wedge this code from the MixedRealityToolkit code into the WebRtc video_capture_winuwp.cc code:

_Use_decl_annotations_
HRESULT NetworkMediaSinkStreamImpl::ProcessCameraData(
    IMFSample* pSample,
    MediaSampleHeader* pSampleHeader)
{
    Log(Log_Level_Info, L"NetworkMediaSinkStreamImpl::ProcessCameraData()\n");

    NULL_CHK(pSample);
    NULL_CHK(pSampleHeader);
    NULL_CHK(_spParentMediaSink.Get());

    UINT32 blobSize = 0;

    using float4x4 = ABI::Windows::Foundation::Numerics::Matrix4x4;
    MFPinholeCameraIntrinsics cameraIntrinsics;
    float4x4 worldToCameraMatrix;
    float4x4 cameraProjectionTransform;
    float4x4 cameraViewTransform;

    // world coordinate system application is using
    using ISpatialCoordinateSystem = ABI::Windows::Perception::Spatial::ISpatialCoordinateSystem;
    ISpatialCoordinateSystem* cameraCoordinateSystem = nullptr;
    HRESULT hr = _spParentMediaSink->get_SpatialCoordinateSystem(&cameraCoordinateSystem);
    if (SUCCEEDED(hr))
    {
        // cameraCoordinates
        ComPtr<ISpatialCoordinateSystem> spSampleCoordinateSystem;
        hr = pSample->GetUnknown(MFSampleExtension_Spatial_CameraCoordinateSystem, __uuidof(ISpatialCoordinateSystem), &spSampleCoordinateSystem);
        if (SUCCEEDED(hr))
        {
            ComPtr<ABI::Windows::Foundation::IReference<ABI::Windows::Foundation::Numerics::Matrix4x4>> transformReference;
            hr = spSampleCoordinateSystem->TryGetTransformTo(cameraCoordinateSystem, &transformReference);
            if (SUCCEEDED(hr) && transformReference != nullptr)
            {
                hr = transformReference->get_Value(
                reinterpret_cast<ABI::Windows::Foundation::Numerics::Matrix4x4*>(&worldToCameraMatrix));
            }
        }

        // intrinsics
        if (SUCCEEDED(hr))
        {
            hr = pSample->GetBlob(MFSampleExtension_PinholeCameraIntrinsics, (UINT8*)&cameraIntrinsics, sizeof(cameraIntrinsics), &blobSize);
        }

        // projection
        if (SUCCEEDED(hr))
        {
            hr = pSample->GetBlob(MFSampleExtension_Spatial_CameraProjectionTransform, (UINT8*)&cameraProjectionTransform, sizeof(cameraProjectionTransform), &blobSize);
        }

        // camera view
        if (SUCCEEDED(hr))
        {
            hr = pSample->GetBlob(MFSampleExtension_Spatial_CameraViewTransform, (UINT8*)&cameraViewTransform, sizeof(cameraViewTransform), &blobSize);
        }
    }

What we need to get back is the CameraProjectionTransform and CameraViewTransform as some sort of globally accessible property, with an indicator of whether we're running on a HoloLens or not.  This is the scenario being used by Skype for HoloLens, and would be the best approach for WebRTC running on the HoloLens.

---

@jamescadd commented on [Mon Feb 26 2018](https://github.com/webrtc-uwp/webrtc-windows/issues/11#issuecomment-368645678)

Thanks for suggesting that alternative approach, and I can see how the transforms would be important. Mosa is working on this now, will let you know when it's ready. Perhaps it will also alleviate the audio issue.
________________________________
From: Mario Pintaric <notifications@github.com>
Sent: Monday, February 26, 2018 9:32:32 AM
To: webrtc-uwp/webrtc-windows
Cc: James Cadd; Comment
Subject: Re: [webrtc-uwp/webrtc-windows] Expose "raw" MediaCapture Object (#11)

Not having audio is a non starter for us. What would be sufficient for our needs would be to wedge this code from the MixedRealityToolkit code into the WebRtc video_capture_winuwp.cc code:

Use_decl_annotations
HRESULT NetworkMediaSinkStreamImpl::ProcessCameraData(
IMFSample* pSample,
MediaSampleHeader* pSampleHeader)
{
Log(Log_Level_Info, L"NetworkMediaSinkStreamImpl::ProcessCameraData()\n");

NULL_CHK(pSample);
NULL_CHK(pSampleHeader);
NULL_CHK(_spParentMediaSink.Get());

UINT32 blobSize = 0;

using float4x4 = ABI::Windows::Foundation::Numerics::Matrix4x4;
MFPinholeCameraIntrinsics cameraIntrinsics;
float4x4 worldToCameraMatrix;
float4x4 cameraProjectionTransform;
float4x4 cameraViewTransform;

// world coordinate system application is using
using ISpatialCoordinateSystem = ABI::Windows::Perception::Spatial::ISpatialCoordinateSystem;
ISpatialCoordinateSystem* cameraCoordinateSystem = nullptr;
HRESULT hr = _spParentMediaSink->get_SpatialCoordinateSystem(&cameraCoordinateSystem);
if (SUCCEEDED(hr))
{
    // cameraCoordinates
    ComPtr<ISpatialCoordinateSystem> spSampleCoordinateSystem;
    hr = pSample->GetUnknown(MFSampleExtension_Spatial_CameraCoordinateSystem, __uuidof(ISpatialCoordinateSystem), &spSampleCoordinateSystem);
    if (SUCCEEDED(hr))
    {
        ComPtr<ABI::Windows::Foundation::IReference<ABI::Windows::Foundation::Numerics::Matrix4x4>> transformReference;
        hr = spSampleCoordinateSystem->TryGetTransformTo(cameraCoordinateSystem, &transformReference);
        if (SUCCEEDED(hr) && transformReference != nullptr)
        {
            hr = transformReference->get_Value(
            reinterpret_cast<ABI::Windows::Foundation::Numerics::Matrix4x4*>(&worldToCameraMatrix));
        }
    }

    // intrinsics
    if (SUCCEEDED(hr))
    {
        hr = pSample->GetBlob(MFSampleExtension_PinholeCameraIntrinsics, (UINT8*)&cameraIntrinsics, sizeof(cameraIntrinsics), &blobSize);
    }

    // projection
    if (SUCCEEDED(hr))
    {
        hr = pSample->GetBlob(MFSampleExtension_Spatial_CameraProjectionTransform, (UINT8*)&cameraProjectionTransform, sizeof(cameraProjectionTransform), &blobSize);
    }

    // camera view
    if (SUCCEEDED(hr))
    {
        hr = pSample->GetBlob(MFSampleExtension_Spatial_CameraViewTransform, (UINT8*)&cameraViewTransform, sizeof(cameraViewTransform), &blobSize);
    }
}

What we need to get back is the CameraProjectionTransform and CameraViewTransform as some sort of globally accessible property, with an indicator of whether we're running on a HoloLens or not. This is the scenario being used by Skype for HoloLens, and would be the best approach for WebRTC running on the HoloLens.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwebrtc-uwp%2Fwebrtc-windows%2Fissues%2F11%23issuecomment-368582403&data=04%7C01%7Cjacadd%40microsoft.com%7Ce4c90ab5d8c8428b6e0d08d57d3eeb3d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636552631580428801%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwifQ%3D%3D%7C-1&sdata=kws9shIcrm%2FE7geWk8q155xe66hKEEEBHRmVN7C1i8U%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACmlAujOClcJKZd15QRzCdvpOt8SV9mmks5tYuqtgaJpZM4P9kyP&data=04%7C01%7Cjacadd%40microsoft.com%7Ce4c90ab5d8c8428b6e0d08d57d3eeb3d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636552631580438806%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwifQ%3D%3D%7C-1&sdata=cNB4wVJdXP5r6ebw36bHQPN6GoSk7kLMcmgFXTitCnE%3D&reserved=0>.

---

@Noemata commented on [Mon Feb 26 2018](https://github.com/webrtc-uwp/webrtc-windows/issues/11#issuecomment-368650723)

Thank you very much for the quick turn around on your reply.  Using the CameraProjectionTransform and CameraViewTransform approach allows us to do the compositing ourselves through several different approaches and eliminates bogging down the HoloLens side with this task.  If you do continue to proceed with the MRC approach on the HoloLens, please make it a feature we can disable, but always provide these Camera transform details on the HoloLens as there's no performance hit associated with these calls and it does allow us to then do the compositing through other means.

---

@adrianimajion commented on [Tue Mar 06 2018](https://github.com/webrtc-uwp/webrtc-windows/issues/11#issuecomment-370808855)

Hey, just wanted to check how progress is looking for exposing CameraProjectionTransform and CameraViewTransform. @morosev regardless of MRC this would be really valuable for us. Thanks 

---

@jamescadd commented on [Tue Mar 06 2018](https://github.com/webrtc-uwp/webrtc-windows/issues/11#issuecomment-370829634)

Hi all, we've determined that the likely cause of MRC not working is the D3D context management of UWP apps.  The quickest resolution is to separate out a Unity only app which, after which we expect the MRC code to just work.  Exposing the transforms per the above will be next up when that's complete.  Thanks!

---

@jamescadd commented on [Thu Mar 29 2018](https://github.com/webrtc-uwp/webrtc-windows/issues/11#issuecomment-377377666)

See related issue for an alternative method of remoting transform data: https://github.com/webrtc-uwp/webrtc-uwp-sdk/issues/10

---

@jamescadd commented on [Fri Mar 30 2018](https://github.com/webrtc-uwp/webrtc-windows/issues/11#issuecomment-377636171)

Latest bits are below - tested and working on PC but pending testing on HoloLens.  MRC code is in place but not yet tested, perf hasn't been verified either.

https://github.com/ortclib/ortclib-sdk/tree/Mosa/20180320-peercc-unity

- The desktop app should be the standard PeerConnection M62 build
- Codec is forced to H.264 and settings are hard coded.  Peer selection list isn't functional
- Enter the signaling server IP into the text box (HoloLens keyboard isn't implemented yet so use the virtual input feature on the device portal)
- Click the connect button in the Unity app, peer should show up on desktop
- Click the call button on Unity app (this app must initiate for now)

**Comment by jamescadd** [comment]
MRC is now working in the above branch, leaving the issue open until it is merged into the individual sample repo.

**Comment by jamescadd** [comment]
@ghandmann @Noemata @adrianimajion Access for raw media capture in some flavor, as well as an option to disable MRC, is under development.  Will ping you for feedback when ready.

**Comment by Noemata** [comment]
Thanks a bunch for this!

**Comment by morosev** [comment]
@ghandmann @Noemata @adrianimajion A way to extract CameraProjectionTransform and CameraViewTransform matrices in application layer has been added. For every video frame received from camera device a callback method which could be attached from application is called. The callback passes pointer value to `IMFSample` obtained from camera in synchronous way. Here is a sample code with dummy event handler:
```
    Media media = Media.CreateMedia();
    MFSampleVideoSource mfSampleSource = media.CreateMFSampleVideoSource();
    mfSampleSource.OnMFSampleVideoFrame += (s) => {
        Debug.WriteLine("MfSample received: " + s);
    };
```
Pointer to MFSample is passed to the application layer as `uint64` WinRT type. Callback should be executed in C++/CX environment and pointer value should be cast to `IMFSample*`. A reference to Wold Coordinate System can be set from Unity environment using `WorldManager.GetNativeISpatialCoordinateSystemPtr()` method. There is a sample from MixedRemoteViewCompositor:
https://github.com/Microsoft/MixedRealityCompanionKit/blob/master/MixedRemoteViewCompositor/Samples/LowLatencyMRC/Unity/Assets/AddOns/MixedRemoteViewCompositor/Scripts/MrvcCapture.cs#L92
Please let us know about success in implementing this solution and if anything is missing. The Nuget package with MFSampleVideoSource will be available soon.

**Comment by jamescadd** [comment]
Checking for any feedback on @morosev comment above for raw media object access.  Please let us know if this doesn't work for your scenario, otherwise we'll close the issue out in a few days.  Thanks!

**Comment by ghandmann** [comment]
Great work so far! But we struggle with building the WebRTC-Project a little bit.
Is there any ETA when these changes will be published in the WebRTC NuGet package?

**Comment by jamescadd** [comment]
@ghandmann Working on this and should have it done this week.  We'll also need to merge the Unity work into the main PeerConnection repo(s) to make things a bit more clean, but that may not happen until next week.

**Comment by jamescadd** [comment]
@ghandmann @Noemata This is now checked into master for PeerCC-Sample and the latest beta NuGet package includes the https://www.nuget.org/packages/WebRTC/1.62.1.1-Beta

**Comment by Fritzwald** [comment]
Hi all!
I am struggling to get access to the **CameraViewTransform**, the **CameraProjectionTransform**, the **CameraCoordinateSystem** and the actual video frame. I have access to the `IMFSample` pointer, but I'm not sure where to go from here.
I can call `GetBlob()` on the pointer, but it doesn't give me access to those parameters I need, at least I don't see how. 
To get the frame in theory I should be able to call `GetMediaBufferByIndex` to get an `IMFMediaBuffer`, which I can then `Lock()` to get the bytes, however that is returning a byte array with a length that can't contain a video frame from the Hololens camera.
I am trying to pass these values to a Unity app on Hololens that uses the values for Computer Vision purposes.

**Comment by jamescadd** [comment]
Hey, I know this isn't very prescriptive but you could take a look at 3DSTK for some pointers. Hoping we can make this easier in the next month or so. Let me know if this doesn't help.

**Comment by jamescadd** [comment]
@vladkol do you know the answer?  I had thought the comment from @morosev above was enough: https://github.com/webrtc-uwp/webrtc-uwp-sdk/issues/30#issuecomment-394528092

**Comment by hanzz0502** [comment]
I have got the **CameraViewTransform** and the **cameraProjectionTransform** successfully.But I can not get the **worldToCameraMatrix**,the microsoft document said that we can get the worldToCameraMatrix by these code:
_ComPtr<Windows::Perception::Spatial::ISpatialCoordinateSystem> spSpatialCoordinateSystem;
ComPtr<Windows::Foundation::IReference<Windows::Foundation::Numerics::Matrix4x4>> spTransformRef;
......
hr = pSample->GetUnknown(MFSampleExtension_Spatial_CameraCoordinateSystem, IID_PPV_ARGS(&spUnknown));
if (SUCCEEDED(hr))
{
.......
// Assume m_spCurrentCoordinateSystem is representing
            // world coordinate system application is using
            hr = m_spCurrentCoordinateSystem->TryGetTransformTo(spSpatialCoordinateSystem.Get(),
                                                                &spTransformRef);
            if (FAILED(hr))
            {
                return hr;
            }
            hr = spTransformRef->get_Value(&worldToCameraMatrix);
}_
But it report errors at the code:"ComPtr<Windows::Perception::Spatial::ISpatialCoordinateSystem> spSpatialCoordinateSystem;" when Compile .The error message like "This indirect addressing cannot be used on the type "Windows:: Perception:: Spatial:: ISpatial Coordinate System" ".So how can I get the spSpatialCoordinateSystem?

And is the m_spCurrentCoordinateSystem  in this code means the unity's SpatialCoordinateSystem?How can I afferent parameter to the variable from the UWP C# program ?

**Comment by hanzz0502** [comment]
>           First line of the code has a typo. It should be
> ComPtrWindows::Perception::Spatial::ISpatialCoordinateSystem spSpatialCoordinateSystem;

It's the problem of display,the code should be "ComPtr<<Windows::Perception::Spatial::ISpatialCoordinateSystem>> spSpatialCoordinateSystem;
" .The symbol '<'and '>' didn't display beacuseof some unknown reasons. I have Corrected the display problem In my question.
And I want to ask the 'm_spCurrentCoordinateSystem'  in this code means the unity's SpatialCoordinateSystem?How can I afferent parameter to the variable from the UWP C# program ?

**Comment by shenwooash** [comment]
Hi，All！
     When I calculate the correct worldToCamera matrix，I use  like this:
     `var cameraToWorldTransform = coordinateSystem.TryGetTransformTo(unityWorldCoordinateSystem);
`     And I can get the unityWorldCoordinateSystem by this:
     `var unityWorldCoordinateSystem =Marshal.GetObjectForIUnknown(WorldManager.GetNativeISpatialCoordinateSystemPtr()) as SpatialCoordinateSystem;
`     But I can not Get the `coordinateSystem` by: `Media.SetSpatialCoordinateSystem`. Because  `Media `has no `SetSpatialCoordinateSystem` method.
     How can i get the  SpatialCoordinateSystem of the frame?
