### ISSUE TITLE
There is a bug

### ISSUE THREAD

**Issue by jamescadd** [webrtc-uwp/webrtc-uwp-sdk#39]
@zhaofengjia2017 commented on [Mon Jan 15 2018](https://github.com/webrtc-uwp/webrtc/issues/2)

https://github.com/webrtc-uwp/webrtc/blob/6661764acc8a6d60d8d9e950c049cc67822bf902/modules/audio_processing/aec3/aec_state.cc#L224

I think here should get the index of max_element instead of the value.

Thanks!

**Comment by jamescadd** [comment]
@morosev does this look right?  curious if that bug came over from the original source.

**Comment by morosev** [comment]
There is the current file version in original sources:
https://chromium.googlesource.com/external/webrtc/+/master/modules/audio_processing/aec3/aec_state.cc
This line has been changed by Google, so it will be included in webrtc-uwp code after next merge.
