### ISSUE TITLE
OnIceConnectionChange state

### ISSUE THREAD

**Issue by yavuzcosar** [webrtc-uwp/webrtc-uwp-sdk#4]
Hi, i have an uwp app with webrtc and i want to connect wowza streaming server with PeerConnection. in this case app send offer and server return answer , then i set remotedescription and nothing is happen. app is running but streaming is not working. i checked PeerConnection Events and i found this; last OnIceConnectionChange is "Checking". But i think it should be "connected".

Thanks your help

**Comment by jamescadd** [comment]
Closing as unable to repro per mention by @vmancic in #22
