### ISSUE TITLE
UWP build failed: platform.winmd missing

### ISSUE THREAD

**Issue by HoloJackStones** [webrtc-uwp/webrtc-uwp-sdk#43]
I need a build for UWP (hololens) 
My steps:

- cloned the m62 branch (git clone -b releases/m62 --recursive https://github.com/webrtc-uwp/webrtc-uwp-sdk.git
- run bin\Prepare.bat (succesfully)
- Opened the webrtc\windows\solutions\webrtc.sln with VisualStudio 2015 (as indicated in the readme)
- Got an update required (One or more project are targeting WIndows 10 Fall Creators update platform etc.)
- Opened the webrtc\windows\solutions\webrtc.sln with Visual Studio 2017
- Selected Release / x86 configuration
- built the WebRtc.UWP.Native.Builder project 

The build fails with several errors like this: 
Error	C1107	could not find assembly 'platform.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable	WebRtc.UWP.Native.Builder	D:\GitHub\webrtc-uwp-sdk\webrtc\windows\projects\third_party\libyuv\source\convert_jpeg.cc	1	

Also tried to run the prebuild scripts from command prompt. 
Running "bin\buildWebRTC.bat Release x86 webrtc" fails.

I attached the output logs

[build.log](https://github.com/webrtc-uwp/webrtc-uwp-sdk/files/1865245/build.log)

[prepare.log](https://github.com/webrtc-uwp/webrtc-uwp-sdk/files/1865242/prepare.log)

Any idea?

**Comment by HoloJackStones** [comment]
The issue seems to be related to the VC Tools path.
I found the missing platform.winmd file in:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.13.26128\lib\x86\store\references

Tried to specify the path trough environment variable like LIB, LIBPATH, VCTOOLSINSTALLDIR. but none of them worked.

Finally, as a workaround, i manually copied platform.winmd in webrtc\xplatform\webrtc\out\winuwp_10_x86_debug folder and it worked.

**Comment by jamescadd** [comment]
Good catch, I've updated the readme to reflect the VS2017 requirement.  For the hard coded tool path I'd have to as @vmancic to clarify.  Can you check that you have the Windows SDK 14393 installed from here: https://developer.microsoft.com/en-us/windows/downloads/sdk-archive

**Comment by HoloJackStones** [comment]
I have installed the Windows SDK 10.0.16299.91

**Comment by jamescadd** [comment]
Ok that's probably the issue. Installing 14393 from the link above should resolve it, they can be installed side by side.

**Comment by HoloJackStones** [comment]
No they can't. If i try to install the 14393 it asks for uninstalling the other already present.

**Comment by jamescadd** [comment]
Oops, sorry about that. Been awhile since I setup a build machine but I'm sure that's correct. Uninstall and use 14393.

**Comment by jamescadd** [comment]
Have you been able to build the UWP bits?  Installing the proper SDK version should have resolved the last issue.
