### ISSUE TITLE
How to detect connection closed

### ISSUE THREAD

**Issue by HoloJackStones** [webrtc-uwp/webrtc-uwp-sdk#44]
Is there any way to detect when the peer connection terminate?
Actually i can only get this information through the signaller, but it is not a reliable method because the peer can loose the connection and can't send a notification to signaller.

The PeerConnection object doesn't expose a "ConnectionClosed" event on something similar.

**Comment by jamescadd** [comment]
Hello, the issue appears to be that we're missing the connectionState property and related events on the RTCPeerConnection WinRT API surface. We'll patch this in the next 2-3 weeks but for now signaling is your best bet (though it has issues as you noted).
________________________________

**Comment by HoloJackStones** [comment]
I found that the OnIceConnectionChange event of PeerConnection can do the job. 

```
_peerConnection.OnIceConnectionChange += _peerConnection_OnIceConnectionChange;

private void _peerConnection_OnIceConnectionChange(RTCPeerConnectionIceStateChangeEvent evt)
    {
      if (evt.State == RTCIceConnectionState.Disconnected)
      {
        // Peer disconnected
      }
      else if (evt.State == RTCIceConnectionState.Closed)
      {
        // Connection closed
      }
    }
```

**Comment by jamescadd** [comment]
Great, in that case we'll wait to update the WinRT wrapper until it makes sense for other APIs.
