### ISSUE TITLE
CRITICAL ERROR: Failed downloading gn.exe in prepare.bat on releases/m62 and on Mosa/20180320-peercc-unity

### ISSUE THREAD

**Issue by DanAndersen** [webrtc-uwp/webrtc-uwp-sdk#45]
I am needing to set up a dev environment for the new Mosa/20180320-peercc-unity branch that is being set up (my goal is a HoloLens-enabled WebRTC app that I can eventually get synchronized per-frame pose with, but for the moment I'd settle for being able to run the existing code successfully).

As described in https://github.com/Microsoft/WebRTC-universal-samples/issues/6 , I clone the repo as follows:

`git clone --recursive -b Mosa/20180320-peercc-unity https://github.com/ortclib/ortclib-sdk.git ortclib-sdk-m62-media-engine-video`

I've set up VS2017, I've ensured that line endings in the .bat files are correct, and I have the Debugging Tools for Windows installed along with the 14393 SDK.

When I run `bin\prepare.bat`, the script runs partway, waits for an extremely long time, and then times out and fails. It looks like gn.exe and clang-format.exe are not being downloaded correctly. Here is the output:

```
D:\holopose\webrtc-uwp-sdk-releases-m62>bin\prepare.bat
Running script with default parameters:
Target: all (Ortc and WebRtc)
Platform: all (x64, x86, arm and win32)
Log level: 2 (warning)

Running prepare script ...

Preparing webRTC development environment ...
Preparing development environment for ARM, x64, x86 and win32 platforms ...

Running WebRTC prepare script ...
=================================
Preparing WebRTC development environment for arm, x64, x86 and win32 platforms ...
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
0> Failed to fetch file gs://chromium-gn/ef6638b20ad334f943d29f985dbcecc86103ab9f for buildtools\win\gn.exe, skipping. [Err: INFO 0427 16:12:42.032000 util.py] Retrying request, attempt #4...
INFO 0427 16:12:54.969000 util.py] Retrying request, attempt #5...
INFO 0427 16:13:20.806000 util.py] Retrying request, attempt #6...
INFO 0427 16:13:52.807000 util.py] Retrying request, attempt #7...
INFO 0427 16:14:24.809000 util.py] Retrying request, attempt #8...
INFO 0427 16:14:56.811000 util.py] Retrying request, attempt #9...
INFO 0427 16:15:28.813000 util.py] Retrying request, attempt #10...
INFO 0427 16:16:00.814000 util.py] Retrying request, attempt #11...
INFO 0427 16:16:32.816000 util.py] Retrying request, attempt #12...
INFO 0427 16:17:04.817000 util.py] Retrying request, attempt #13...
INFO 0427 16:17:36.819000 util.py] Retrying request, attempt #14...
INFO 0427 16:18:08.821000 util.py] Retrying request, attempt #15...
INFO 0427 16:18:40.823000 util.py] Retrying request, attempt #16...
INFO 0427 16:19:12.825000 util.py] Retrying request, attempt #17...
INFO 0427 16:19:44.827000 util.py] Retrying request, attempt #18...
INFO 0427 16:20:16.829000 util.py] Retrying request, attempt #19...
INFO 0427 16:20:48.831000 util.py] Retrying request, attempt #20...
INFO 0427 16:21:20.833000 util.py] Retrying request, attempt #21...
INFO 0427 16:21:52.834000 util.py] Retrying request, attempt #22...
Failure: Unable to find the server at www.googleapis.com.
]
Failed to fetch file gs://chromium-gn/ef6638b20ad334f943d29f985dbcecc86103ab9f for buildtools\win\gn.exe. [Err: INFO 0427 16:12:42.032000 util.py] Retrying request, attempt #4...
INFO 0427 16:12:54.969000 util.py] Retrying request, attempt #5...
INFO 0427 16:13:20.806000 util.py] Retrying request, attempt #6...
INFO 0427 16:13:52.807000 util.py] Retrying request, attempt #7...
INFO 0427 16:14:24.809000 util.py] Retrying request, attempt #8...
INFO 0427 16:14:56.811000 util.py] Retrying request, attempt #9...
INFO 0427 16:15:28.813000 util.py] Retrying request, attempt #10...
INFO 0427 16:16:00.814000 util.py] Retrying request, attempt #11...
INFO 0427 16:16:32.816000 util.py] Retrying request, attempt #12...
INFO 0427 16:17:04.817000 util.py] Retrying request, attempt #13...
INFO 0427 16:17:36.819000 util.py] Retrying request, attempt #14...
INFO 0427 16:18:08.821000 util.py] Retrying request, attempt #15...
INFO 0427 16:18:40.823000 util.py] Retrying request, attempt #16...
INFO 0427 16:19:12.825000 util.py] Retrying request, attempt #17...
INFO 0427 16:19:44.827000 util.py] Retrying request, attempt #18...
INFO 0427 16:20:16.829000 util.py] Retrying request, attempt #19...
INFO 0427 16:20:48.831000 util.py] Retrying request, attempt #20...
INFO 0427 16:21:20.833000 util.py] Retrying request, attempt #21...
INFO 0427 16:21:52.834000 util.py] Retrying request, attempt #22...
Failure: Unable to find the server at www.googleapis.com.
]
Downloading 1 files took 604.613000 second(s)

CRITICAL ERROR: Failed downloading gn.exe

FAILURE:Preparing WebRTC development environment has failed.
=======   WebRTC prepare script summary   =======
=======   platform   =========   result   =======
            arm                 not run
            x64                 not run
            x86                 not run
            win32               not run
=================================================
```

*Note:* I am able to workaround this specific issue because I was able to run prepare.bat on the master branch of `webrtc-uwp-sdk`, get those EXE files, copy them into the corresponding directory in `ortclib-sdk-m62-media-engine-video` and then re-run `prepare.bat`. After doing that, the script is able to progress past that point.

However, I am curious as to what could be the cause of this, as it is still a usability issue with getting one's dev environment set up. My computer has no issue pinging www.googleapis.com.

**Comment by gjavi1** [comment]
I've also encountered problems running `bin\prepare.bat` but after installing the 16299 SDK my issues were gone.

**Comment by vmancic** [comment]
Please check how much free memory you have, and try again. Please use option -loglevel 4 with prepare.bat, in order to have more detailed log.

I managed to reproduce the issue "Failed downloading gn.exe", and it turned out that I did not have enough memory.  When I freed some memory, the issue did not happen again. This is relevant part of the log (using loglevel 4) that I received when the issue was reproduced:

Updating Clang to 310694-2...
Creating directory C:\Work\apr30-webrtc-uwp-m62\webrtc-uwp-sdk\webrtc\xplatform\webrtc\third_party\llvm-build
Downloading prebuilt clang
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Win/clang-310694-2.tgz ..Traceback (most recent call last):
  File "tools\clang\scripts\update.py", line 879, in <module>
    sys.exit(main())
  File "tools\clang\scripts\update.py", line 875, in main
    return UpdateClang(args)
  File "tools\clang\scripts\update.py", line 414, in UpdateClang
    DownloadAndUnpack(cds_full_url, LLVM_BUILD_DIR)
  File "tools\clang\scripts\update.py", line 138, in DownloadAndUnpack
    DownloadUrl(url, f)
  File "tools\clang\scripts\update.py", line 108, in DownloadUrl
    output_file.write(chunk)
IOError: [Errno 28] No space left on device
Created folder third_party\llvm
Path "third_party\llvm" already exists
Path "third_party\llvm-build" already exists
Clang already exists, skipping clang update...
0> Failed to fetch file gs://chromium-gn/ef6638b20ad334f943d29f985dbcecc86103ab9f for buildtools\win\gn.exe, skipping. [Err: Traceback (most recent call last):
  File "C:\Work\apr30-webrtc-uwp-m62\webrtc-uwp-sdk\webrtc\xplatform\depot_tools\gsutil.py", line 172, in <module>
    sys.exit(main())
  File "C:\Work\apr30-webrtc-uwp-m62\webrtc-uwp-sdk\webrtc\xplatform\depot_tools\gsutil.py", line 169, in main
    clean=args.clean)
  File "C:\Work\apr30-webrtc-uwp-m62\webrtc-uwp-sdk\webrtc\xplatform\depot_tools\gsutil.py", line 128, in run_gsutil
    gsutil_bin = ensure_gsutil(force_version, target, clean)
  File "C:\Work\apr30-webrtc-uwp-m62\webrtc-uwp-sdk\webrtc\xplatform\depot_tools\gsutil.py", line 112, in ensure_gsutil
    target_zip.extractall(download_dir)
  File "C:\Python27\lib\zipfile.py", line 1036, in extractall
    self.extract(zipinfo, path, pwd)
  File "C:\Python27\lib\zipfile.py", line 1024, in extract
    return self._extract_member(member, path, pwd)
  File "C:\Python27\lib\zipfile.py", line 1080, in _extract_member
    shutil.copyfileobj(source, target)
  File "C:\Python27\lib\shutil.py", line 52, in copyfileobj
    fdst.write(buf)
IOError: [Errno 28] No space left on device
]
Failed to fetch file gs://chromium-gn/ef6638b20ad334f943d29f985dbcecc86103ab9f for buildtools\win\gn.exe. [Err: Traceback (most recent call last):
  File "C:\Work\apr30-webrtc-uwp-m62\webrtc-uwp-sdk\webrtc\xplatform\depot_tools\gsutil.py", line 172, in <module>
    sys.exit(main())
  File "C:\Work\apr30-webrtc-uwp-m62\webrtc-uwp-sdk\webrtc\xplatform\depot_tools\gsutil.py", line 169, in main
    clean=args.clean)
  File "C:\Work\apr30-webrtc-uwp-m62\webrtc-uwp-sdk\webrtc\xplatform\depot_tools\gsutil.py", line 128, in run_gsutil
    gsutil_bin = ensure_gsutil(force_version, target, clean)
  File "C:\Work\apr30-webrtc-uwp-m62\webrtc-uwp-sdk\webrtc\xplatform\depot_tools\gsutil.py", line 112, in ensure_gsutil
    target_zip.extractall(download_dir)
  File "C:\Python27\lib\zipfile.py", line 1036, in extractall
    self.extract(zipinfo, path, pwd)
  File "C:\Python27\lib\zipfile.py", line 1024, in extract
    return self._extract_member(member, path, pwd)
  File "C:\Python27\lib\zipfile.py", line 1080, in _extract_member
    shutil.copyfileobj(source, target)
  File "C:\Python27\lib\shutil.py", line 52, in copyfileobj
    fdst.write(buf)
IOError: [Errno 28] No space left on device
]
Downloading 1 files took 14.948000 second(s)

CRITICAL ERROR: Failed downloading gn.exe

FAILURE:Preparing WebRTC development environment has failed.
=======   WebRTC prepare script summary   =======
=======   platform   =========   result   =======
            arm                 not run
            x64                 not run
            x86                 not run
            win32               not run
=================================================

**Comment by vmancic** [comment]
Thanks for the logs. I will look into this.

**Comment by vmancic** [comment]
@DanAndersen

You wrote this note: 
"Note: I am able to workaround this specific issue because I was able to run prepare.bat on the master branch of webrtc-uwp-sdk, get those EXE files, copy them into the corresponding directory in ortclib-sdk-m62-media-engine-video and then re-run prepare.bat. After doing that, the script is able to progress past that point."

It would be helpful for me to understand this correctly: are you able to run prepare.bat on the master branch the same time when prepare is failing on m62, or you run prepare.bat on master some time in the past and you just happen to have EXE files that you used for this workaround.

I am trying to understand whether this issue happens on m62 only, or on master branch too.

Thanks for you help.

**Comment by DanAndersen** [comment]
@vmancic 
Yes, the prepare.bat script in `webrtc-uwp-sdk/master` branch will successfully download gn.exe, but when running either the `webrtc-uwp-sdk/releases/m62` branch or the `ortclib-sdk/Mosa/20180320-peercc-unity` branch, the gn.exe download fails. I've re-run on each of these three branches today just to confirm. This means that the workaround I described is at least usable as of the time of this writing, and I didn't need to have some previously-downloaded EXE file to move forward.

Logs:
[2018-05-03_failed_download_in_ortclib-sdk-m62-media-engine-video.txt](https://github.com/webrtc-uwp/webrtc-uwp-sdk/files/1972655/2018-05-03_failed_download_in_ortclib-sdk-m62-media-engine-video.txt)
[2018-05-03_failed_download_in_webrtc-uwp-sdk-releases-m62.txt](https://github.com/webrtc-uwp/webrtc-uwp-sdk/files/1972656/2018-05-03_failed_download_in_webrtc-uwp-sdk-releases-m62.txt)
[2018-05-03_successful_download_in_master.txt](https://github.com/webrtc-uwp/webrtc-uwp-sdk/files/1972657/2018-05-03_successful_download_in_master.txt)

**Comment by vmancic** [comment]
Many thanks for prompt answer!

**Comment by vmancic** [comment]
@DanAndersen

Having that prepare works fine on master branch and does not work on m62, the root cause for this problem is most probably the version of Win SDK that you have installed. Glen already pointed this out. m62 supports 16299 or newer, while master branch is still fine with 14393.

**Comment by DanAndersen** [comment]
I do already have 16299 installed (I've been able to build UWP projects with both a target and minimum version of 16299), though.

**Comment by vmancic** [comment]
I have updated README file for webrtc-uwp-sdk branch releases/m62.

**Comment by vmancic** [comment]
@DanAndersen

Sorry, I see now that you already mentioned, in some of you previous posts, that you use 16299.

**Comment by vmancic** [comment]
This issue is reported as chromium bug here:
https://bugs.chromium.org/p/chromium/issues/detail?id=410031

And here, you can see how some people did workaround the problem:
https://github.com/jay0lee/GAM/issues/236

**Comment by DanAndersen** [comment]
@vmancic Thanks for the link to the workaround. I was able to get past this issue by editing my `c:\windows\system32\drivers\etc\hosts` file and adding the following line:

```
172.217.4.74 www.googleapis.com
```

where `172.217.4.74` was the result I found when running the command `ping www.googleapis.com`.

**Comment by IcyCheetah358** [comment]
I had the same problem .... the prepare bat would quickly fail. I noticed it the script tried to use company net shared drive(K:) that was only visible while in official wifi to download files into. I was in another wifi so my access to the network drive was blocked and this gave me this "CRITICAL ERROR: Failed downloading gn.exe" error.

`I:\repos\webrtc-uwp-sdk>bin\prepare.bat -loglevel 4

Running prepare script ...

Running script parameters:
Target: all
Platform: all
Cpu: all
Log level: 4
Preparing webRTC development environment ...
Preparing development environment for WinUWP and Win32 platforms ...
Preparing development environment for arm, x86, and x64 cpus ...
Preparing development environment for debug and release configurations ...
depotToolsPathCheck entered...
Python is present.
Python 2.7.11
Currently installed Python version: 2.7.11
Currently installed Python 2.7 subversion: 11
Installing the latest Python 2.7 version
Installing Python ...
Python is successfully installed
Deleting downloaded file.
Python is added to the path.
Pip and pywin32 setup...
Pip is present.
Updating pip ...
Requirement already up-to-date: pip in i:\python27\lib\site-packages (18.1)
Installing pywin32...
Requirement already satisfied: pywin32 in i:\python27\lib\site-packages (224)
webrtc\xplatform\webrtc\third_party\ortc\ folder already exists
webrtc\xplatform\webrtc\third_party\idl folder already exists
        1 file(s) copied.
COPY webrtc\xplatform\templates\gn\idl_BUILD.gn webrtc\xplatform\webrtc\third_party\idl\BUILD.gn
Copied

Running WebRTC prepare script ...
=================================
Preparing WebRTC development environment for WinUWP and win32 platforms ...
Preparing WebRTC development environment for arm, x86, x64 cpus ...
Preparing WebRTC development environment for debug and release configurations ...
Executing prepareWebRTC function
Pushed webrtc\xplatform\webrtc path
Executing generateChromiumFolders function
chromium\src folder already exists
chromium\src\tools folder already exists
chromium\src\third_party folder already exists
chromium\src\third_party\winsdk_samples folder already exists
chromium\src\third_party\libjingle\source\talk\media\testdata\ folder already exists
third_party folder already exists
tools folder already exists
Executing makeJunctionLinks function
Path "buildtools" already exists
Path "build" already exists
Path "chromium\src\third_party\jsoncpp" already exists
Path "chromium\src\third_party\jsoncpp\source" already exists
Path "chromium\src\tools\protoc_wrapper" already exists
Path "chromium\src\third_party\protobuf" already exists
Path "chromium\src\third_party\yasm" already exists
Path "chromium\src\third_party\opus" already exists
Path "chromium\src\third_party\boringssl" already exists
Path "chromium\src\third_party\usrsctp" already exists
Path "chromium\src\third_party\libvpx" already exists
Path "chromium\src\third_party\libvpx\source\libvpx" already exists
Path "chromium\src\testing" already exists
Path "testing" already exists
Path "base" already exists
Path "tools\protoc_wrapper" already exists
Path "third_party\yasm" already exists
Path "third_party\yasm\binaries" already exists
Path "third_party\yasm\source\patched-yasm" already exists
Path "third_party\opus" already exists
Path "third_party\opus\src" already exists
Path "third_party\boringssl" already exists
Path "third_party\boringssl\src" already exists
Path "third_party\usrsctp" already exists
Path "third_party\usrsctp\usrsctplib" already exists
Path "third_party\protobuf" already exists
Path "chromium\src\third_party\expat" already exists
Path "third_party\expat" already exists
Path "chromium\src\third_party\googletest" already exists
Path "third_party\googletest" already exists
Path "third_party\googletest\src" already exists
Path "third_party\libsrtp" already exists
Path "third_party\libvpx" already exists
Path "third_party\libyuv" already exists
Path "third_party\openmax_dl" already exists
Path "third_party\libjpeg_turbo" already exists
Path "third_party\jsoncpp" already exists
Path "third_party\winuwp_compat" already exists
Path "third_party\winuwp_h264" already exists
Path "third_party\gflags" already exists
Path "third_party\gflags\src" already exists
Path "third_party\winsdk_samples" already exists
Path "tools\gyp" already exists
Path "tools\clang" already exists
Path "third_party\harfbuzz-ng" already exists
Path "third_party\freetype" already exists
Path "third_party\zlib" already exists
Path "third_party\libpng" already exists
Path "third_party\icu" already exists
third_party\idl folder already exists
Path "third_party\idl\cryptopp" already exists
Path "third_party\idl\zsLib" already exists
Path "third_party\idl\zsLib-eventing" already exists
Path "sdk\windows" already exists
Path "sdk\idl" already exists
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
Running clang update ...
Clang already exists, skipping clang update...
0> Failed to fetch file gs://chromium-gn/e93779cab57d5f36100faa4d88524a1e33be7b0f for buildtools\win\gn.exe, skipping. [Err: [E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242] original error: mkdir K:: The network path was not found.
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242]
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242] goroutine 1:
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242] #0 go.chromium.org/luci/common/system/filesystem/filesystem.go:32 - filesystem.MakeDirs()
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242] #1 go.chromium.org/luci/vpython/venv/config.go:200 - venv.(*Config).makeEnv()
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242]   reason: could not create environment root: K:\.vpython-root
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242]
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242] #2 go.chromium.org/luci/vpython/venv/venv.go:163 - venv.With()
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242] #3 go.chromium.org/luci/vpython/run.go:63 - vpython.Run()
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242] #4 go.chromium.org/luci/vpython/application/application.go:318 - application.(*application).mainImpl()
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242] #5 go.chromium.org/luci/vpython/application/application.go:402 - application.(*Config).Main.func1()
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242] #6 go.chromium.org/luci/vpython/application/support.go:47 - application.run()
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242] #7 go.chromium.org/luci/vpython/application/application.go:401 - application.(*Config).Main()
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242] #8 vpython/main.go:92 - main.mainImpl()
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242] #9 vpython/main.go:98 - main.main()
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242] #10 runtime/proc.go:195 - runtime.main()
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242] #11 runtime/asm_amd64.s:2337 - runtime.goexit()
]
Failed to fetch file gs://chromium-gn/e93779cab57d5f36100faa4d88524a1e33be7b0f for buildtools\win\gn.exe. [Err: [E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242] original error: mkdir K:: The network path was not found.
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242]
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242] goroutine 1:
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242] #0 go.chromium.org/luci/common/system/filesystem/filesystem.go:32 - filesystem.MakeDirs()
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242] #1 go.chromium.org/luci/vpython/venv/config.go:200 - venv.(*Config).makeEnv()
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242]   reason: could not create environment root: K:\.vpython-root
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242]
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242] #2 go.chromium.org/luci/vpython/venv/venv.go:163 - venv.With()
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242] #3 go.chromium.org/luci/vpython/run.go:63 - vpython.Run()
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242] #4 go.chromium.org/luci/vpython/application/application.go:318 - application.(*application).mainImpl()
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242] #5 go.chromium.org/luci/vpython/application/application.go:402 - application.(*Config).Main.func1()
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242] #6 go.chromium.org/luci/vpython/application/support.go:47 - application.run()
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242] #7 go.chromium.org/luci/vpython/application/application.go:401 - application.(*Config).Main()
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242] #8 vpython/main.go:92 - main.mainImpl()
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242] #9 vpython/main.go:98 - main.main()
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242] #10 runtime/proc.go:195 - runtime.main()
[E2018-10-09T09:33:07.746861+03:00 20500 0 annotate.go:242] #11 runtime/asm_amd64.s:2337 - runtime.goexit()
]
Downloading 1 files took 3.894000 second(s)

CRITICAL ERROR: Failed downloading gn.exe

FAILURE:Preparing WebRTC development environment has failed.
=======   WebRTC prepare script summary   =======
=======   platform   =========   cpu   =========   result   =======
          winuwp                 arm               not run
          winuwp                 x86               not run
          winuwp                 x64               not run
          win32                  x86               not run
          win32                  x64               not run
===================================================================


I:\repos\webrtc-uwp-sdk>`

**Comment by jLynx** [comment]
@DanAndersen I am having the same issue, would you be able to upload gn.exe?

**Comment by DanAndersen** [comment]
> @DanAndersen I am having the same issue, would you be able to upload gn.exe?

Sorry, I currently don't have access to the dev machine I was using for that project (away from grad school). Would one of the developers be able to help?

**Comment by gjavi1** [comment]
I can upload the file after an hour

**Comment by gjavi1** [comment]
@jLynx apologies for the delay you could download the file [here](https://goo.gl/4vdLPE). I tried to run  `bin\prepare.bat ` and I got the error:

```
Exception: dbghelp.dll not found in "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\dbghelp.dll"
You must install the "Debugging Tools for Windows" feature from the Windows 10 SDK.
``` 

After installing the latest Windows 10 SDK (10.0.17763.0), I got everything working and was able to download gn.exe

<img width="268" alt="capture" src="https://user-images.githubusercontent.com/8813958/46866039-1ab5b400-ce63-11e8-8607-c995417a93bf.PNG">

**Comment by jLynx** [comment]
Thank you @gjavi1!
