### ISSUE TITLE
ARM support (old version source code)

### ISSUE THREAD

**Issue by fdarie** [webrtc-uwp/webrtc-uwp-sdk#46]
Hi,
Is there any progress on ARM integration? 
I've modified the latest version code to enable screen sharing. It works for x86/x64 but ARM support is required.
Is there any way to pull the source code of an old version that compiles for ARM (not Nuget package) ?

Thank you

**Comment by SergioOpenPeer** [comment]
ARM is present in M49 version. Unfortunately there is no branch with that version on this repo, but you can get it from this repo https://github.com/ortclib/ortclib-sdk.git branch releases/m49 

ortclib-sdk repo beside webrtc contains also ortc version, but you can use webrtc the same way it is used in this repo

**Comment by jamescadd** [comment]
And yes there has been progress but it's not ready for use yet. This is under active development.
________________________________

**Comment by fdarie** [comment]
Thank you! That should be enough for me
