### ISSUE TITLE
Will there be Xamarin Native Libraries with desktop_capture @cross platform with samples

### ISSUE THREAD

**Issue by Raj123456788** [webrtc-uwp/webrtc-uwp-sdk#48]
Hey Folks,
               Just stumbled upon ur github repo. It has been ages that we are trying to find a webrtc desktop_capture module for crossplatform with a good API documentation?

**Comment by jamescadd** [comment]
Hello, thanks for reaching out.  What you're asking for is likely a ways out - we need to both implement screen capture as well as work on video for the Xamarin platforms.  We will keep this on the backlog and increase priority if more people request it.  Which platforms are most important to you?

**Comment by EbramTawfik** [comment]
1- Android
2- macOS
3- iOS

**Comment by Raj123456788** [comment]
1- Android
2- macOS
3- iOS

**Comment by jamescadd** [comment]
Closing this for now as Xamarin has moved down our priority list.  If/when we revisit the issue I'll open it.
