### ISSUE TITLE
Githubs Browser "Download Zip" function results in empty zip

### ISSUE THREAD

**Issue by Senador** [webrtc-uwp/webrtc-uwp-sdk#5]
I tried download this repository

https://github.com/webrtc-uwp/webrtc-uwp-sdk

by using "Download ZIP". It downloads a zip but it has just empty folders in it. 

system:
Windows 10
Browser:
Chrome

**Comment by robin-raymond** [comment]
It's not a single repo. This repo is a repo of repos. Each directory contains a sub-repo within and download of zip can't download sub repos.
