### ISSUE TITLE
"Failed to load 'Org.WebRtc.dll', expected x86 architecture, but was Unknown architecture. You must recompile your plugin for x86 architecture."

### ISSUE THREAD

**Issue by DanAndersen** [webrtc-uwp/webrtc-uwp-sdk#50]
Hello again,
I am working from the latest commits on the "Mosa/20180320-peercc-unity" branch of ortclib-sdk, and am encountering new errors when attempting to deploy a Unity app with the Org.WebRtc.dll that is built from source.

I am able to open up WebRtc.sln and compile the `Org.WebRtc.Uwp` project (as well as `WebRtc.Stats.Observer` and `WebRtc.UWP.Native.Builder`) with no reported errors. I copy over the generated files `Org.WebRtc.dll`, `Org.WebRtc.pdb`, and `Org.WebRtc.winmd` into the Plugins/WSA/x86 directory of my Unity application (I also have in that directory some other DLLs like `MediaEngineUWP.dll` and `WebRtcScheme.dll` from the PeerCCUnity project but I don't think it's related here).

I have a test Unity script that references `Org.WebRtc` in its `Start()` function:
```
void Start()
    {
#if !UNITY_EDITOR
        Debug.Log("doing early test");
        Org.WebRtc.Media fooMedia = Org.WebRtc.Media.CreateMedia();
        Debug.Log("fooMedia: " + fooMedia);
#endif
[...]
}
```

When I try to use the newly generated Org.WebRtc.dll plugin, I get the following error when deploying (to the HoloLens):

```
[...]
  Loading MediaEngineUWP.dll
  Loading WebRtcScheme.dll
  Loading MicStreamSelector.dll
  Loading GpuTiming.dll
  Loading SharingClient.dll
  Loading Org.WebRtc.dll
Failed to load 'Org.WebRtc.dll', expected x86 architecture, but was Unknown architecture. You must recompile your plugin for x86 architecture.
  Loading SpatialUnderstanding.dll
[...]
```
(to confirm, yes I am building Org.WebRtc.Uwp in VS2017 as x86.)

This results in the following error when my Start() function attempts to reference Org.WebRtc:

```
FileNotFoundException: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
   at Org.WebRtc.Media.CreateMedia()
   at ControlScript.Start()
   at ControlScript.$Invoke19(Int64 instance, Int64* args)
   at UnityEngine.Internal.$MethodUtility.InvokeMethod(Int64 instance, Int64* args, IntPtr method) 
```

I have an earlier copy of the Org.WebRtc DLL (generated locally on May 4th), and when I put those plugin files into my Unity project, everything loads without any issue. I have not yet gone through commit-by-commit to see if there was a specific change that caused this issue, but I wanted to see if there was anything you might recognize.

This issue happens when building both Debug and Release versions of Org.WebRtc.

**Comment by jamescadd** [comment]
@DanAndersen Are you able to use the Dll with the provided WebRtcUnityD3D.sln solution?  This reminds me of an older bug where compiling for x64 then switching to X86 would fail to properly rebuild the solution.  Is this from a clean clone or had you previously built for other platforms?  I cloned and built that branch late yesterday and it worked fine and deployed/ran on HoloLens.

**Comment by DanAndersen** [comment]
@jamescadd I have just cloned a new instance of the entire repo and rebuilt the projects in WebRtcUnityD3D.sln, running the provided PeerConnectionClientUnity HoloLens project. The only build configuration I did on this new instance was x86. The same error appears:

```
FileNotFoundException: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
   at Org.WebRtc.Media.CreateMedia()
   at PeerConnectionClient.Signalling.Conductor..ctor()
   at PeerConnectionClient.Signalling.Conductor.get_Instance()
   at ControlScript.Start()
   at ControlScript.$Invoke21(Int64 instance, Int64* args)
   at UnityEngine.Internal.$MethodUtility.InvokeMethod(Int64 instance, Int64* args, IntPtr method) 
```

**Comment by DanAndersen** [comment]
To give some additional information:

- The error appears (Org.WebRtc is not found) *only* when deploying to the HoloLens. If I build a (non-mixed-reality) version of the same Unity app and deploy it as a UWP Unity app on my desktop, the error does not appear (I can call methods in Org.WebRtc).
- The version of my HoloLens is 10.0.17134.1011.
- In Unity Build Settings, I have set the SDK to both 10.0.17134.0 and 10.0.16299.0. The same issue arises.

Please let me know if there is any other information I can provide that can help diagnose this issue. My project requires that I be able to edit the source in Org.WebRtc (I am trying to add the synchronized pose-as-metadata linked in another issue), but at this rate I would at least like to be able to build the existing source of Org.WebRtc from the repo and be able to use that on the HoloLens.

**Comment by jamescadd** [comment]
We're looking at this, trying a fresh clone now.

**Comment by jamescadd** [comment]
I just did a fresh clone, build and run of the Unity app and it ran on HoloLens (though I haven't tried connecting to a server or peers).  My HL version is 10.0.17134.1 so it's a bit earlier than yours though I don't expect that would cause the issue.  That said I did nothing in Unity, just used the off the shelf solution.  I'm using Unity 2017.4.0.f1, maybe that's the difference?

**Comment by DanAndersen** [comment]
I'm also using Unity 2017.4.0.f1. (also, just to clarify, my Unity application also will start up on the HoloLens but all function calls that involve Org.WebRtc will throw the above exception, so attempting to connect to a server definitely would trigger the exception in the debug logs).

Thanks for looking into this, and I am continuing to search for a solution to my issue. I'll let you know if I make any progress.

Would it be helpful if I provided any of the output from my Org.WebRtc library? If you are able to replicate the issue when replacing your DLL with mine, there could be a comparison in the DLL first-order dependencies that could give a hint as to what is happening.

**Comment by DanAndersen** [comment]
Update: I was able to successfully build the Unity project in an earlier commit ( https://github.com/ortclib/ortclib-sdk/commit/65746266794d2fd88a246ef89d69735b45976b29 ) and I was able to deploy it onto the HoloLens (emulator) and verify that I can call Org.Webrtc.Media.CreateMedia() without an exception (the PeerConnectionClientUnity app crashes on startup in the Emulator anyway but that's just because it can't access a camera/mic, no issue there; my test of CreateMedia() was before that point). 

However, I found that I needed to make sure that all traces of the 17134 SDK were scrubbed off my machine. This means that I had to downgrade my release of VS2017 from 15.7 (I'm using 15.4.5 which can be found at https://docs.microsoft.com/en-us/visualstudio/productinfo/installing-an-earlier-release-of-vs2017 ). This is because, starting with 15.7, the 17134 SDK is used by default and you can't uninstall 17134 without removing other vital Visual Studio components. 

My methodology was:
```
git clone --recursive -b Mosa/20180320-peercc-unity https://github.com/ortclib/ortclib-sdk.git mosa_rollback
cd mosa_rollback
git checkout 65746266794d2fd88a246ef89d69735b45976b29
# change the submodules to what they were at the time of that commit
git submodule update --recursive
bin\prepare.bat -loglevel 4
```
Then open up WebRtcUnityD3D.sln and build PeerConnectionClientUnity.

With this, I am able to be back where I started before the latest 17134-related commits apparently make a valid build for HoloLens not functional.

**Comment by morosev** [comment]
The problem has been fixed. No need to use previous version of VS and SDK. It works fine with VS 2017 15.7.2 and SDK 17134.

**Comment by djee-ms** [comment]
Not sure what was fixed (@morosev can you expand on that please?) but the error message in the title ("expected xxx architecture") always appears for me in Unity, and everything works fine anyway. I assume that this message is not related with the current issue, but rather Unity trying to automatically load some DLL as a Unity plugin (_e.g._ a custom native renderer) and failing, or something like that. I have always seen that error message since I started using WebRTC with Unity.

**Comment by morosev** [comment]
I will check the issue. Strange, it doesn't break anything.
