### ISSUE TITLE
Video output resolution

### ISSUE THREAD

**Issue by HoloJackStones** [webrtc-uwp/webrtc-uwp-sdk#51]
We are using the library in a remote assistance based on hololens and mixed reality holograms.
The application works good using wifi connecitons but sometimes the customers need to use mobile hotspots with lower bandwidth.
Is there any way to reduce the resolutions of the video streaming sent by hololens?
The lower available hololens camera resolution is 896x504  but it's still too high.

I'm looking for a way to scale the captured frames before sending through the webrc protocol.

**Comment by morosev** [comment]
@HoloJackStones You cannot change the frame resolution from application level. But you can customize video capturing module inside webrtc library to achieve this.
Take a look to the following method: https://github.com/webrtc-uwp/webrtc/blob/Mosa/20180320-peercc-unity/webrtc/modules/video_capture/windows/video_capture_winuwp.cc#L487
The video frame content could be resized there before OnIncomingFrame() method has been called. You can use utility library libyuv which is part of webrtc package. libyuv contains various methods for image transform using platform optimized vector instructions.

**Comment by HoloJackStones** [comment]
Thanks @morosev. It would be useful to expose the frame resolution selection from application level. Developer could change it dinamically according to the connection health stats.

**Comment by morosev** [comment]
Yes, it might be added as a new feature if camera doesn't support low resolutions, as it is case on HoloLens. But on the other hand, there is no need to do any control in application layer related to adapting to network conditions. WebRTC has very powerful congestion control engine and it already lowers the video resolution internally if network throughput is poor or if remote side cannot process all received data due to low CPU/GPU capabilities. @HoloJackStones 
More about GCC:
https://www.ietf.org/archive/id/draft-ietf-rmcat-gcc-02.txt
https://ieeexplore.ieee.org/document/6691458/

**Comment by HoloJackStones** [comment]
Yes, teorically you're right. But during our field tests we are encountering serious issues related to network performance between hololens and desktop. Now we are going to debug and log the resolution of frames received on desktop side to detect if resolution is really adapted.

**Comment by HoloJackStones** [comment]
We did some test with a 3g hotspot showing the size of received frame on desktop side. The resolution has never changed. The streaming freeze in some cases, but no resolution adapting has been registered.

**Comment by HoloJackStones** [comment]
@morosev can you give some hints on how to scale the frame? I'm not so skilled on c++ code.

**Comment by HoloJackStones** [comment]
Please take a look at this code. I'm trying to scale the frame:

```
void CaptureDevice::ScaleFrame(uint8_t* src_video_frame, uint8_t* dst_video_frame,
                               size_t& src_frame_length,
                               size_t& dst_frame_length,
                               int32_t& dst_width,
                               int32_t& dst_height) {

  if (frame_info_.videoType == VideoType::kYUY2) {
    uint8_t* src_video_y = src_video_frame;
    
    uint8_t* src_video_u = src_video_y + (frame_info_.width * frame_info_.height)*2;
    uint8_t* src_video_v = src_video_u + (frame_info_.width * frame_info_.height) / 2;

    int src_stride_y = frame_info_.width*2;
    int src_stride_uv = (frame_info_.width + 1) / 4;

    uint8_t* dst_video_y = dst_video_frame;
    uint8_t* dst_video_u = dst_video_y + (dst_width * dst_height)*2;
    uint8_t* dst_video_v = dst_video_u + (dst_width * dst_height) / 4;

    int dst_stride_y = dst_width*2;
    int dst_stride_uv = (dst_width + 1) / 4;

    libyuv::I420Scale(src_video_y, src_stride_y, src_video_u, src_stride_uv,
                      src_video_v, src_stride_uv, frame_info_.width,
                      frame_info_.height, dst_video_y, dst_stride_y,
                      dst_video_u, dst_stride_uv, dst_video_v, dst_stride_uv,
                      dst_width, dst_height, libyuv::kFilterNone);


  } 
}
```

**Comment by morosev** [comment]
Sure @HoloJackStones. That is just the correct way for doing the scaling. The underneath code will do the scaling procedure on CPU in the platform optimized way. Just be careful about video formats which are used and the positioning of the color matrices in the memory. The Internal WebRTC format is I420, so maybe the code above will not work if the incoming format is YUY2. Better do the scaling on I420 video frames.
Sorry, I'm currently occupied by other tasks, but will be responsive for any help here.

**Comment by HoloJackStones** [comment]
@morosev, i debugged the running application and the frames comes in YUY2 format. How can do the scaling on i420 video frames?

**Comment by morosev** [comment]
OK. There are two options. You can either convert frame data to I420 before the frame is passed to webrtc internal capturing engine or you can do the scaling in webrtc internal code after the frame is converted to I420, native webrtc format.
1) Call ConvertToI420() right after the following line https://github.com/webrtc-uwp/webrtc/blob/Mosa/20180320-peercc-unity/webrtc/modules/video_capture/windows/video_capture_winuwp.cc#L521. After conversion do the scaling and change width, height and VideoType in frame_info_ variable.
2) You can do scaling in file video_capture_impl.cc. After the line https://github.com/webrtc-uwp/webrtc/blob/Mosa/20180320-peercc-unity/webrtc/modules/video_capture/video_capture_impl.cc#L176 just perform the scaling (libyuv::I420Scale()).

**Comment by HoloJackStones** [comment]
Perfect! The second option worked like a charm.

Now i'll work on exposing the feature at application level.
Thanks al lot @morosev
