### ISSUE TITLE
Screen capture support ?

### ISSUE THREAD

**Issue by Airborne76** [webrtc-uwp/webrtc-uwp-sdk#54]
In version 1803, Windows.Graphics.Capture namespace provides APIs to capture screen [Windows.Graphics.Capture namespace provides APIs](url). Do you have plan for supporting screen capture ?

**Comment by jamescadd** [comment]
Yes we do plan to support screen capture using the latest APIs as we want to keep parity with other platforms in the Google codebase.  Please follow #47 for updates but note this is not on the immediate roadmap so its at least a few months out though demand appears to be growing.

Duplicate #47

**Comment by jamescadd** [comment]
duplicate of #47
