### ISSUE TITLE
prepare.bat failed

### ISSUE THREAD

**Issue by Qualcuno** [webrtc-uwp/webrtc-uwp-sdk#55]
In the past i already done this step with success. Today i pulled down the repository from git with recursive. All ok, but when i try to run prepare.bat this error appear

> .
> .
> .
> Preparing WebRTC development environment for arm, x64, x86 and win32 platforms ...
> CRITICAL ERROR: WebRTC invalid folder structure. ..\chromium-pruned\build does not exist
> FAILURE:Preparing WebRTC development environment has failed.
> .
> .
> .

i see that the prepare.bat was modified 23h ago.

**Comment by jamescadd** [comment]
This should be fixed now - give it another try.

**Comment by Qualcuno** [comment]
Ok, problem solveld. Thanks
