### ISSUE TITLE
Check for Windows SDK based on Windows Build breaks for creator's update

### ISSUE THREAD

**Issue by tylergibson** [webrtc-uwp/webrtc-uwp-sdk#6]
In prepareWebRtc.bat, the over-ride function breaks the build for anyone running creator's update (or any build after 10.0.14393).  WebRTC doesn't support WindowsSDK's beyond this, nor can it build properly in VS2017, both of which are results of any Windows build after 14393.  I had to patch this with a static version definition to unbreak builds.  Why is this needed when the script you're patching msvs.py already does a proper check for the most recent installed Windows_SDK?

```
:updateSDKVersion

FOR /f "tokens=4-7 delims=[.] " %%i IN ('ver') DO (IF %%i==Version (SET v=%%j.%%k.%%l) ELSE (SET v=%%i.%%j.%%k))

IF NOT "!v!"=="" (
	CALL:print %warning% "!v! SDK version will be used"
	SET SDKVersionString=%stringToUpdateWithSDKVersion:10.0.10240=!v!%
	%powershell_path% -ExecutionPolicy ByPass -File bin\TextReplaceInFile.ps1 %pythonFilePathToUpdateSDKVersion% "%stringToUpdateWithSDKVersion%" "!SDKVersionString!" %pythonFilePathToUpdateSDKVersion%
	IF ERRORLEVEL 1 CALL:error 0 "Failed to set newer SDK version"
)

GOTO:EOF
```

**Comment by SergioOpenPeer** [comment]
That issue is already fixed on most of branches. If it is not the case for branch on which you are working please let me know. It will use the latest installed SDK that is not Creator Update.

**Comment by tylergibson** [comment]
Thanks Sergio, I was working from Master, which seemed to exhibit the issue.

**Comment by SergioOpenPeer** [comment]
Master branch is fixed as well
