### ISSUE TITLE
CRITICAL ERROR: COULD NOT CREATE SYMBOLIC LINK TO chromium\src\third_party\jsoncpp\source FROM ..\jsoncpp

### ISSUE THREAD

**Issue by sammytran90** [webrtc-uwp/webrtc-uwp-sdk#62]
Hi,
I followed the instruction but meet this error after running: bin\prepare.bat:

Executing prepareWebRTC function
Pushed webrtc\xplatform\webrtc path
Executing generateChromiumFolders function
chromium\src folder already exists
chromium\src\tools folder already exists
chromium\src\third_party folder already exists
chromium\src\third_party\winsdk_samples folder already exists
chromium\src\third_party\libjingle\source\talk\media\testdata\ folder already exists
third_party folder already exists
tools folder already exists
Executing makeJunctionLinks function
Path "buildtools" already exists
Path "build" already exists
Path "chromium\src\third_party\jsoncpp" already exists
In
The system cannot find the path specified.

CRITICAL ERROR: COULD NOT CREATE SYMBOLIC LINK TO chromium\src\third_party\jsoncpp\source FROM ..\jsoncpp

FAILURE:Preparing WebRTC development environment has failed.
=======   WebRTC prepare script summary   =======
=======   platform   =========   result   =======
            arm                 not run
            x64                 not run
            x86                 not run
            win32               not run
=================================================

The system cannot find the path specified.
Path "chromium\src\third_party\jsoncpp\source" already exists

CRITICAL ERROR: WebRTC invalid folder structure. ..\chromium\tools\protoc_wrapper does not exist

FAILURE:Preparing WebRTC development environment has failed.
=======   WebRTC prepare script summary   =======
=======   platform   =========   result   =======
            arm                 not run
            x64                 not run
            x86                 not run
            win32               not run
=================================================

I don't really know what happens here, can anyone give me an idea?
Would be very appreciated.

**Comment by jamescadd** [comment]
Could you let us know which branch you're working on?

**Comment by vmancic** [comment]
And also, please, provide full log (when running prepare.bat script, option: -loglevel 4).

**Comment by sammytran90** [comment]
Hi, I solved the issue.I downloaded the .zip file and it didn't include other projects.
