### ISSUE TITLE
CreateRawVideoSource crash

### ISSUE THREAD

**Issue by HoloJackStones** [webrtc-uwp/webrtc-uwp-sdk#7]
My UWP sample app crashes few seconds after connection has been established and remotestream has been aded.
It happens only if i attach the OnRawVideoFrame on a RawVideoSource.
The eventhandler do nothing.
if i don't attach the eventhandler, all works as expected. 

```
 private void Conductor_OnAddRemoteStream(MediaStreamEvent evt)
    {
      _peerVideoTrack = evt.Stream.GetVideoTracks().FirstOrDefault();
      if (_peerVideoTrack != null)
      {
        rawSource = media.CreateRawVideoSource(_peerVideoTrack);

        if (OnFrameUpdate != null)
        {          
          rawSource.OnRawVideoFrame += RawSource_OnRawVideoFrame;
        }

```
```
private void RawSource_OnRawVideoFrame(uint width, uint height, byte[] yplane, uint ystripe, byte[] uplane, uint ustripe, byte[] vplane, uint vstripe)
    {
    }

```

I need to grab received frames and i suppose the only way is using the RawVideoSource.

**Comment by morosev** [comment]
Hi @NinoStella,
One question. Which codec are you using - H.264 or VP8/9? CreateRawVideoSource() method works with VP8/9 only. Also, the buffer is safe to be used only during the call to event. So, it is better to copy the data to another memory structure in event handler method.

**Comment by NinoStella** [comment]
2017-06-15 21:09 GMT+02:00 Vladimir Morosev <notifications@github.com>:

> Hi @NinoStella <https://github.com/ninostella>,
> One question. Which codec are you using - H.264 or VP8/9?
> CreateRawVideoSource() method works with VP8/9 only.
>

I know that. I tried with VP8 and VP9.


> Also, the buffer is safe to be used only during the call to event. So, it
> is better to copy the data to another memory structure in event handler
> method.
>
Thanks for answering.
I'm not using the buffer yet. I just attached the event handler and the
application crashes.
I'm also tried on the PeerCC sample. Same behavior. As soos as the event is
attached the crash happens.
It's really easy to reproduce the issue using two instance of PeerCC (on
different machine of course).

**Comment by morosev** [comment]
OK @NinoStella. I will try to reproduce to problem. Just tell me, please, on which branch are you working on and will try the method call there. There is one more thing. It is not supposed to use other Video Sources. You cannot render remote video to the screen while you use Raw Video Source.

**Comment by NinoStella** [comment]
2017-06-15 23:16 GMT+02:00 Vladimir Morosev <notifications@github.com>:

> OK @NinoStella <https://github.com/ninostella>. I will try to reproduce
> to problem. Just tell me, please, on which branch are you working on and
> will try the method call there.
>

i recursevely cloned the webrtc-uwp-sdk


> There is one more thing. It is not supposed to use other Video Sources.
> You cannot render remote video to the screen while you use Raw Video Source.
>

i'm quite sure i tested the issue in both cases: with and without rendering
the video source on a media element. I'll check again.
My final purpose is using this code in a unity 3d project.
I already written the code for converting the raw buffer to a unity RGB
texture and succesfully tested with local video source.

**Comment by NinoStella** [comment]
I commented out all PeerVideo MediaStreamSource assignment (in Conductor_OnAddRemoteStream and PeerVideo_MediaFailed methods). 
The application works, of course no remote video is displayed. 
Then i tryed creating a RawVideoSource in the Conductor_OnAddRemoteStream method. In the exact instant other peer show the first frame, the local one crashes.

**Comment by r-b-us** [comment]
Hello @morosev ,
Regarding getting access to raw frames using H.264, how do you convert the native handle into a buffer containing the data? NativeHandleBuffer doesn't implement anything helpful at the moment - I would like to add something in my version so that RenderFrame in Media.cc can do the right thing.

**Comment by r-b-us** [comment]
Hello @morosev ,
Just noticed that the current version has an EncodedVideoFrame version that has the native handle processing. Is this the intended route to get access to compressed H.264 chunks?
