### ISSUE TITLE
Cant connect javascript client to peerserver: 

### ISSUE THREAD

**Issue by byQ96** [webrtc-uwp/webrtc-uwp-sdk#74]
I tried to connect my WebRTC client written in JavaScript, to the peer_server. Here is the code:
`socket = new WebSocket("wss://127.0.0.1:8888");

    socket.onopen = function () {
        console.log("Socket connected!");

        //startStream();
    };

    socket.onerror = fuction () {
        console.log('Socket error.');
    };`
Server can see new client and returns communicate: "New connection...". Unfortunatelly after some time, there's a communicate in browser console that the request timed out: 

> rtc_main.js:221 WebSocket connection to 'wss://127.0.0.1:8888/' failed: WebSocket opening handshake timed out

 OnOpen js event is not called too. I am looking for the peer_connection solution, where I can write my own js app and connect it with C# client.

**Comment by nikolamand** [comment]
As far as i can remember there needs to be a *sign in* as well as *wait* request and *peer id* when connecting to the server (i'm assuming the same peercc server is being used), witch on PeerCC-Browser app is accomplished using socket io and long polling.  
You can find a working example of that [here](https://github.com/OpticalTone/PeerCC-Browser/blob/master/js/signallingchannel.js)  
I hope this will be helpful

**Comment by byQ96** [comment]
Yes it was exacly i was looking for, thank You
