### ISSUE TITLE
bin\prepare.bat failed 

### ISSUE THREAD

**Issue by happyao** [webrtc-uwp/webrtc-uwp-sdk#81]
hi, could anyone help me with this project? Thanks!

I run bin\prepare.bat  -loglevel 4 then failed. The log is:
......
Clang already exists, skipping clang update...
0> Failed to fetch file gs://chromium-gn/e93779cab57d5f36100faa4d88524a1e33be7b0
f for buildtools\win\gn.exe, skipping. [Err: Traceback (most recent call last):
  File "C:\webrtc-uwp-sdk\webrtc\xplatform\depot_tools\gsutil.py", line 182, in
<module>
    sys.exit(main())

........
failed to fetch file gs://chromium-gn/e93779cab57d5f36100faa4d88524a1e33be7b0f f or buildtools\win\gn.exe. 

..........

urllib2.URLError: <urlopen error [Errno 11003] getaddrinfo failed>
]
Downloading 1 files took 6.905000 second(s)

[91mCRITICAL ERROR: Failed downloading gn.exe[0m

[91mFAILURE:Preparing WebRTC development environment has failed.       [0m
=======   WebRTC prepare script summary   =======
=======   platform   =========   cpu   =========   result   =======
[93m          winuwp                 arm               not run[0m
[93m          winuwp                 x86               not run[0m
[93m          winuwp                 x64               not run[0m
[93m          win32                  x86               not run[0m
[93m          win32                  x64               not run[0m
===================================================================

**Comment by jamescadd** [comment]
Hello, could you confirm which branch you're on?  That download is initiate from prepareWebrt.bat
CALL python %DepotToolsPath%\download_from_google_storage.py -b chromium-gn -s buildtools\win\gn.exe.sha1  -  Google's script is initiating the download.  This has happened in the past and is usually a network issue, or it could be that you have the Google WebRTC tooling installed on the same machine and that depot_tools path is interfering with the UWP tools.  Let me know which branch and I'll see if I can repro it.

Thanks,
James

**Comment by happyao** [comment]
> Hello, could you confirm which branch you're on? That download is initiate from prepareWebrt.bat
> CALL python %DepotToolsPath%\download_from_google_storage.py -b chromium-gn -s buildtools\win\gn.exe.sha1 - Google's script is initiating the download. This has happened in the past and is usually a network issue, or it could be that you have the Google WebRTC tooling installed on the same machine and that depot_tools path is interfering with the UWP tools. Let me know which branch and I'll see if I can repro it.
> [](url)
> Thanks,
> James

Hi Thanks James, I use " git clone --recursive https://github.com/webrtc-uwp/webrtc-uwp-sdk.git " to get this repository. I am now on master branch.  This is the whole log. Thanks!
[webrtc-uwp-sdk-log.txt](https://github.com/webrtc-uwp/webrtc-uwp-sdk/files/2546683/webrtc-uwp-sdk-log.txt)

**Comment by happyao** [comment]
> Hello, could you confirm which branch you're on? That download is initiate from prepareWebrt.bat
> CALL python %DepotToolsPath%\download_from_google_storage.py -b chromium-gn -s buildtools\win\gn.exe.sha1 - Google's script is initiating the download. This has happened in the past and is usually a network issue, or it could be that you have the Google WebRTC tooling installed on the same machine and that depot_tools path is interfering with the UWP tools. Let me know which branch and I'll see if I can repro it.
> 
> Thanks,
> James

Hi I have solved this problem by try on window 10 computer. Thanks!
